/** Admin User Manual — content (English + Hindi). See common.js for the format. */
import { t, STATUS } from './common.js';
import { ADMIN_ROLES, AREAS, PERMISSIONS, ACTIONS } from '../roles.js';

const Y = '✅'; const N = '—'; const V = '👁';
const AREA_HI = { dashboard: 'डैशबोर्ड', orders: 'ऑर्डर और डिलीवरी', payments: 'भुगतान', returns: 'रिटर्न और रिफ़ंड', settlements: 'डीलर सेटलमेंट', catalog: 'प्रोडक्ट, कैटेगरी, ऑफ़र, रिव्यू, स्टॉक', pricing: 'लाभ और कीमत',
  customers: 'ग्राहक', marketing: 'मार्केटिंग और ग्राहक मैसेज', support: 'सपोर्ट रिक्वेस्ट', dealers: 'डीलर और रूटिंग', verification: 'डीलर सत्यापन (KYC, दस्तावेज़)', dealer_products: 'डीलर प्रोडक्ट',
  legal: 'Legal & Compliance', ai: 'AI इनसाइट', audit: 'ऑडिट लॉग', settings: 'भुगतान और स्टोर सेटिंग', security: 'सुरक्षा', admins: 'एडमिन यूज़र और रोल' };
const ROLE_HI = { owner: 'Owner (सुपर एडमिन)', manager: 'Manager', support: 'Customer Support', legal: 'Legal Admin', dealer_admin: 'Dealer Admin', finance: 'Finance Admin', operations: 'Operations Admin', readonly: 'Read Only Admin' };
const ACTION_EN = { confirm_payment: 'Confirm payment', reject_payment: 'Reject payment', cancel_order: 'Cancel an order', refund: 'Record refunds', approve_return: 'Approve / reject returns', settle_pay: 'Create & pay settlements', legal_publish: 'Publish legal versions', legal_edit: 'Create / edit legal drafts', bank_reveal: 'Reveal dealer bank account', dealer_routing: 'Dealer routing settings', store_settings: 'Payment & store settings', unlock_accounts: 'Unlock accounts', marketing_send: 'Send customer messages', manage_admins: 'Add admins & change roles' };
const ACTION_HI = { confirm_payment: 'भुगतान पक्का', reject_payment: 'भुगतान अस्वीकार', cancel_order: 'ऑर्डर कैंसल', refund: 'रिफ़ंड दर्ज', approve_return: 'रिटर्न मंज़ूर / अस्वीकार', settle_pay: 'सेटलमेंट बनाना और चुकाना', legal_publish: 'लीगल वर्ज़न प्रकाशित', legal_edit: 'लीगल ड्राफ़्ट बनाना / बदलना', bank_reveal: 'डीलर बैंक खाता देखना', dealer_routing: 'डीलर रूटिंग सेटिंग', store_settings: 'भुगतान और स्टोर सेटिंग', unlock_accounts: 'अकाउंट अनलॉक', marketing_send: 'ग्राहक मैसेज भेजना', manage_admins: 'एडमिन जोड़ना और रोल बदलना' };
const ROLE_LIST = Object.keys(ADMIN_ROLES);
const mark = (r, a) => (r === 'owner' ? Y : PERMISSIONS[r]?.[a] === 'edit' ? Y : PERMISSIONS[r]?.[a] === 'view' ? V : N);

export default {
  key: 'admin',
  file: 'Admin_User_Manual',
  title: t('Admin User Manual', 'एडमिन उपयोगकर्ता मैनुअल'),
  subtitle: t('Complete Guide to Marketplace Administration', 'मार्केटप्लेस प्रशासन की पूरी गाइड'),
  audience: t('For Administrators', 'प्रशासकों के लिए'),
  help: 'admin',
  sections: [
    {
      id: 'login', title: t('Admin Login', 'एडमिन लॉगिन'), shot: 'a_login',
      callouts: [
        ['label:Email', t('Email', 'ईमेल')],
        ['label:Password', t('Password', 'पासवर्ड')],
        ['css:form .btn--primary, form button', t('Sign in', 'साइन इन')],
        ['text:Back to store', t('← Back to store', '← स्टोर पर वापस')],
      ],
      what: t('The "Store admin" sign-in page at /admin.', '/admin पर "Store admin" साइन-इन पेज।'),
      why: t('The admin panel controls money, customer data and legal records, so only authorised staff may enter.', 'एडमिन पैनल पैसे, ग्राहक डेटा और कानूनी रिकॉर्ड नियंत्रित करता है, इसलिए केवल अधिकृत स्टाफ़ प्रवेश कर सकता है।'),
      steps: t(['Open /admin (or footer → "🔐 Admin login").', 'Enter Email and Password → "Sign in".', 'If two-step login is on, enter the 6-digit code from your authenticator app (or a backup code) → "Verify".', 'First sign-in: set your own password ("Set your own password to continue").'], ['/admin खोलें (या फ़ुटर → "🔐 Admin login")।', 'ईमेल और पासवर्ड डालें → "Sign in"।', 'दो-चरण लॉगिन चालू हो तो ऑथेंटिकेटर ऐप का 6 अंकों का कोड (या बैकअप कोड) डालें → "Verify"।', 'पहला साइन-इन: अपना पासवर्ड बनाएँ ("Set your own password to continue")।']),
      after: t('You see the Dashboard. Sessions last 12 hours.', 'Dashboard दिखता है। सत्र 12 घंटे चलता है।'),
      important: t(['Admin passwords: 10+ characters with letters and a number.', '5 wrong attempts lock sign-in for 15 minutes; more attempts lock longer.', 'The admin panel can be limited to allowed networks (IP allow-list).'], ['एडमिन पासवर्ड: 10+ अक्षर, अक्षर और अंक दोनों।', '5 गलत कोशिशों पर 15 मिनट के लिए लॉक; ज़्यादा पर और लंबा।', 'एडमिन पैनल को केवल अनुमत नेटवर्क (IP allow-list) तक सीमित किया जा सकता है।']),
      mistakes: t(['Sharing one admin login between staff', 'Losing the authenticator phone without saving backup codes'], ['एक एडमिन लॉगिन कई स्टाफ़ में बाँटना', 'बैकअप कोड सेव किए बिना ऑथेंटिकेटर फ़ोन खो देना']),
    },
    {
      id: 'dashboard', title: t('Admin Dashboard', 'एडमिन डैशबोर्ड'), shot: 'a_dashboard',
      callouts: [
        ['css:.kpis', t('Tiles: total sales, gross profit, today\'s sales, orders, pending payments, products, low stock, active offers', 'टाइल: कुल बिक्री, सकल लाभ, आज की बिक्री, ऑर्डर, बाकी भुगतान, प्रोडक्ट, कम स्टॉक, सक्रिय ऑफ़र')],
        ['text:Needs attention', t('Needs attention: payments to verify, orders to ship, reviews, low stock', 'ध्यान दें: जाँचने वाले भुगतान, भेजने वाले ऑर्डर, रिव्यू, कम स्टॉक')],
        ['css:.adm-nav, nav', t('Menu of all admin pages', 'सभी एडमिन पेजों का मेन्यू')],
      ],
      what: t('The first admin screen: a summary of the store.', 'पहली एडमिन स्क्रीन: स्टोर का सारांश।'),
      why: t('To see in one minute what needs action today.', 'एक मिनट में देखने के लिए कि आज किस पर काम करना है।'),
      can: t(['Total sales, gross profit, today\'s sales', 'Orders to pack & ship, pending payments', 'Low stock, active offers, reviews to moderate', 'Sales of the last 14 days, recent orders, top products'], ['कुल बिक्री, सकल लाभ, आज की बिक्री', 'पैक व भेजने वाले ऑर्डर, बाकी भुगतान', 'कम स्टॉक, सक्रिय ऑफ़र, मॉडरेट करने वाले रिव्यू', 'पिछले 14 दिन की बिक्री, हाल के ऑर्डर, टॉप प्रोडक्ट']),
      important: t(['Customers, dealers waiting for verification, legal acceptance and policy alerts are on their own pages: Customers, Dealer verification and Legal & Compliance → Overview.'], ['ग्राहक, सत्यापन के इंतज़ार वाले डीलर, कानूनी स्वीकृति और पॉलिसी अलर्ट अपने पेजों पर हैं: Customers, Dealer verification और Legal & Compliance → Overview।']),
      planned: t(['Combined dashboard tiles for total customers, total dealers, pending dealer verification, pending returns, legal acceptance and policy alerts are a Planned Feature.'], ['कुल ग्राहक, कुल डीलर, बाकी डीलर सत्यापन, बाकी रिटर्न, कानूनी स्वीकृति और पॉलिसी अलर्ट की संयुक्त डैशबोर्ड टाइल Planned Feature है।']),
    },
    {
      id: 'customers', title: t('Customer Management', 'ग्राहक प्रबंधन'), shot: 'a_customers',
      callouts: [['css:table', t('Name, email, mobile, orders, spent, joined', 'नाम, ईमेल, मोबाइल, ऑर्डर, खर्च, जुड़ने की तारीख')]],
      what: t('"Customers" — the list of registered accounts.', '"Customers" — रजिस्टर्ड अकाउंट की सूची।'),
      why: t('To know who your customers are and how much they buy.', 'यह जानने के लिए कि आपके ग्राहक कौन हैं और कितना खरीदते हैं।'),
      important: t(['Guest checkouts appear under Orders, not here.', 'Customer legal acceptance is in Legal & Compliance → Acceptance.', 'Treat customer data as confidential (Privacy Policy).'], ['गेस्ट चेकआउट Orders में दिखते हैं, यहाँ नहीं।', 'ग्राहक की कानूनी स्वीकृति Legal & Compliance → Acceptance में है।', 'ग्राहक डेटा को गोपनीय रखें (Privacy Policy)।']),
      planned: t(['Customer search, detail page, export and actions (block, reset password) are Planned Features.'], ['ग्राहक सर्च, विवरण पेज, एक्सपोर्ट और कार्रवाई (ब्लॉक, पासवर्ड रीसेट) Planned Features हैं।']),
    },
    {
      id: 'dealers', title: t('Dealer Management', 'डीलर प्रबंधन'), shot: 'a_dealers',
      callouts: [
        ['css:.tabs', t('Tabs: Dealer orders · Dealers · Routing', 'टैब: Dealer orders · Dealers · Routing')],
        ['text:Add dealer', t('+ Add dealer', '+ डीलर जोड़ें')],
        ['text:Edit', t('Edit dealer — PIN codes, categories, active, reset password', 'डीलर बदलें — PIN कोड, कैटेगरी, सक्रिय, पासवर्ड रीसेट')],
      ],
      what: t('"Dealers" — dealer orders board, dealer list and order routing.', '"Dealers" — डीलर ऑर्डर बोर्ड, डीलर सूची और ऑर्डर रूटिंग।'),
      why: t('Admin uses this page to manage the dealer lifecycle in operation: who serves which PIN codes and categories, and how orders are routed. Onboarding and approval happen in Dealer verification.', 'एडमिन इस पेज से डीलरों का संचालन संभालता है: कौन किन PIN कोड और कैटेगरी पर सेवा देता है, और ऑर्डर कैसे भेजे जाते हैं। ऑनबोर्डिंग और मंज़ूरी Dealer verification में होती है।'),
      can: t(['Dealer orders: follow every dealer order; assign paid orders that have no dealer ("Find dealer")', 'Dealers: add a dealer (one-time password shared by WhatsApp), edit PIN codes ("4110", "411001-411050"), "Ships anywhere in India", categories, priority, Active', 'Routing: auto-send paid orders, auto-move when rejected/not accepted, acceptance time (10–1440 min)'], ['Dealer orders: हर डीलर ऑर्डर देखें; बिना डीलर वाले भुगतान हुए ऑर्डर भेजें ("Find dealer")', 'Dealers: डीलर जोड़ें (एक बार का पासवर्ड WhatsApp से), PIN कोड ("4110", "411001-411050"), "Ships anywhere in India", कैटेगरी, प्राथमिकता, Active बदलें', 'Routing: भुगतान हुए ऑर्डर अपने-आप भेजें, अस्वीकार/समय पर स्वीकार न होने पर अगले को भेजें, स्वीकार का समय (10–1440 मिनट)']),
      statuses: STATUS.onboarding,
      important: t(['A dealer added here gets a 14-day grace period to finish KYC and sign.', 'Approval needs delivery PIN codes to be set here first.'], ['यहाँ जोड़े डीलर को KYC और साइन पूरा करने के लिए 14 दिन का ग्रेस पीरियड मिलता है।', 'मंज़ूरी से पहले यहाँ डिलीवरी PIN कोड सेट होने चाहिए।']),
    },
    {
      id: 'verification', title: t('Dealer Verification', 'डीलर सत्यापन'), shot: 'a_verify_list',
      callouts: [
        ['css:.tabs', t('Tabs: To verify, Docs rejected, In progress, To sign, Approved, Suspended, Rejected', 'टैब: To verify, Docs rejected, In progress, To sign, Approved, Suspended, Rejected')],
        ['css:table', t('KYC, documents, agreement, status and whether the dealer receives orders', 'KYC, दस्तावेज़, एग्रीमेंट, स्टेटस और डीलर को ऑर्डर मिलते हैं या नहीं')],
      ],
      what: t('"🛡️ Dealer verification" — the queue of dealers in onboarding.', '"🛡️ Dealer verification" — ऑनबोर्डिंग वाले डीलरों की कतार।'),
      why: t('A dealer may receive orders only after KYC, documents and the signed agreement are checked and approved.', 'KYC, दस्तावेज़ और साइन किए एग्रीमेंट की जाँच व मंज़ूरी के बाद ही डीलर को ऑर्डर मिल सकते हैं।'),
      steps: t(['Open "🔎 To verify".', 'Open a dealer.', 'Check business and KYC, verify documents, read the signed agreement.', 'Use Decision: ✅ Approve dealer (or request documents / correction / reject).'], ['"🔎 To verify" खोलें।', 'कोई डीलर खोलें।', 'बिज़नेस और KYC जाँचें, दस्तावेज़ सत्यापित करें, साइन किया एग्रीमेंट पढ़ें।', 'Decision: ✅ Approve dealer (या दस्तावेज़/सुधार माँगें/अस्वीकार करें)।']),
      statuses: STATUS.onboarding,
      important: t(['Only Owner and Manager roles can open this page.'], ['यह पेज केवल Owner और Manager रोल खोल सकते हैं।']),
    },
    {
      id: 'kyc', title: t('KYC Management', 'KYC प्रबंधन'), shot: 'a_verify_detail',
      callouts: [
        ['text:Business', t('Business details', 'बिज़नेस विवरण')],
        ['text:KYC & bank', t('KYC & bank (PAN, GSTIN, CIN, bank)', 'KYC और बैंक (PAN, GSTIN, CIN, बैंक)')],
        ['text:Show (logged)', t('Show (logged) — owner can reveal the full account number; this is recorded', 'Show (logged) — ओनर पूरा खाता नंबर देख सकता है; यह दर्ज होता है')],
        ['css:.lgv-steps', t('Onboarding steps with progress', 'ऑनबोर्डिंग चरण और प्रगति')],
      ],
      what: t('The dealer detail page in Dealer verification.', 'Dealer verification में डीलर विवरण पेज।'),
      why: t('To confirm the business is genuine and payments go to the right account.', 'पक्का करने के लिए कि बिज़नेस असली है और भुगतान सही खाते में जाता है।'),
      steps: t(['Compare legal name, PAN and GSTIN with the documents.', 'Check the bank holder name matches the business/proprietor.', 'Reveal the account number only if needed ("Show (logged)").'], ['कानूनी नाम, PAN और GSTIN की दस्तावेज़ों से तुलना करें।', 'जाँचें कि बैंक खाताधारक नाम बिज़नेस/प्रोपराइटर से मेल खाता है।', 'ज़रूरत हो तभी खाता नंबर देखें ("Show (logged)")।']),
      important: t(['Bank numbers are encrypted; every reveal is written to the audit log.'], ['बैंक नंबर एन्क्रिप्टेड हैं; हर बार देखना ऑडिट लॉग में दर्ज होता है।']),
    },
    {
      id: 'documents', title: t('Document Verification', 'दस्तावेज़ सत्यापन'), shot: 'a_verify_docs',
      callouts: [
        ['css:.table thead', t('Document · Status · File · Number/expiry · Uploaded', 'दस्तावेज़ · स्टेटस · फ़ाइल · नंबर/समाप्ति · अपलोड')],
        ['text:Verify', t('✓ Verify', '✓ सत्यापित करें')],
        ['text:Reject', t('✕ Reject — with a reason the dealer sees', '✕ अस्वीकार — कारण के साथ जो डीलर देखता है')],
        ['text:View', t('View / Download', 'देखें / डाउनलोड')],
      ],
      what: t('The Documents section of the dealer detail page.', 'डीलर विवरण पेज का Documents हिस्सा।'),
      why: t('Document verification is necessary to confirm identity, address, tax registration and bank ownership before a dealer can sell.', 'डीलर के बेचने से पहले पहचान, पता, टैक्स रजिस्ट्रेशन और बैंक स्वामित्व पक्का करने के लिए दस्तावेज़ सत्यापन ज़रूरी है।'),
      steps: t(['Tap "View" and check the file is clear, current and in the right name.', 'Tap "✓ Verify", or "✕ Reject" with a reason (quick reasons: blurred, name mismatch, expired, wrong document, number mismatch).', 'To ask for more documents use Decision → "📄 Request documents".'], ['"View" दबाकर जाँचें कि फ़ाइल साफ़, मान्य और सही नाम की है।', '"✓ Verify" दबाएँ, या कारण के साथ "✕ Reject" (तुरंत कारण: धुंधला, नाम मेल नहीं, समाप्त, गलत दस्तावेज़, नंबर मेल नहीं)।', 'और दस्तावेज़ माँगने के लिए Decision → "📄 Request documents"।']),
      after: t('Rejecting notifies the dealer and sets status "Documents rejected". When all required documents are verified and the agreement is signed, "✅ Approve dealer" becomes active.', 'अस्वीकार करने पर डीलर को सूचना जाती है और स्टेटस "Documents rejected" होता है। सारे ज़रूरी दस्तावेज़ सत्यापित और एग्रीमेंट साइन होने पर "✅ Approve dealer" चालू होता है।'),
      statuses: STATUS.document,
      planned: t(['Separate "Reviewer" column and free comments per document are Planned Features (the reviewer is recorded in the audit history).'], ['हर दस्तावेज़ के लिए अलग "Reviewer" कॉलम और खुली टिप्पणी Planned Features हैं (समीक्षक ऑडिट इतिहास में दर्ज होता है)।']),
    },
    {
      id: 'products', title: t('Product Management', 'प्रोडक्ट प्रबंधन'), shot: 'a_products',
      callouts: [
        ['text:Add product', t('Add product', 'प्रोडक्ट जोड़ें')],
        ['css:table', t('MRP, selling price, cost, profit/unit, stock, flags, Live/Hidden', 'MRP, बिक्री कीमत, लागत, लाभ/यूनिट, स्टॉक, फ़्लैग, Live/Hidden')],
      ],
      shot2: 'a_dealer_products',
      callouts2: [
        ['css:.tabs', t('Dealer products queue: To review, Waiting for dealer, Approved, Rejected', 'डीलर प्रोडक्ट कतार: To review, Waiting for dealer, Approved, Rejected')],
      ],
      what: t('"Products" (your catalogue) and "Dealer products" (products dealers sent for review).', '"Products" (आपका कैटलॉग) और "Dealer products" (डीलरों के रिव्यू के लिए भेजे प्रोडक्ट)।'),
      why: t('Every product customers see must have correct details, price, cost and photos.', 'ग्राहकों को दिखने वाले हर प्रोडक्ट का विवरण, कीमत, लागत और फ़ोटो सही होने चाहिए।'),
      can: t(['Add/edit products: details, specifications, SEO, up to 6 photos, MRP, selling price, cost, stock, low-stock alert, visibility', '"✨ Write for me" — help writing descriptions', 'Dealer products: review, set customer price with the 🧮 calculator, "✅ Approve & publish", "✏️ Ask for changes" or "✖️ Reject"', 'Product photos: bulk upload by file name'], ['प्रोडक्ट जोड़ें/बदलें: विवरण, स्पेसिफ़िकेशन, SEO, 6 तक फ़ोटो, MRP, बिक्री कीमत, लागत, स्टॉक, कम स्टॉक अलर्ट, दिखना', '"✨ Write for me" — विवरण लिखने में मदद', 'Dealer products: रिव्यू करें, 🧮 कैलकुलेटर से ग्राहक कीमत तय करें, "✅ Approve & publish", "✏️ Ask for changes" या "✖️ Reject"', 'Product photos: फ़ाइल नाम से बल्क अपलोड']),
      important: t(['A product that has orders is archived instead of deleted.', 'The dealer never sees the customer price, MRP or margin.'], ['जिस प्रोडक्ट के ऑर्डर हैं उसे डिलीट की जगह आर्काइव किया जाता है।', 'डीलर ग्राहक कीमत, MRP या मार्जिन कभी नहीं देखता।']),
    },
    {
      id: 'inventory', title: t('Inventory', 'इन्वेंटरी'), shot: 'a_inventory',
      callouts: [['text:Stock', t('Stock column — edit in the product form; "Low-stock alert at"', 'Stock कॉलम — प्रोडक्ट फ़ॉर्म में बदलें; "Low-stock alert at"')]],
      what: t('Stock is managed per product (Products) and by dealers for their listings.', 'स्टॉक हर प्रोडक्ट (Products) में और डीलर अपनी लिस्टिंग के लिए संभालते हैं।'),
      why: t('Correct stock prevents selling items you cannot deliver.', 'सही स्टॉक से ऐसा सामान नहीं बिकता जो दे न सकें।'),
      can: t(['See low stock on the Dashboard', 'Edit stock and low-stock threshold in the product form', 'AI insights → Forecast & stock alerts: what to reorder'], ['Dashboard पर कम स्टॉक देखें', 'प्रोडक्ट फ़ॉर्म में स्टॉक और कम-स्टॉक सीमा बदलें', 'AI insights → Forecast & stock alerts: क्या दोबारा मँगाना है']),
      important: t(['Cancelling an order puts its stock back. Dealer stock updates go live immediately.'], ['ऑर्डर कैंसल करने पर स्टॉक वापस जुड़ता है। डीलर का स्टॉक अपडेट तुरंत लाइव होता है।']),
    },
    {
      id: 'orders', title: t('Order Management', 'ऑर्डर प्रबंधन'), shot: 'a_orders',
      callouts: [
        ['ph:Search order', t('Search order ID, name or phone', 'ऑर्डर ID, नाम या फ़ोन खोजें')],
        ['css:select', t('Filter by payment status and order status', 'भुगतान और ऑर्डर स्टेटस से फ़िल्टर')],
        ['css:table', t('Orders list — tap one to open details', 'ऑर्डर सूची — विवरण के लिए दबाएँ')],
      ],
      shot2: 'a_order_detail',
      callouts2: [
        ['text:Customer', t('Customer and payment (UTR, screenshot)', 'ग्राहक और भुगतान (UTR, स्क्रीनशॉट)')],
        ['text:Dealer', t('🏪 Dealer — assign / auto-pick best', '🏪 डीलर — भेजें / सबसे अच्छा अपने-आप')],
        ['text:Actions', t('Actions: Confirm Payment, Process, Mark Shipped, Out for Delivery, Delivered, Cancel, Mark Refunded', 'कार्रवाई: Confirm Payment, Process, Mark Shipped, Out for Delivery, Delivered, Cancel, Mark Refunded')],
      ],
      what: t('"Orders" — every order and its detail window.', '"Orders" — हर ऑर्डर और उसकी विवरण विंडो।'),
      why: t('To confirm payments and move each order through packing and delivery.', 'भुगतान पक्का करने और हर ऑर्डर को पैकिंग व डिलीवरी तक ले जाने के लिए।'),
      steps: t(['Open an order.', 'Check payment (UTR / screenshot) → "Confirm Payment" or "Reject Payment".', 'Assign a dealer (or let auto-routing do it) — or process it yourself: "Process Order" → "Mark Shipped" (courier + tracking) → "Out for Delivery" → "Mark Delivered".', 'Add an "Internal note" when needed.'], ['ऑर्डर खोलें।', 'भुगतान (UTR / स्क्रीनशॉट) जाँचें → "Confirm Payment" या "Reject Payment"।', 'डीलर भेजें (या ऑटो-रूटिंग करने दें) — या खुद प्रोसेस करें: "Process Order" → "Mark Shipped" (कूरियर + ट्रैकिंग) → "Out for Delivery" → "Mark Delivered"।', 'ज़रूरत हो तो "Internal note" जोड़ें।']),
      statuses: STATUS.order,
      important: t(['Reject Payment and Cancel Order ask you to tap twice.', 'Confirm/Reject Payment: Owner, Manager or Finance. Cancel: Owner, Manager, Finance or Operations. Mark Refunded (cancelled orders): Owner or Finance.', 'Every change sends the customer an update and is written to the order history.'], ['Reject Payment और Cancel Order में दो बार दबाना पड़ता है।', 'Confirm/Reject Payment: Owner, Manager या Finance। Cancel: Owner, Manager, Finance या Operations। Mark Refunded (कैंसल ऑर्डर): Owner या Finance।', 'हर बदलाव पर ग्राहक को अपडेट जाता है और ऑर्डर इतिहास में दर्ज होता है।']),
    },
    {
      id: 'payments', title: t('Payment Management', 'भुगतान प्रबंधन'), shot: 'a_payments',
      callouts: [
        ['css:.tabs', t('Tabs: All, To verify, Not paid yet, Confirmed, Rejected', 'टैब: All, To verify, Not paid yet, Confirmed, Rejected')],
        ['text:UTR / reference', t('UTR / reference and payment proof (screenshot link when uploaded)', 'UTR / रेफ़रेंस और भुगतान प्रमाण (अपलोड होने पर स्क्रीनशॉट लिंक)')],
        ['text:Confirm', t('Confirm / Reject', 'पक्का करें / अस्वीकार करें')],
      ],
      what: t('"Payments" — the UPI verification queue.', '"Payments" — UPI सत्यापन कतार।'),
      why: t('Manual UPI payments must be matched with the bank statement before the order is processed.', 'ऑर्डर प्रोसेस होने से पहले मैन्युअल UPI भुगतान को बैंक स्टेटमेंट से मिलाना ज़रूरी है।'),
      steps: t(['Open "To verify".', 'Find the UTR and amount in your bank statement.', 'Tap "Confirm" if it matches; "Reject" if not.'], ['"To verify" खोलें।', 'बैंक स्टेटमेंट में UTR और रकम ढूँढें।', 'मेल खाए तो "Confirm"; नहीं तो "Reject"।']),
      statuses: STATUS.payment,
      important: t(['Check the ⚠️ risk badge before confirming large or unusual orders.', 'Payment settings (UPI ID, QR, gateway) are in "Payment & Store" (Owner only).'], ['बड़े या असामान्य ऑर्डर पक्का करने से पहले ⚠️ रिस्क बैज देखें।', 'भुगतान सेटिंग (UPI ID, QR, गेटवे) "Payment & Store" में है (केवल Owner)।']),
    },
    {
      id: 'settlement', title: t('Settlement', 'सेटलमेंट'), shot: 'a_settlements',
      callouts: [
        ['text:Due now', t('Due now: every dealer with delivered orders not yet settled', 'Due now: हर डीलर जिसके डिलीवर ऑर्डर अभी सेटल नहीं हुए')],
        ['text:Review & create', t('Review & create — see every order, return and the net', 'Review & create — हर ऑर्डर, रिटर्न और शुद्ध राशि देखें')],
        ['text:Settlement batches', t('Settlement batches with status, net and UTR', 'सेटलमेंट बैच — स्टेटस, शुद्ध राशि और UTR')],
      ],
      shot2: 'a_commercial',
      callouts2: [['text:Commercial terms', t('Commercial terms per dealer: model, commission, fees, settlement days, return window, penalty, logistics', 'हर डीलर की कमर्शियल शर्तें: मॉडल, कमीशन, फ़ीस, सेटलमेंट दिन, रिटर्न अवधि, पेनल्टी, लॉजिस्टिक्स')]],
      what: t('"🧾 Dealer settlements": what each dealer is owed for delivered orders, less returns and fees, and the payment batches.', '"🧾 Dealer settlements": डिलीवर ऑर्डर के लिए हर डीलर का बकाया, रिटर्न और फ़ीस घटाकर, और भुगतान बैच।'),
      why: t('So every dealer is paid the right amount, once, with a record the dealer can see.', 'ताकि हर डीलर को सही राशि, एक बार, ऐसे रिकॉर्ड के साथ मिले जो डीलर भी देख सके।'),
      can: t(['See what is due to each dealer', 'Add adjustments (penalty − / bonus +)', 'Create a settlement batch', 'Mark it paid with the bank UTR', 'Cancel a batch that was not paid'], ['हर डीलर का बकाया देखें', 'समायोजन जोड़ें (पेनल्टी − / बोनस +)', 'सेटलमेंट बैच बनाएँ', 'बैंक UTR के साथ Paid करें', 'बिना चुकाया बैच कैंसल करें']),
      steps: t(['Open "Dealer settlements".', 'In "Due now" tap "Review & create" for a dealer.', 'Check each order (📦) and return (↩️); add adjustments if needed.', 'Tap "Create settlement for ₹…" (status Processing).', 'Pay from your bank to the dealer\'s verified account.', 'Open the batch, type the UTR, tap "Mark paid". The dealer is notified.'], ['"Dealer settlements" खोलें।', '"Due now" में डीलर के लिए "Review & create" दबाएँ।', 'हर ऑर्डर (📦) और रिटर्न (↩️) जाँचें; ज़रूरत हो तो समायोजन जोड़ें।', '"Create settlement for ₹…" दबाएँ (स्टेटस Processing)।', 'अपने बैंक से डीलर के सत्यापित खाते में भुगतान करें।', 'बैच खोलें, UTR लिखें, "Mark paid" दबाएँ। डीलर को सूचना जाती है।']),
      flow: 'settlement_flow',
      statuses: STATUS.settlement,
      important: t(['Only the Owner and Finance Admin can create or pay settlements; others can view.', 'An order or return is never counted in two active batches. Cancelling a batch releases its orders for the next one.', 'A batch is never created for zero or a negative net — returns are carried forward.', 'Supply model: dealer price × quantity (the snapshot taken when the order was placed). Commission model: item value − commission − platform fee − payment fee.', 'Changing commercial terms after the dealer signed asks the dealer to sign again; new orders pause until then.'], ['केवल Owner और Finance Admin सेटलमेंट बना या चुका सकते हैं; बाकी देख सकते हैं।', 'कोई ऑर्डर या रिटर्न दो चालू बैच में नहीं गिना जाता। बैच कैंसल करने पर उसके ऑर्डर अगले बैच में आते हैं।', 'शून्य या माइनस शुद्ध राशि का बैच कभी नहीं बनता — रिटर्न आगे जाते हैं।', 'Supply मॉडल: डीलर प्राइस × मात्रा (ऑर्डर के समय का)। Commission मॉडल: आइटम मूल्य − कमीशन − प्लेटफ़ॉर्म फ़ीस − पेमेंट फ़ीस।', 'डीलर के साइन के बाद कमर्शियल शर्तें बदलने पर डीलर से दोबारा साइन माँगा जाता है; तब तक नए ऑर्डर रुकते हैं।']),
      mistakes: t(['Marking paid before the bank transfer is done', 'Typing a UTR from another payment (it is refused if already used)'], ['बैंक ट्रांसफ़र होने से पहले Paid करना', 'किसी दूसरे भुगतान का UTR लिखना (पहले से उपयोग हुआ हो तो मना होता है)']),
    },
    {
      id: 'returns', title: t('Returns', 'रिटर्न'), shot: 'a_returns',
      callouts: [
        ['css:.chips', t('Filter: New, Approved, Received, Refunded, Rejected, All', 'फ़िल्टर: New, Approved, Received, Refunded, Rejected, All')],
        ['css:table', t('Return number, order, customer, items, reason, photo, refund amount, status', 'रिटर्न नंबर, ऑर्डर, ग्राहक, आइटम, कारण, फ़ोटो, रिफ़ंड राशि, स्टेटस')],
        ['text:Decide', t('Decide: approve (refund can be lowered) or reject with a reason', 'Decide: मंज़ूर (रिफ़ंड घटा सकते हैं) या कारण के साथ अस्वीकार')],
      ],
      what: t('"↩️ Returns & refunds" → Returns: return requests customers send from their order page.', '"↩️ Returns & refunds" → Returns: ग्राहकों के ऑर्डर पेज से भेजी गई रिटर्न रिक्वेस्ट।'),
      why: t('One place to check, approve and receive returns, put resaleable stock back and open the refund for finance.', 'रिटर्न जाँचने, मंज़ूर करने और प्राप्त करने, बिकने लायक स्टॉक वापस रखने और फ़ाइनेंस के लिए रिफ़ंड खोलने की एक जगह।'),
      steps: t(['Open Returns & refunds → New.', 'Tap "Decide": check items, reason and photo.', 'Approve (optionally lower the refund) or reject with a note the customer sees.', 'Arrange the pickup; the delivering dealer is told automatically.', 'When the item arrives, tap "Mark received" and tick "resaleable" to put it back in stock.', 'A refund opens in the Refunds tab for finance.'], ['Returns & refunds → New खोलें।', '"Decide" दबाएँ: आइटम, कारण और फ़ोटो जाँचें।', 'मंज़ूर करें (चाहें तो रिफ़ंड घटाएँ) या ग्राहक को दिखने वाले नोट के साथ अस्वीकार करें।', 'पिकअप करवाएँ; डिलीवर करने वाले डीलर को अपने-आप सूचना जाती है।', 'सामान आने पर "Mark received" दबाएँ और स्टॉक में वापस रखने के लिए "resaleable" टिक करें।', 'फ़ाइनेंस के लिए Refunds टैब में रिफ़ंड खुलता है।']),
      statuses: STATUS.returns,
      important: t(['The refund amount is calculated from what the customer paid (after discounts) plus delivery for damaged/wrong/missing items. You can lower it, never raise it.', 'Returns are accepted within 7 days of delivery (damaged/wrong/missing: 48 hours).', 'Owner, Manager, Finance, Operations and Support can decide returns; only Owner and Finance record refunds.'], ['रिफ़ंड राशि ग्राहक के भुगतान (छूट के बाद) और टूटे/गलत/कम सामान पर डिलीवरी शुल्क से बनती है। आप घटा सकते हैं, बढ़ा नहीं।', 'डिलीवरी के 7 दिन में रिटर्न (टूटा/गलत/कम: 48 घंटे)।', 'Owner, Manager, Finance, Operations और Support रिटर्न तय कर सकते हैं; रिफ़ंड केवल Owner और Finance दर्ज करते हैं।']),
    },
    {
      id: 'refunds', title: t('Refunds', 'रिफ़ंड'), shot: 'a_refunds',
      callouts: [
        ['css:.kpis', t('Refunds to pay, failed and paid (amounts)', 'चुकाने बाकी, फ़ेल और चुकाए गए रिफ़ंड (राशि)')],
        ['css:table', t('Order, cancelled order / return, amount, status, reference', 'ऑर्डर, कैंसल ऑर्डर / रिटर्न, राशि, स्टेटस, रेफ़रेंस')],
        ['text:Record refund', t('Record refund — reference, method; or mark failed', 'Record refund — रेफ़रेंस, तरीका; या फ़ेल दर्ज करें')],
      ],
      what: t('"↩️ Returns & refunds" → Refunds: every refund owed for cancelled paid orders and received returns.', '"↩️ Returns & refunds" → Refunds: कैंसल हुए भुगतान वाले ऑर्डर और प्राप्त रिटर्न के सभी देय रिफ़ंड।'),
      why: t('So every refund is paid once, never more than the customer paid, and the customer sees the reference.', 'ताकि हर रिफ़ंड एक बार दिया जाए, ग्राहक के भुगतान से ज़्यादा कभी नहीं, और ग्राहक रेफ़रेंस देख सके।'),
      steps: t(['Open Refunds → "To pay".', 'Send the money (gateway refund or UPI/bank transfer).', 'Tap "Record refund", type the reference (UTR / refund ID) and method, tap "Mark refunded".', 'If the bank returns it, tap "Record refund" → "Mark failed (retry later)" with the reason, then record it again after retrying.'], ['Refunds → "To pay" खोलें।', 'पैसा भेजें (गेटवे रिफ़ंड या UPI/बैंक ट्रांसफ़र)।', '"Record refund" दबाएँ, रेफ़रेंस (UTR / रिफ़ंड ID) और तरीका लिखें, "Mark refunded" दबाएँ।', 'बैंक लौटा दे तो "Record refund" → "Mark failed (retry later)" कारण के साथ, फिर दोबारा भेजकर दर्ज करें।']),
      statuses: STATUS.refund,
      important: t(['Recording a refund does not send money by itself — send it first.', 'A refund cannot be marked paid twice, a reference can be used once, and refunds can never add up to more than the order total.', 'When everything paid is refunded, the order payment shows "Refunded"; partial refunds keep "Payment Confirmed" with the refund listed.', 'Cancelling a paid order opens a full refund automatically (also when a customer cancels).'], ['रिफ़ंड दर्ज करने से अपने-आप पैसा नहीं जाता — पहले भेजें।', 'एक रिफ़ंड दो बार Paid नहीं होता, एक रेफ़रेंस एक बार ही चलता है, और रिफ़ंड का जोड़ ऑर्डर कुल से ज़्यादा नहीं हो सकता।', 'पूरा भुगतान लौटने पर ऑर्डर का भुगतान "Refunded" दिखता है; आंशिक रिफ़ंड में "Payment Confirmed" रहता है और रिफ़ंड सूची में दिखता है।', 'भुगतान वाला ऑर्डर कैंसल करने पर (ग्राहक द्वारा भी) पूरा रिफ़ंड अपने-आप खुलता है।']),
      planned: t(['Sending gateway refunds directly from the admin (instead of recording them) is a Planned Feature.'], ['एडमिन से सीधे गेटवे रिफ़ंड भेजना (सिर्फ़ दर्ज करने की जगह) Planned Feature है।']),
    },
    {
      id: 'support', title: t('Customer Support', 'ग्राहक सहायता'), shot: 'a_support',
      callouts: [
        ['css:.kpis', t('Open, waiting for customer, resolved, satisfaction', 'खुली, ग्राहक का इंतज़ार, हल, संतुष्टि')],
        ['ph:Search name', t('Search name, phone, order, HELP-…', 'नाम, फ़ोन, ऑर्डर, HELP-… खोजें')],
        ['css:.tickets, select', t('Filter and ticket list — each ticket shows status and priority', 'फ़िल्टर और टिकट सूची — हर टिकट पर स्टेटस और प्राथमिकता')],
      ],
      what: t('"Support requests" (page title "Customer support").', '"Support requests" (पेज शीर्षक "Customer support")।'),
      why: t('To answer customer requests quickly and keep a record of every conversation.', 'ग्राहक रिक्वेस्ट का जल्दी जवाब देने और हर बातचीत का रिकॉर्ड रखने के लिए।'),
      steps: t(['Filter "Needs attention".', 'Open a ticket; set priority (Normal/High/Urgent).', 'Use a quick reply or write one; choose what happens after sending (wait for customer / keep working / mark resolved).', 'Tap "Send reply".'], ['"Needs attention" फ़िल्टर करें।', 'टिकट खोलें; प्राथमिकता तय करें (Normal/High/Urgent)।', 'तुरंत जवाब चुनें या लिखें; भेजने के बाद क्या हो चुनें (ग्राहक का इंतज़ार / काम जारी / हल)।', '"Send reply" दबाएँ।']),
      statuses: STATUS.ticket,
      planned: t(['Assigning tickets to a team member is a Planned Feature.'], ['टिकट किसी टीम सदस्य को सौंपना Planned Feature है।']),
    },
    {
      id: 'dealersupport', title: t('Dealer Support', 'डीलर सहायता'),
      what: t('How the team supports dealers today.', 'आज टीम डीलरों की मदद कैसे करती है।'),
      why: t('Dealers contact the team by phone, WhatsApp or email.', 'डीलर फ़ोन, WhatsApp या ईमेल से टीम से संपर्क करते हैं।'),
      can: t(['Reset a dealer password (Dealers → Edit → Reset password)', 'Change PIN codes, categories or active status', 'Message a dealer about a policy issue (Legal & Compliance → Dealer compliance → Violations → Contact dealer)', 'Ask to re-sign, request documents or corrections (Dealer verification → Decision)'], ['डीलर पासवर्ड रीसेट करें (Dealers → Edit → Reset password)', 'PIN कोड, कैटेगरी या सक्रिय स्थिति बदलें', 'पॉलिसी मामले पर डीलर को संदेश (Legal & Compliance → Dealer compliance → Violations → Contact dealer)', 'दोबारा साइन, दस्तावेज़ या सुधार माँगें (Dealer verification → Decision)']),
      planned: t(['A dealer support-ticket queue is a Planned Feature.'], ['डीलर सपोर्ट-टिकट कतार Planned Feature है।']),
    },
    {
      id: 'legal', title: t('Legal & Policies — Legal & Compliance Center', 'कानूनी और पॉलिसी — Legal & Compliance Center'), shot: 'a_legal_overview',
      callouts: [
        ['css:.lc-hero', t('Search and "+ Create New Policy"', 'सर्च और "+ Create New Policy"')],
        ['css:.lc-kpis', t('Active Policies · Pending Review · Expiring Soon · User Acceptance', 'Active Policies · Pending Review · Expiring Soon · User Acceptance')],
        ['css:.lc-flow', t('Approval workflow with counts', 'गिनती के साथ अप्रूवल वर्कफ़्लो')],
        ['css:.lc-cats', t('Customer, Dealer and Company policy categories', 'ग्राहक, डीलर और कंपनी पॉलिसी श्रेणियाँ')],
      ],
      what: t('"⚖️ Legal & Compliance" — the central legal control center.', '"⚖️ Legal & Compliance" — केंद्रीय कानूनी नियंत्रण केंद्र।'),
      why: t('Admin uses it to create, review, approve, publish, update and track all legal policies and agreements, and to watch dealer compliance.', 'एडमिन इससे सभी कानूनी पॉलिसी और एग्रीमेंट बनाता, जाँचता, मंज़ूर करता, प्रकाशित करता, अपडेट करता और ट्रैक करता है, और डीलर अनुपालन देखता है।'),
      can: t(['Overview: KPIs, workflow, categories, "Needs your attention", recent activity, acceptance, policy checklist', 'Policy library (31 policies): Customer — Terms, Privacy, Payment, Shipping, Cancellation/Return/Refund, Reviews, Account security, Prohibited activities, Complaints. Dealer — Agreement, T&C, KYC, Listing, Pricing & Fees, Settlement, Fulfilment, Returns, Customer communication, Customer data, IP, Product safety, Performance, Violations/Suspension/Termination. Company — Platform terms, Data protection, Cookies, Communication, Dispute resolution, Fraud, Security, Legal notice', 'Acceptance, Dealer compliance, Calendar, Notifications, Audit trail, Settings'],
        ['Overview: KPI, वर्कफ़्लो, श्रेणियाँ, "Needs your attention", हाल की गतिविधि, स्वीकृति, पॉलिसी चेकलिस्ट', 'पॉलिसी लाइब्रेरी (31 पॉलिसी): ग्राहक — Terms, Privacy, Payment, Shipping, Cancellation/Return/Refund, Reviews, Account security, Prohibited activities, Complaints. डीलर — Agreement, T&C, KYC, Listing, Pricing & Fees, Settlement, Fulfilment, Returns, Customer communication, Customer data, IP, Product safety, Performance, Violations/Suspension/Termination. कंपनी — Platform terms, Data protection, Cookies, Communication, Dispute resolution, Fraud, Security, Legal notice', 'Acceptance, Dealer compliance, Calendar, Notifications, Audit trail, Settings']),
      flow: 'policy_workflow',
      statuses: STATUS.policy,
      important: t(['All policy text is original Utsav Ghar wording. A qualified lawyer must review and approve every document before it is published.', 'Owner can create/approve/publish; Manager can view.'], ['सारा पॉलिसी पाठ Utsav Ghar का अपना है। प्रकाशित करने से पहले हर दस्तावेज़ योग्य वकील से जाँचवाना और मंज़ूर करवाना ज़रूरी है।', 'Owner बना/मंज़ूर/प्रकाशित कर सकता है; Manager देख सकता है।']),
    },
    {
      id: 'agreements', title: t('Agreement Management', 'एग्रीमेंट प्रबंधन'), shot: 'a_legal_library',
      callouts: [
        ['css:.lc-filters', t('Filters: All, Customer, Dealer, Company, Published, Draft, Review, Scheduled, Expired, Archived', 'फ़िल्टर: All, Customer, Dealer, Company, Published, Draft, Review, Scheduled, Expired, Archived')],
        ['css:.lc-pol', t('Policy card: status, version, effective, updated, next review, accepted by', 'पॉलिसी कार्ड: स्टेटस, वर्ज़न, लागू, अपडेट, अगली समीक्षा, स्वीकार करने वाले')],
        ['css:.lc-pol__acts', t('View · Edit / New version · Preview · PDF · History', 'View · Edit / New version · Preview · PDF · History')],
        ['css:.lc-pol__wf', t('Next workflow step', 'वर्कफ़्लो का अगला कदम')],
      ],
      shot2: 'a_legal_editor',
      callouts2: [
        ['css:.lc-ed__meta', t('Title, version, owner, dates, "What changed?", simple explanation', 'शीर्षक, वर्ज़न, ओनर, तारीखें, "What changed?", आसान व्याख्या')],
        ['css:.lc-ed__tools', t('Insert: section, subheading, simple line, bullets, numbered, table, notice, definition, link, bold', 'जोड़ें: सेक्शन, उप-शीर्षक, आसान लाइन, बुलेट, नंबर, टेबल, सूचना, परिभाषा, लिंक, बोल्ड')],
        ['css:.lc-ed__preview', t('Live preview as users see it', 'यूज़र जैसा देखेंगे वैसा लाइव प्रीव्यू')],
      ],
      what: t('Policy library, the "Create New Policy" wizard and the policy editor.', 'पॉलिसी लाइब्रेरी, "Create New Policy" विज़ार्ड और पॉलिसी एडिटर।'),
      why: t('To keep every agreement and policy accurate, current and approved.', 'हर एग्रीमेंट और पॉलिसी को सही, मौजूदा और मंज़ूर रखने के लिए।'),
      steps: t(['"+ Create New Policy": choose type → basic information (name, description, owner, version, effective and review dates, applicable users, countries, status) → simple explanation → start from live version, starter template or blank.', 'Edit in the editor; write "What changed?"; tick "Important change" if people must accept again.', '"Send for internal review →" → "✓ Pass internal review" → "⚖️ Record legal approval" (lawyer name + confirmation) → "🚀 Publish…" (effective date, next review date).', 'Use "↩ Request changes" to send back.'],
        ['"+ Create New Policy": प्रकार चुनें → बुनियादी जानकारी (नाम, विवरण, ओनर, वर्ज़न, लागू और समीक्षा तारीख, लागू यूज़र, देश, स्टेटस) → आसान व्याख्या → लाइव वर्ज़न, स्टार्टर टेम्पलेट या खाली से शुरू करें।', 'एडिटर में बदलें; "What changed?" लिखें; लोगों को दोबारा स्वीकार करना हो तो "Important change" टिक करें।', '"Send for internal review →" → "✓ Pass internal review" → "⚖️ Record legal approval" (वकील का नाम + पुष्टि) → "🚀 Publish…" (लागू तारीख, अगली समीक्षा तारीख)।', 'वापस भेजने के लिए "↩ Request changes"।']),
      statuses: STATUS.policy,
      important: t(['PDF management: every version has View PDF / Download PDF / Print. Policy PDFs include logo, company name, document name, version, effective date, full content, page numbers, footer, reference number and approval information. Signed dealer agreements also include dealer name and ID, signature, date/time, version and digital acceptance details (OTP, IP, device, fingerprint).', 'Do not change the meaning of legally approved text when writing the simple explanation.'],
        ['PDF प्रबंधन: हर वर्ज़न में View PDF / Download PDF / Print है। पॉलिसी PDF में लोगो, कंपनी नाम, दस्तावेज़ नाम, वर्ज़न, लागू तारीख, पूरा पाठ, पेज नंबर, फ़ुटर, रेफ़रेंस नंबर और मंज़ूरी जानकारी होती है। साइन किए डीलर एग्रीमेंट में डीलर नाम और ID, सिग्नेचर, तारीख/समय, वर्ज़न और डिजिटल स्वीकृति विवरण (OTP, IP, डिवाइस, फ़िंगरप्रिंट) भी होते हैं।', 'आसान व्याख्या लिखते समय कानूनी रूप से मंज़ूर पाठ का अर्थ न बदलें।']),
    },
    {
      id: 'versions', title: t('Agreement Version Control', 'एग्रीमेंट वर्ज़न कंट्रोल'), shot: 'a_legal_history',
      callouts: [
        ['css:.lc-vtl li', t('Each version: created, internal review, approved by, effective, change summary, acceptance count', 'हर वर्ज़न: बनाया, आंतरिक समीक्षा, मंज़ूर करने वाला, लागू, बदलाव सारांश, स्वीकृति गिनती')],
        ['text:New version', t('+ New version — starts a new draft; the live version is never overwritten. "Audit for this policy" appears here once actions are logged', '+ नया वर्ज़न — नया ड्राफ़्ट शुरू होता है; लाइव वर्ज़न कभी नहीं बदला जाता। कार्रवाई दर्ज होने पर यहाँ "इस पॉलिसी का ऑडिट" दिखता है')],
      ],
      what: t('"🕘 History" on any policy.', 'किसी भी पॉलिसी पर "🕘 History"।'),
      why: t('Old versions must never be overwritten: each customer and dealer accepted a specific text, and the company must be able to show exactly what was agreed and when.', 'पुराने वर्ज़न कभी बदले नहीं जाने चाहिए: हर ग्राहक और डीलर ने एक खास पाठ स्वीकार किया, और कंपनी को ठीक-ठीक दिखाना होता है कि क्या और कब तय हुआ।'),
      flow: 'policy_versions',
      can: t(['Version', 'Created date and by', 'Approved by (lawyer) and date', 'Effective date', 'Change summary', 'Acceptance count'], ['वर्ज़न', 'बनाने की तारीख और किसने', 'मंज़ूर करने वाला (वकील) और तारीख', 'लागू होने की तारीख', 'बदलाव सारांश', 'स्वीकृति की गिनती']),
      important: t(['Published and archived versions cannot be edited or deleted. Changes always create a new version.', 'A version marked "Important change" makes people accept again before their next order.'], ['प्रकाशित और आर्काइव वर्ज़न बदले या डिलीट नहीं हो सकते। बदलाव से हमेशा नया वर्ज़न बनता है।', '"Important change" वाले वर्ज़न पर लोगों को अगले ऑर्डर से पहले दोबारा स्वीकार करना होता है।']),
    },
    {
      id: 'records', title: t('Digital Agreement Records', 'डिजिटल एग्रीमेंट रिकॉर्ड'), shot: 'a_legal_acceptance',
      callouts: [
        ['css:.lc-acc', t('Per agreement: accepted, earlier version, pending', 'हर एग्रीमेंट: स्वीकार, पुराना वर्ज़न, बाकी')],
        ['text:View acceptance', t('View acceptance / Pending list', 'स्वीकृति / बाकी सूची देखें')],
        ['text:Export report', t('⬇️ Export report (CSV)', '⬇️ रिपोर्ट एक्सपोर्ट (CSV)')],
      ],
      what: t('Legal & Compliance → "✅ Acceptance".', 'Legal & Compliance → "✅ Acceptance"।'),
      why: t('The company needs to know which agreement version each customer/dealer accepted and when.', 'कंपनी को जानना होता है कि हर ग्राहक/डीलर ने कौन सा वर्ज़न कब स्वीकार किया।'),
      can: t(['See accepted / earlier version / pending for each agreement (e.g. Dealer Agreement v2.0 — Accepted 12,450 · Pending 324)', 'Open the people lists', 'Search acceptance records by name, email, mobile or agreement number and open the PDF', 'Export a CSV report'], ['हर एग्रीमेंट के लिए स्वीकार / पुराना वर्ज़न / बाकी देखें (जैसे Dealer Agreement v2.0 — स्वीकार 12,450 · बाकी 324)', 'लोगों की सूची खोलें', 'नाम, ईमेल, मोबाइल या एग्रीमेंट नंबर से रिकॉर्ड खोजें और PDF खोलें', 'CSV रिपोर्ट एक्सपोर्ट करें']),
      important: t(['Dealer legal profiles (Dealer compliance) show each dealer\'s agreement version, signed date, signature method, KYC and documents, with "Download Signed PDF".'], ['डीलर लीगल प्रोफ़ाइल (Dealer compliance) में हर डीलर का एग्रीमेंट वर्ज़न, साइन तारीख, सिग्नेचर तरीका, KYC और दस्तावेज़ "Download Signed PDF" के साथ दिखते हैं।']),
    },
    {
      id: 'violations', title: t('Policy Violations', 'पॉलिसी उल्लंघन'), shot: 'a_violations',
      callouts: [
        ['css:.lc-subtabs', t('Active · Open · Correction requested · Resolved · Closed', 'Active · Open · Correction requested · Resolved · Closed')],
        ['text:Record violation', t('＋ Record violation', '＋ उल्लंघन दर्ज करें')],
        ['css:table', t('Dealer · Violation · Severity · Date · Status · Actions', 'डीलर · उल्लंघन · गंभीरता · तारीख · स्टेटस · कार्रवाई')],
      ],
      what: t('Dealer compliance → "🚩 Policy violations".', 'Dealer compliance → "🚩 Policy violations"।'),
      why: t('To record problems fairly, tell the dealer, give a chance to fix them and act when needed — with a full history.', 'मामलों को निष्पक्ष रूप से दर्ज करने, डीलर को बताने, सुधार का मौका देने और ज़रूरत पर कार्रवाई करने के लिए — पूरे इतिहास के साथ।'),
      steps: t(['"＋ Record violation": dealer, type, severity (🟢 Low, 🟡 Medium, 🟠 High, 🔴 Critical), policy, days to respond, what happened.', 'Use Actions: View, Contact dealer, Request correction, Suspend listing, Suspend dealer, Mark resolved, Close violation.'], ['"＋ Record violation": डीलर, प्रकार, गंभीरता (🟢 Low, 🟡 Medium, 🟠 High, 🔴 Critical), पॉलिसी, जवाब के दिन, क्या हुआ।', 'Actions: View, Contact dealer, Request correction, Suspend listing, Suspend dealer, Mark resolved, Close violation।']),
      statuses: STATUS.violation,
      important: t(['The dealer is notified in the app and by email/SMS.', '"Suspend listing" hides that product from the store; "Suspend dealer" pauses new orders.'], ['डीलर को ऐप और ईमेल/SMS से सूचना जाती है।', '"Suspend listing" उस प्रोडक्ट को स्टोर से छिपाता है; "Suspend dealer" नए ऑर्डर रोकता है।']),
    },
    {
      id: 'health', title: t('Dealer Account Health', 'डीलर अकाउंट हेल्थ'), shot: 'a_health',
      callouts: [
        ['css:.lc-hlevels', t('Dealers by level: Good, Needs attention, Warning, Restricted', 'स्तर अनुसार डीलर: Good, Needs attention, Warning, Restricted')],
        ['text:Configure rules', t('⚙️ Configure rules — thresholds, period, minimum orders, dispatch hours', '⚙️ नियम सेट करें — सीमा, अवधि, न्यूनतम ऑर्डर, भेजने के घंटे')],
        ['css:.lc-hcard', t('Dealer card — tap for measures', 'डीलर कार्ड — माप देखने के लिए दबाएँ')],
      ],
      what: t('Dealer compliance → "🩺 Account health".', 'Dealer compliance → "🩺 Account health"।'),
      why: t('To spot dealers who need help or action before customers are affected.', 'ग्राहकों पर असर से पहले मदद या कार्रवाई वाले डीलरों को पहचानने के लिए।'),
      can: t(['Measures: order cancellation rate, late shipment rate, customer complaints, return rate, refund issues, product quality complaints, policy violations, document expiry, fraud indicators', 'Configure thresholds for each level'], ['माप: ऑर्डर कैंसलेशन दर, देर से शिपमेंट दर, ग्राहक शिकायतें, रिटर्न दर, रिफ़ंड मामले, गुणवत्ता शिकायतें, पॉलिसी उल्लंघन, दस्तावेज़ समाप्ति, धोखाधड़ी संकेत', 'हर स्तर की सीमा सेट करें']),
      statuses: STATUS.health,
      important: t(['Health is guidance; suspension is always your decision (Violations / Dealer verification).'], ['हेल्थ मार्गदर्शन है; निलंबन हमेशा आपका फ़ैसला है (Violations / Dealer verification)।']),
    },
    {
      id: 'notifications', title: t('Notifications', 'सूचनाएँ'), shot: 'a_notices',
      callouts: [
        ['css:.lc-noticeinfo', t('Who gets what: Admin, Dealers, Customers', 'किसे क्या मिलता है: Admin, Dealers, Customers')],
        ['css:.lc-notices', t('Notification list — "Open" jumps to the policy or dealer', 'सूचना सूची — "Open" पॉलिसी या डीलर पर ले जाता है')],
      ],
      what: t('Legal & Compliance → "🔔 Notifications" (bell icon in the header).', 'Legal & Compliance → "🔔 Notifications" (हेडर में घंटी)।'),
      why: t('So nobody misses an approval, a review date, an expiring document or a policy change.', 'ताकि कोई मंज़ूरी, समीक्षा तारीख, समाप्त होता दस्तावेज़ या पॉलिसी बदलाव न छूटे।'),
      can: t(['Admin: "… is ready for publication", changes requested, review due, documents expiring, violations', 'Dealers: "Your Dealer Agreement has been updated. Please review and accept the new version.", policy issues, expiring documents', 'Customers: "Our Terms & Conditions have been updated…" — they accept before the next order'], ['Admin: "… is ready for publication", बदलाव माँगे, समीक्षा बाकी, समाप्त होते दस्तावेज़, उल्लंघन', 'डीलर: "Your Dealer Agreement has been updated. Please review and accept the new version.", पॉलिसी मामले, समाप्त होते दस्तावेज़', 'ग्राहक: "Our Terms & Conditions have been updated…" — अगले ऑर्डर से पहले स्वीकार करते हैं']),
      important: t(['Order and payment messages to customers are sent automatically by email/WhatsApp when those channels are configured.'], ['चैनल सेट होने पर ग्राहकों को ऑर्डर और भुगतान मैसेज ईमेल/WhatsApp से अपने-आप जाते हैं।']),
    },
    {
      id: 'reports', title: t('Reports', 'रिपोर्ट'), shot: 'a_tracking',
      callouts: [['text:Export CSV', t('⬇ Export CSV', '⬇ CSV एक्सपोर्ट')]],
      what: t('The reports and CSV exports available today.', 'आज उपलब्ध रिपोर्ट और CSV एक्सपोर्ट।'),
      why: t('To analyse delivery, pricing, marketing and legal acceptance outside the app (Excel/Sheets).', 'डिलीवरी, प्राइसिंग, मार्केटिंग और कानूनी स्वीकृति का ऐप के बाहर (Excel/Sheets) विश्लेषण करने के लिए।'),
      table: [
        [t('Delivery tracking', 'Delivery tracking'), t('Shipments, stages, times — ⬇ Export CSV', 'शिपमेंट, चरण, समय — ⬇ Export CSV')],
        [t('Pricing by PIN → All products', 'Pricing by PIN → All products'), t('Profit by zone — ⬇ Export CSV', 'ज़ोन अनुसार लाभ — ⬇ Export CSV')],
        [t('Customer messages → Subscribers', 'Customer messages → Subscribers'), t('Subscriber list — Export CSV (Owner)', 'सब्सक्राइबर सूची — Export CSV (Owner)')],
        [t('Legal & Compliance → Acceptance', 'Legal & Compliance → Acceptance'), t('Acceptance report — ⬇️ Export report (CSV)', 'स्वीकृति रिपोर्ट — ⬇️ Export report (CSV)')],
        [t('Dashboard, Profit & pricing, Marketing, AI insights', 'Dashboard, Profit & pricing, Marketing, AI insights'), t('On-screen reports and charts', 'स्क्रीन पर रिपोर्ट और चार्ट')],
      ],
      planned: t(['A single Reports page with order, payment, customer, sales and profit exports is a Planned Feature.'], ['ऑर्डर, भुगतान, ग्राहक, बिक्री और लाभ एक्सपोर्ट वाला एक Reports पेज Planned Feature है।']),
    },
    {
      id: 'audit', title: t('Audit Logs', 'ऑडिट लॉग'), shot: 'a_audit',
      callouts: [
        ['css:.lc-audit li', t('Who · what · when — e.g. "Store Owner — Created Dealer Agreement v2.0 — 06 Oct 2026, 10:25 am"', 'किसने · क्या · कब — जैसे "Store Owner — Created Dealer Agreement v2.0 — 06 Oct 2026, 10:25 am"')],
        ['css:.lc-card__head select', t('Filter by people and action', 'लोग और कार्रवाई से फ़िल्टर')],
      ],
      what: t('Legal & Compliance → "🧾 Audit trail" (legal actions) and the "Audit log" page (store admin actions).', 'Legal & Compliance → "🧾 Audit trail" (कानूनी कार्रवाई) और "Audit log" पेज (स्टोर एडमिन कार्रवाई)।'),
      why: t('Audit logs provide a history of important system and legal actions. They help the company understand who performed an action and when.', 'ऑडिट लॉग ज़रूरी सिस्टम और कानूनी कार्रवाइयों का इतिहास देते हैं। इनसे कंपनी समझती है कि किसने कौन सी कार्रवाई कब की।'),
      can: t(['Legal: created, edited, reviewed, approved, published policies; acceptances and signatures; dealer verification decisions; bank reveals; violations', 'Store: last 300 admin actions (who, action, item)'], ['कानूनी: पॉलिसी बनाना, बदलना, जाँचना, मंज़ूर करना, प्रकाशित करना; स्वीकृति और सिग्नेचर; डीलर सत्यापन फ़ैसले; बैंक नंबर देखना; उल्लंघन', 'स्टोर: पिछली 300 एडमिन कार्रवाई (किसने, क्या, कौन सा आइटम)']),
      important: t(['Audit entries cannot be edited or deleted from the app.'], ['ऑडिट प्रविष्टियाँ ऐप से बदली या डिलीट नहीं हो सकतीं।']),
    },
    {
      id: 'roles', title: t('User Roles & Permissions', 'यूज़र रोल और अनुमतियाँ'),
      what: t('Who can see and change what in the admin panel.', 'एडमिन पैनल में कौन क्या देख और बदल सकता है।'),
      why: t('Giving each person only the access they need protects money, customer data and legal records.', 'हर व्यक्ति को केवल ज़रूरी पहुँच देने से पैसा, ग्राहक डेटा और कानूनी रिकॉर्ड सुरक्षित रहते हैं।'),
      shot: 'a_admins',
      callouts: [
        ['css:table', t('Team: name, email, role (change here), two-step, last sign-in, status', 'टीम: नाम, ईमेल, रोल (यहाँ बदलें), दो-चरण, आखिरी साइन-इन, स्टेटस')],
        ['text:Add an admin', t('Add an admin: name, work email, role → one-time password', 'एडमिन जोड़ें: नाम, वर्क ईमेल, रोल → एक बार का पासवर्ड')],
        ['text:Permission matrix', t('Permission matrix (same map the server enforces)', 'अनुमति मैट्रिक्स (वही नक्शा जो सर्वर लागू करता है)')],
      ],
      matrix: {
        head: [t('Area', 'क्षेत्र'), ...ROLE_LIST.map((r) => t(ADMIN_ROLES[r].short, ROLE_HI[r].replace(' Admin', '')))],
        rows: [
          ...Object.entries(AREAS).map(([k, a]) => [t(a.label, AREA_HI[k] || a.label), ...ROLE_LIST.map((r) => mark(r, k))]),
          ...Object.keys(ACTIONS).map((k) => [t(`Action: ${ACTION_EN[k] || k}`, `कार्य: ${ACTION_HI[k] || k}`), ...ROLE_LIST.map((r) => (ACTIONS[k].includes(r) ? Y : N))]),
        ],
        note: t('✅ can change · 👁 can view only · — no access. "Action" rows are extra checks for money, legal and admin actions.', '✅ बदल सकते हैं · 👁 केवल देख सकते हैं · — पहुँच नहीं। "कार्य" पंक्तियाँ पैसे, लीगल और एडमिन कार्यों की अतिरिक्त जाँच हैं।'),
      },
      can: t(ROLE_LIST.map((r) => `${ADMIN_ROLES[r].label}: ${ADMIN_ROLES[r].desc}`), ROLE_LIST.map((r) => `${ROLE_HI[r]}: ${ADMIN_ROLES[r].desc}`)),
      steps: t(['Owner: open "👥 Admin users & roles".', 'Under "Add an admin" enter name, work email and role; tap "Add admin".', 'Give the one-time password privately; the person sets their own password at first sign-in.', 'To change a role, pick it in the Team table (that person is signed out). "Disable" removes access; "Reset password" gives a new one-time password.'], ['Owner: "👥 Admin users & roles" खोलें।', '"Add an admin" में नाम, वर्क ईमेल और रोल डालें; "Add admin" दबाएँ।', 'एक बार का पासवर्ड निजी रूप से दें; व्यक्ति पहली बार साइन इन पर अपना पासवर्ड बनाता है।', 'रोल बदलने के लिए Team टेबल में चुनें (वह व्यक्ति साइन आउट हो जाता है)। "Disable" पहुँच हटाता है; "Reset password" नया एक बार का पासवर्ड देता है।']),
      important: t(['The menu shows only the pages a role may open. Even if someone types a link, the server refuses pages and actions their role does not allow.', 'Read Only Admin can open every page except Admin users and Security but cannot change anything.', 'You cannot change your own role or disable yourself, and there is always at least one active Owner.'], ['मेन्यू में केवल वही पेज दिखते हैं जो रोल खोल सकता है। कोई लिंक टाइप करे तब भी सर्वर अनुमति न होने पर पेज और कार्य मना करता है।', 'Read Only Admin Admin users और Security छोड़कर हर पेज देख सकता है पर कुछ बदल नहीं सकता।', 'आप अपना रोल नहीं बदल सकते, खुद को डिसेबल नहीं कर सकते, और हमेशा कम से कम एक सक्रिय Owner रहता है।']),
    },
    {
      id: 'security', title: t('Security', 'सुरक्षा'), shot: 'a_security',
      callouts: [
        ['text:Security checklist', t('✅ Security checklist', '✅ सुरक्षा चेकलिस्ट')],
        ['text:Two-step login', t('📱 Two-step login (authenticator app + 10 backup codes)', '📱 दो-चरण लॉगिन (ऑथेंटिकेटर ऐप + 10 बैकअप कोड)')],
        ['text:Sign out everywhere', t('💻 Sign out everywhere', '💻 हर जगह से साइन आउट')],
        ['text:Recent admin sign-ins', t('👤 Recent admin sign-ins. A "🔒 Locked accounts" list with Unlock (Owner) appears here only when an account is locked', '👤 हाल के एडमिन साइन-इन। कोई अकाउंट लॉक होने पर ही यहाँ Unlock (Owner) के साथ "🔒 लॉक अकाउंट" सूची दिखती है')],
      ],
      what: t('"Security" page.', '"Security" पेज।'),
      why: t('To protect the store from account takeover and to see suspicious sign-in attempts.', 'स्टोर को अकाउंट पर कब्ज़े से बचाने और संदिग्ध साइन-इन कोशिशें देखने के लिए।'),
      steps: t(['Turn on Two-step login: scan the QR with an authenticator app, enter the 6-digit code, save the 10 backup codes safely.', 'Review "Recent admin sign-ins" and "Blocked & failed attempts".', 'Use "Sign out everywhere" if a device is lost.'], ['दो-चरण लॉगिन चालू करें: ऑथेंटिकेटर ऐप से QR स्कैन करें, 6 अंकों का कोड डालें, 10 बैकअप कोड सुरक्षित रखें।', '"Recent admin sign-ins" और "Blocked & failed attempts" देखें।', 'डिवाइस खोने पर "Sign out everywhere" उपयोग करें।']),
      important: t(['Backup codes are shown only once and each works once.'], ['बैकअप कोड केवल एक बार दिखते हैं और हर कोड एक बार चलता है।']),
    },
    {
      id: 'settings', title: t('System Settings', 'सिस्टम सेटिंग'), shot: 'a_settings',
      callouts: [
        ['text:UPI payment', t('💳 UPI payment: UPI ID, payee, QR, require UTR', '💳 UPI भुगतान: UPI ID, प्राप्तकर्ता, QR, UTR ज़रूरी')],
        ['text:Payment gateway', t('🔐 Payment gateway', '🔐 पेमेंट गेटवे')],
        ['text:Store & delivery', t('🏪 Store & delivery: contacts, delivery fee, free delivery above', '🏪 स्टोर और डिलीवरी: संपर्क, डिलीवरी फ़ीस, कितने से ऊपर फ़्री')],
      ],
      what: t('"Payment & Store" settings, plus Legal & Compliance → Settings (company details, health rules).', '"Payment & Store" सेटिंग, और Legal & Compliance → Settings (कंपनी विवरण, हेल्थ नियम)।'),
      why: t('These settings decide how customers pay, what delivery costs, which festival is featured and what company details appear in legal documents.', 'ये सेटिंग तय करती हैं कि ग्राहक कैसे भुगतान करें, डिलीवरी कितने की हो, कौन सा त्योहार दिखे और कानूनी दस्तावेज़ों में कंपनी विवरण क्या हो।'),
      can: t(['UPI, gateway, merchant & settlement notes', 'Current festival, store contacts, delivery fee and free-delivery limit', 'Selling abroad (international shipping, exchange rates)', 'Shipping zones', 'Guest checkout on/off', 'Company details used in documents (legal name, address, Grievance Officer)'], ['UPI, गेटवे, मर्चेंट और सेटलमेंट नोट', 'मौजूदा त्योहार, स्टोर संपर्क, डिलीवरी फ़ीस और फ़्री डिलीवरी सीमा', 'विदेश बिक्री (अंतरराष्ट्रीय शिपिंग, विनिमय दर)', 'शिपिंग ज़ोन', 'गेस्ट चेकआउट चालू/बंद', 'दस्तावेज़ों में उपयोग होने वाला कंपनी विवरण (कानूनी नाम, पता, शिकायत अधिकारी)']),
      important: t(['Only the Owner can save these settings.', 'Fill Company details before going live — the Consumer Protection (E-Commerce) Rules, 2020 require them.'], ['केवल Owner ये सेटिंग सेव कर सकता है।', 'लाइव होने से पहले कंपनी विवरण भरें — Consumer Protection (E-Commerce) Rules, 2020 में ये ज़रूरी हैं।']),
    },
    {
      id: 'problems', title: t('Common Problems', 'आम समस्याएँ'),
      table: [
        [t('"Please change the default password first."', '"Please change the default password first."'), t('Set your own password on the screen shown after sign-in.', 'साइन-इन के बाद दिखी स्क्रीन पर अपना पासवर्ड बनाएँ।')],
        [t('"You do not have permission for this action."', '"You do not have permission for this action."'), t('Your role is not allowed — ask the Owner (see Roles & Permissions).', 'आपके रोल को अनुमति नहीं — Owner से कहें (Roles & Permissions देखें)।')],
        [t('"✅ Approve dealer" is grey', '"✅ Approve dealer" धुंधला है'), t('Business/KYC incomplete, a required document not verified, agreement not signed, or delivery PIN codes not set.', 'बिज़नेस/KYC अधूरा, कोई ज़रूरी दस्तावेज़ सत्यापित नहीं, एग्रीमेंट साइन नहीं, या डिलीवरी PIN कोड सेट नहीं।')],
        [t('Paid order not going to any dealer', 'भुगतान हुआ ऑर्डर किसी डीलर को नहीं जा रहा'), t('No dealer covers the PIN/items. Use "Find dealer" or process the order yourself.', 'कोई डीलर उस PIN/आइटम को कवर नहीं करता। "Find dealer" उपयोग करें या खुद प्रोसेस करें।')],
        [t('Cannot publish a policy', 'पॉलिसी प्रकाशित नहीं हो रही'), t('It must pass internal review and have legal approval recorded first.', 'पहले आंतरिक समीक्षा और कानूनी मंज़ूरी दर्ज होनी चाहिए।')],
        [t('UPI payment cannot be found', 'UPI भुगतान नहीं मिल रहा'), t('Ask the customer for a screenshot; check the date range of the statement; reject only when sure.', 'ग्राहक से स्क्रीनशॉट माँगें; स्टेटमेंट की तारीख जाँचें; पक्का होने पर ही अस्वीकार करें।')],
        [t('Lost authenticator phone', 'ऑथेंटिकेटर फ़ोन खो गया'), t('Sign in with a backup code, then turn two-step login off and on again.', 'बैकअप कोड से साइन इन करें, फिर दो-चरण लॉगिन बंद करके दोबारा चालू करें।')],
        [t('Admin account locked', 'एडमिन अकाउंट लॉक'), t('Wait, or ask the Owner to "Unlock" in Security.', 'रुकें, या Owner से Security में "Unlock" करवाएँ।')],
      ],
    },
    {
      id: 'faq', title: t('Frequently Asked Questions', 'अक्सर पूछे जाने वाले प्रश्न'),
      faq: [
        [t('Can I edit a published policy?', 'क्या प्रकाशित पॉलिसी बदल सकते हैं?'), t('No. Create a new version; the old one stays as a legal record.', 'नहीं। नया वर्ज़न बनाएँ; पुराना कानूनी रिकॉर्ड के रूप में रहता है।')],
        [t('Who approves legal documents?', 'कानूनी दस्तावेज़ कौन मंज़ूर करता है?'), t('A qualified lawyer reviews them; the Owner records the lawyer\'s name in "Record legal approval".', 'योग्य वकील जाँचता है; Owner "Record legal approval" में वकील का नाम दर्ज करता है।')],
        [t('Does "Mark Refunded" send money?', 'क्या "Mark Refunded" पैसा भेजता है?'), t('No, it only records the refund. Send the money first.', 'नहीं, केवल दर्ज करता है। पहले पैसा भेजें।')],
        [t('How do dealers get orders automatically?', 'डीलरों को ऑर्डर अपने-आप कैसे मिलते हैं?'), t('With auto-routing on, a paid order goes to the best dealer who stocks all items and covers the PIN; it moves on if not accepted in time.', 'ऑटो-रूटिंग चालू होने पर भुगतान हुआ ऑर्डर उस डीलर को जाता है जिसके पास सारे आइटम हैं और जो PIN कवर करता है; समय पर स्वीकार न हो तो आगे जाता है।')],
        [t('Can dealers see our selling price or profit?', 'क्या डीलर हमारी कीमत या मुनाफ़ा देख सकते हैं?'), t('No. Only their dealer price.', 'नहीं। केवल अपना डीलर प्राइस।')],
        [t('How do I add another admin?', 'दूसरा एडमिन कैसे जोड़ें?'), t('Owner: Admin users & roles → Add an admin. Choose the smallest role that fits the job.', 'Owner: Admin users & roles → Add an admin। काम के लिए सबसे छोटा उपयुक्त रोल चुनें।')],
      ],
    },
  ],
};
