/** Customer User Manual — content (English + Hindi). See common.js for the format. */
import { t, STATUS } from './common.js';

export default {
  key: 'customer',
  file: 'Customer_User_Manual',
  title: t('Customer User Manual', 'ग्राहक उपयोगकर्ता मैनुअल'),
  subtitle: t('Complete Guide to Using Our Marketplace', 'हमारे मार्केटप्लेस का उपयोग करने की पूरी गाइड'),
  audience: t('For Customers', 'ग्राहकों के लिए'),
  help: 'customer',
  sections: [
    {
      id: 'intro', title: t('Introduction', 'परिचय'), shot: 'c_home',
      callouts: [
        ['css:.zh__search', t('Search box — type or tap 🎤 to search by voice', 'सर्च बॉक्स — लिखें या 🎤 दबाकर बोलकर खोजें')],
        ['css:.zh__acct', t('Hello, sign in / Account & Lists', 'Hello, sign in / Account & Lists')],
        ['css:.zh__orders', t('Returns & Orders', 'Returns & Orders (रिटर्न और ऑर्डर)')],
        ['css:.zh__cart', t('Cart', 'कार्ट')],
        ['css:.zh__nav', t('Departments, Offers, Track Order, Customer Service', 'विभाग, ऑफ़र, Track Order, Customer Service')],
        ['text:Help', t('💬 Help — chat with us any time', '💬 Help — कभी भी चैट करें')],
      ],
      what: t('Utsav Ghar is an online store for festival décor, pooja items, home décor, crockery and kitchenware. This manual explains every page you use as a customer — from creating an account to getting help after delivery.',
        'Utsav Ghar त्योहार की सजावट, पूजा सामग्री, होम डेकोर, क्रॉकरी और किचन के सामान का ऑनलाइन स्टोर है। यह मैनुअल ग्राहक के रूप में आपके हर पेज को समझाता है — अकाउंट बनाने से लेकर डिलीवरी के बाद मदद तक।'),
      why: t('So you can shop with confidence: you know what each button does, what each status means and whom to contact.',
        'ताकि आप भरोसे से खरीदारी करें: आपको पता हो कि हर बटन क्या करता है, हर स्टेटस का मतलब क्या है और किससे संपर्क करें।'),
      can: t(['Browse and search products (also by voice in Hindi/English)', 'Create an account and save addresses', 'Order and pay by UPI (cards/net banking when the store enables them)', 'Track orders, ask for help, review products', 'Read and download our policies'],
        ['प्रोडक्ट देखें और खोजें (हिंदी/अंग्रेज़ी में बोलकर भी)', 'अकाउंट बनाएँ और पते सेव करें', 'ऑर्डर करें और UPI से भुगतान करें (स्टोर चालू करे तो कार्ड/नेट बैंकिंग)', 'ऑर्डर ट्रैक करें, मदद माँगें, रिव्यू लिखें', 'हमारी पॉलिसी पढ़ें और डाउनलोड करें']),
      flow: 'customer_order',
      important: t(['All orders are prepaid. Cash on delivery is not available right now.', 'You need an account to place an order.', 'Screens in this manual are real screens from the website with demo data. The phone app shows the same screens.'],
        ['सभी ऑर्डर प्रीपेड हैं। अभी कैश ऑन डिलीवरी उपलब्ध नहीं है।', 'ऑर्डर करने के लिए अकाउंट ज़रूरी है।', 'इस मैनुअल की स्क्रीन वेबसाइट की असली स्क्रीन हैं (डेमो डेटा)। फ़ोन ऐप में भी यही स्क्रीन दिखती हैं।']),
    },
    {
      id: 'register', title: t('Customer Registration', 'ग्राहक रजिस्ट्रेशन'), shot: 'c_register',
      callouts: [
        ['label:Full name', t('Your details: name, mobile, email, date of birth (optional)', 'आपकी जानकारी: नाम, मोबाइल, ईमेल, जन्मतिथि (वैकल्पिक)')],
        ['label:Password', t('Password with strength meter', 'पासवर्ड और उसकी मज़बूती का मीटर')],
        ['label:House no', t('Address — saved as your default delivery address', 'पता — आपका डिफ़ॉल्ट डिलीवरी पता बन जाता है')],
      ],
      shot2: 'c_register_b',
      callouts2: [
        ['css:.lg-cust', t('Customer Terms & Agreement — Simple explanation / Full legal terms', 'Customer Terms & Agreement — आसान भाषा / पूरी कानूनी शर्तें')],
        ['text:Before you create your account', t('The 4 required boxes', '4 ज़रूरी बॉक्स')],
        ['text:Download Customer Agreement PDF', t('Download the agreement before you sign up', 'साइन अप से पहले एग्रीमेंट डाउनलोड करें')],
        ['text:Accept & Create Account', t('Accept & Create Account — active only when everything is filled', 'Accept & Create Account — सब भरने पर ही चालू होता है')],
      ],
      what: t('The page where you create your Utsav Ghar account ("Create your account").', 'वह पेज जहाँ आप अपना Utsav Ghar अकाउंट बनाते हैं ("Create your account")।'),
      why: t('An account lets us securely identify you, manage your orders, save your addresses, keep a record of the terms you accepted and give you support.',
        'अकाउंट से हम आपकी सुरक्षित पहचान कर पाते हैं, आपके ऑर्डर संभालते हैं, पते सेव करते हैं, आपकी स्वीकार की गई शर्तों का रिकॉर्ड रखते हैं और आपकी मदद कर पाते हैं।'),
      can: t(['Enter your details and address', 'Read the Customer Agreement and other policies', 'Download the agreement as PDF', 'Accept the 4 required boxes and create the account', 'Optionally sign up for festival deals on WhatsApp/email'],
        ['अपनी जानकारी और पता भरें', 'Customer Agreement और बाकी पॉलिसी पढ़ें', 'एग्रीमेंट PDF में डाउनलोड करें', '4 ज़रूरी बॉक्स टिक करके अकाउंट बनाएँ', 'चाहें तो WhatsApp/ईमेल पर त्योहार ऑफ़र के लिए साइन अप करें']),
      steps: t([
        'Tap "Hello, sign in" → "Create an account" (or open /register).',
        'Section 1 "Your details": enter Full name, Mobile number (10 digits, starts with 6–9), Email, and a Password. Type the password again in "Confirm password".',
        'Section 2 "Address": choose Country, enter House no./street/area, PIN code (6 digits), City and State. Typing the PIN fills the State automatically.',
        'Section 3 "Read & accept": read the agreement (switch between "Simple explanation" and "Full legal terms"). Use "⬇️ Download Customer Agreement PDF" to keep a copy.',
        'Tap "Send code". A 6-digit code arrives by WhatsApp/SMS on your mobile and by email. Type it in "Mobile & email code".',
        'Tick all four boxes under "Before you create your account".',
        'Tap "Accept & Create Account". If it is grey, read the "Still needed:" line below it.'],
      [
        '"Hello, sign in" → "Create an account" दबाएँ (या /register खोलें)।',
        'सेक्शन 1 "Your details": पूरा नाम, मोबाइल नंबर (10 अंक, 6–9 से शुरू), ईमेल और पासवर्ड भरें। "Confirm password" में पासवर्ड दोबारा लिखें।',
        'सेक्शन 2 "Address": देश चुनें, मकान नं./गली/इलाका, PIN कोड (6 अंक), शहर और राज्य भरें। PIN लिखते ही राज्य अपने-आप भर जाता है।',
        'सेक्शन 3 "Read & accept": एग्रीमेंट पढ़ें ("Simple explanation" और "Full legal terms" के बीच बदलें)। कॉपी रखने के लिए "⬇️ Download Customer Agreement PDF" दबाएँ।',
        '"Send code" दबाएँ। 6 अंकों का कोड आपके मोबाइल पर WhatsApp/SMS से और ईमेल पर आता है। उसे "Mobile & email code" में लिखें।',
        '"Before you create your account" के नीचे चारों बॉक्स टिक करें।',
        '"Accept & Create Account" दबाएँ। अगर बटन धुंधला है, तो नीचे "Still needed:" वाली लाइन पढ़ें।']),
      after: t('After the code is checked, your account is created and you are signed in. You go to "My account". A record of each document you accepted (version, date, time, reference number) is saved in Legal & Agreements.',
        'कोड जाँचने के बाद अकाउंट बनता है और आप साइन इन हो जाते हैं। आप "My account" पर पहुँचते हैं। आपने जो-जो दस्तावेज़ स्वीकार किए (वर्ज़न, तारीख, समय, रेफ़रेंस नंबर) उनका रिकॉर्ड Legal & Agreements में सेव होता है।'),
      important: t(['Fields marked * are required.', 'Password: at least 8 characters; do not use your name, email or common passwords like "password123".', 'One account per email address and per mobile number.', 'The code is valid for 10 minutes. "Resend code" works after 30 seconds (up to 5 codes an hour). After 5 wrong codes, ask for a new one.', 'Date of birth is optional (for birthday offers) and is not shared.'],
        ['* वाले फ़ील्ड ज़रूरी हैं।', 'पासवर्ड: कम से कम 8 अक्षर; अपना नाम, ईमेल या "password123" जैसे आम पासवर्ड न रखें।', 'एक ईमेल और एक मोबाइल नंबर से एक ही अकाउंट।', 'कोड 10 मिनट तक चलता है। "Resend code" 30 सेकंड बाद (एक घंटे में 5 कोड तक)। 5 गलत कोड के बाद नया कोड माँगें।', 'जन्मतिथि वैकल्पिक है (बर्थडे ऑफ़र के लिए) और किसी से साझा नहीं होती।']),
      mistakes: t(['Passwords in both boxes do not match', 'Mobile number with +91 or spaces in a wrong format', 'Not ticking all four boxes', 'Using an email that already has an account — sign in instead', 'Typing the code after 10 minutes — tap "Resend code"'],
        ['दोनों बॉक्स के पासवर्ड अलग होना', 'मोबाइल नंबर गलत तरीके से (+91 या खाली जगह के साथ) लिखना', 'चारों बॉक्स टिक न करना', 'ऐसा ईमेल जिससे पहले से अकाउंट है — उसकी जगह साइन इन करें', '10 मिनट बाद कोड लिखना — "Resend code" दबाएँ']),
    },
    {
      id: 'login', title: t('Customer Login', 'ग्राहक लॉगिन'), shot: 'c_login',
      callouts: [
        ['label:Email', t('Email', 'ईमेल')],
        ['label:Password', t('Password', 'पासवर्ड')],
        ['css:form button[type=submit]', t('Sign in', 'Sign in (साइन इन)')],
        ['text:Forgot password', t('Forgot password? — reset with a code', 'Forgot password? — कोड से रीसेट')],
        ['text:Create an account', t('New here? Create an account', 'नए हैं? अकाउंट बनाएँ')],
      ],
      shot2: 'c_forgot',
      callouts2: [
        ['label:Email', t('Your account email', 'आपके अकाउंट का ईमेल')],
        ['css:.otp__send', t('Send code (to your email and mobile)', 'Send code (ईमेल और मोबाइल पर)')],
        ['label:New password', t('New password + confirm', 'नया पासवर्ड + दोबारा')],
        ['text:Set new password', t('Set new password', 'नया पासवर्ड सेट करें')],
      ],
      what: t('The "Welcome back" page where you sign in with your email and password.', '"Welcome back" पेज जहाँ आप ईमेल और पासवर्ड से साइन इन करते हैं।'),
      why: t('Signing in proves it is you, so we can show your orders, wishlist and addresses and let you place orders.', 'साइन इन से पता चलता है कि आप ही हैं, ताकि हम आपके ऑर्डर, विशलिस्ट और पते दिखा सकें और आप ऑर्डर कर सकें।'),
      can: t(['Sign in', 'Reset a forgotten password with a code', 'Go to registration'], ['साइन इन करें', 'भूला पासवर्ड कोड से रीसेट करें', 'रजिस्ट्रेशन पर जाएँ']),
      steps: t(['Tap "Hello, sign in" in the header.', 'Enter your Email and Password.', 'Tap "Sign in".', 'Forgot it? Tap "Forgot password?", enter your email, tap "Send code", type the 6-digit code from your email or mobile, choose a new password and tap "Set new password".'], ['हेडर में "Hello, sign in" दबाएँ।', 'ईमेल और पासवर्ड डालें।', '"Sign in" दबाएँ।', 'भूल गए? "Forgot password?" दबाएँ, ईमेल लिखें, "Send code" दबाएँ, ईमेल या मोबाइल पर आया 6 अंकों का कोड लिखें, नया पासवर्ड चुनें और "Set new password" दबाएँ।']),
      after: t('You return to the page you were on (for example checkout). You stay signed in on this device for 30 days unless you sign out.', 'आप उसी पेज पर लौटते हैं जहाँ थे (जैसे चेकआउट)। साइन आउट न करें तो इस डिवाइस पर 30 दिन तक साइन इन रहते हैं।'),
      important: t(['After 5 wrong attempts sign-in is paused for 15 minutes (longer after more attempts). This protects your account.', 'After a password reset you are signed out on every device and we email you. If you did not ask for it, contact us.', 'For your safety the reset page always says "If an account exists…" — it never tells anyone whether an email is registered.'], ['5 बार गलत पासवर्ड पर 15 मिनट के लिए साइन-इन रुक जाता है (ज़्यादा बार पर और लंबा)। यह आपके अकाउंट की सुरक्षा के लिए है।', 'पासवर्ड रीसेट के बाद आप हर डिवाइस से साइन आउट हो जाते हैं और हम ईमेल भेजते हैं। आपने नहीं माँगा था तो हमसे संपर्क करें।', 'सुरक्षा के लिए रीसेट पेज हमेशा "If an account exists…" कहता है — यह किसी को नहीं बताता कि ईमेल रजिस्टर्ड है या नहीं।']),
      mistakes: t(['Typing the mobile number instead of the email', 'Caps Lock on while typing the password'], ['ईमेल की जगह मोबाइल नंबर लिखना', 'Caps Lock चालू रहते पासवर्ड लिखना']),
    },
    {
      id: 'dashboard', title: t('Customer Dashboard (My account)', 'ग्राहक डैशबोर्ड (My account)'), shot: 'c_account',
      callouts: [
        ['css:.account__nav', t('Account menu: Profile, Orders, Wishlist, Addresses, Payments, Offers, Help requests, Legal, Security', 'अकाउंट मेन्यू: Profile, Orders, Wishlist, Addresses, Payments, Offers, Help requests, Legal, Security')],
        ['text:Deals & festival alerts', t('🔔 Deals & festival alerts', '🔔 Deals & festival alerts (ऑफ़र अलर्ट)')],
        ['text:Sign out', t('Sign out', 'साइन आउट')],
      ],
      what: t('"My account" — your personal area after signing in. Open it from "Account & Lists" in the header.', '"My account" — साइन इन के बाद आपका निजी हिस्सा। हेडर में "Account & Lists" से खोलें।'),
      why: t('Everything about you is in one place: orders, payments, addresses, saved items, help requests and legal records.', 'आपसे जुड़ी हर चीज़ एक जगह: ऑर्डर, भुगतान, पते, सेव किए आइटम, मदद रिक्वेस्ट और कानूनी रिकॉर्ड।'),
      can: t(['My Profile — name and mobile', 'My Orders — track and view orders', 'Wishlist — items you saved with ❤️', 'Addresses — add or delete delivery addresses', 'Payment History — all payments', 'Offers — current coupons', 'Help requests — your support tickets', 'Legal Documents — terms you accepted', 'Login & Security — password, devices, your data'],
        ['My Profile — नाम और मोबाइल', 'My Orders — ऑर्डर देखें और ट्रैक करें', 'Wishlist — ❤️ से सेव किए आइटम', 'Addresses — डिलीवरी पते जोड़ें या हटाएँ', 'Payment History — सारे भुगतान', 'Offers — मौजूदा कूपन', 'Help requests — आपकी सपोर्ट टिकट', 'Legal Documents — स्वीकार की गई शर्तें', 'Login & Security — पासवर्ड, डिवाइस, आपका डेटा']),
      steps: t(['Sign in.', 'Tap "Account & Lists".', 'Choose a tab on the left (on phones: at the top).'], ['साइन इन करें।', '"Account & Lists" दबाएँ।', 'बाईं ओर (फ़ोन पर ऊपर) कोई टैब चुनें।']),
      important: t(['If we updated our terms, a "We have updated our terms" box appears. Accept it to keep ordering.'], ['अगर हमने शर्तें बदली हैं तो "We have updated our terms" बॉक्स दिखता है। ऑर्डर जारी रखने के लिए उसे स्वीकार करें।']),
    },
    {
      id: 'profile', title: t('Customer Profile', 'ग्राहक प्रोफ़ाइल'), shot: 'c_profile',
      callouts: [
        ['label:Name', t('Name', 'नाम')],
        ['label:Mobile', t('Mobile (10 digits)', 'मोबाइल (10 अंक)')],
        ['label:Email', t('Email — your sign-in; change it with "Change email"', 'ईमेल — आपका साइन-इन; "Change email" से बदलें')],
        ['text:Save changes', t('Save changes', 'बदलाव सेव करें')],
        ['text:Change email', t('Change email (password + code to the new email)', 'Change email (पासवर्ड + नए ईमेल पर कोड)')],
      ],
      what: t('"My Profile" tab in My account.', 'My account का "My Profile" टैब।'),
      why: t('Correct name, mobile and email help couriers and our team reach you about your orders.', 'सही नाम, मोबाइल और ईमेल से कूरियर और हमारी टीम ऑर्डर के बारे में आप तक पहुँच पाती है।'),
      can: t(['Change your name', 'Change your mobile number', 'Change your email (verified with a code)'], ['नाम बदलें', 'मोबाइल नंबर बदलें', 'ईमेल बदलें (कोड से पक्का)']),
      steps: t(['Open My account → My Profile.', 'Edit Name or Mobile and tap "Save changes".', 'To change email: tap "Change email", type the new email and your current password, tap "Send code", enter the code from the new inbox and tap "Confirm new email".'], ['My account → My Profile खोलें।', 'नाम या मोबाइल बदलें और "Save changes" दबाएँ।', 'ईमेल बदलने के लिए: "Change email" दबाएँ, नया ईमेल और मौजूदा पासवर्ड लिखें, "Send code" दबाएँ, नए इनबॉक्स में आया कोड डालें और "Confirm new email" दबाएँ।']),
      after: t('You see "Profile saved." New orders use the new details. After an email change you sign in with the new email; your old email gets a notice.', '"Profile saved." दिखता है। नए ऑर्डर में नई जानकारी उपयोग होती है। ईमेल बदलने के बाद नए ईमेल से साइन इन करें; पुराने ईमेल पर सूचना जाती है।'),
      important: t(['A mobile number or email can belong to only one account.'], ['एक मोबाइल नंबर या ईमेल केवल एक अकाउंट का हो सकता है।']),
      mistakes: t(['Entering a number that is not a valid Indian mobile number', 'Using a mobile number that another account already has'], ['ऐसा नंबर डालना जो सही भारतीय मोबाइल नंबर न हो', 'ऐसा मोबाइल नंबर जो किसी दूसरे अकाउंट में है']),
    },
    {
      id: 'search', title: t('Product Search', 'प्रोडक्ट सर्च'), shot: 'c_search',
      callouts: [
        ['ph:Search diyas', t('Type what you want (when the box is empty, tap 🎤 to speak — "Bolkar kharidiye")', 'जो चाहिए वह लिखें (बॉक्स खाली हो तो 🎤 दबाकर बोलें — "बोलकर खरीदिए")')],
        ['css:.search__panel', t('Suggestions: words, categories and products with prices', 'सुझाव: शब्द, कैटेगरी और कीमत के साथ प्रोडक्ट')],
        ['css:.zh__search select', t('Choose a department ("All")', 'विभाग चुनें ("All")')],
      ],
      shot2: 'c_shop',
      callouts2: [
        ['css:.filters, .shop__filters, aside', t('Filters: category, price, material, rating, discount, in stock', 'फ़िल्टर: कैटेगरी, कीमत, मटेरियल, रेटिंग, छूट, स्टॉक में')],
        ['text:Sort by', t('Sort by: price, rating, newest, best sellers, discount', 'Sort by: कीमत, रेटिंग, नए, बेस्ट सेलर, छूट')],
      ],
      what: t('The search box at the top of every page, the voice shopper and the shop pages with filters.', 'हर पेज के ऊपर सर्च बॉक्स, वॉइस शॉपिंग और फ़िल्टर वाले शॉप पेज।'),
      why: t('To find the right product quickly among many items.', 'बहुत सारे सामान में से सही प्रोडक्ट जल्दी ढूँढने के लिए।'),
      can: t(['Search by words (spelling mistakes are corrected)', 'Pick a category in the "All" dropdown', 'Use "Recent searches" and "Popular right now"', 'Speak in Hindi, Hinglish or English, e.g. "2 brass diya cart mein daal do"', 'Filter and sort results'],
        ['शब्दों से खोजें (गलत स्पेलिंग ठीक हो जाती है)', '"All" ड्रॉपडाउन में कैटेगरी चुनें', '"Recent searches" और "Popular right now" का उपयोग करें', 'हिंदी, हिंग्लिश या अंग्रेज़ी में बोलें, जैसे "2 brass diya cart mein daal do"', 'नतीजों को फ़िल्टर और सॉर्ट करें']),
      steps: t(['Tap the search box and type, e.g. "diya".', 'Choose a suggestion or press Enter / "See all results".', 'Use filters on the left (on phones: "Filters").', 'Change "Sort by" if needed.', 'For voice: tap 🎤, allow the microphone, and speak.'],
        ['सर्च बॉक्स दबाकर लिखें, जैसे "diya"।', 'कोई सुझाव चुनें या Enter / "See all results" दबाएँ।', 'बाईं ओर के फ़िल्टर लगाएँ (फ़ोन पर "Filters")।', 'ज़रूरत हो तो "Sort by" बदलें।', 'आवाज़ के लिए: 🎤 दबाएँ, माइक्रोफ़ोन की अनुमति दें और बोलें।']),
      mistakes: t(['Too many filters together → no results. Tap "Clear all filters".', 'Microphone permission blocked in the browser'], ['एक साथ बहुत सारे फ़िल्टर → कोई नतीजा नहीं। "Clear all filters" दबाएँ।', 'ब्राउज़र में माइक्रोफ़ोन की अनुमति बंद होना']),
    },
    {
      id: 'product', title: t('Product Details', 'प्रोडक्ट विवरण'), shot: 'c_product',
      callouts: [
        ['css:.pdp__gal, .gallery, .pdp__media', t('Photos — tap to change', 'फ़ोटो — बदलने के लिए दबाएँ')],
        ['css:.buybox .price, .pdp__price, .buybox__price', t('Price, MRP and % off ("Inclusive of all taxes")', 'कीमत, MRP और % छूट ("सभी टैक्स शामिल")')],
        ['text:Add to Cart', t('Add to Cart', 'कार्ट में डालें')],
        ['text:Buy Now', t('Buy Now — straight to checkout', 'Buy Now — सीधे चेकआउट')],
        ['css:.buybox [aria-label*="ishlist" i], .pdp__wish', t('❤️ Wishlist', '❤️ विशलिस्ट')],
      ],
      what: t('The page of one product: photos, price, offer, stock, delivery estimate, details, specifications and reviews.', 'एक प्रोडक्ट का पेज: फ़ोटो, कीमत, ऑफ़र, स्टॉक, डिलीवरी अनुमान, विवरण, स्पेसिफ़िकेशन और रिव्यू।'),
      why: t('To check that the product is right for you before buying.', 'खरीदने से पहले यह जाँचने के लिए कि प्रोडक्ट आपके लिए सही है।'),
      can: t(['See photos, price and discount', 'Check stock ("Only N left")', 'Choose quantity (up to 10)', 'Add to cart, buy now or save to wishlist', 'Share the link', 'Compare with similar items and see "Frequently bought together"', 'Read reviews and write one after buying'],
        ['फ़ोटो, कीमत और छूट देखें', 'स्टॉक देखें ("Only N left")', 'मात्रा चुनें (10 तक)', 'कार्ट में डालें, अभी खरीदें या विशलिस्ट में सेव करें', 'लिंक शेयर करें', 'मिलते-जुलते सामान से तुलना करें और "Frequently bought together" देखें', 'रिव्यू पढ़ें और खरीदने के बाद लिखें']),
      steps: t(['Open a product from search or a category.', 'Check photos, price and "Product details".', 'Choose quantity.', 'Tap "Add to Cart" or "Buy Now".'], ['सर्च या कैटेगरी से प्रोडक्ट खोलें।', 'फ़ोटो, कीमत और "Product details" देखें।', 'मात्रा चुनें।', '"Add to Cart" या "Buy Now" दबाएँ।']),
      important: t(['The delivery date shown is an estimate. The exact charge and timing depend on your PIN code at checkout.', 'Out-of-stock products cannot be added to the cart.'], ['दिखाई गई डिलीवरी तारीख अनुमान है। सही चार्ज और समय चेकआउट पर आपके PIN कोड से तय होते हैं।', 'स्टॉक खत्म वाले प्रोडक्ट कार्ट में नहीं जुड़ते।']),
      planned: t(['A PIN-code delivery checker on the product page and product Q&A are Planned Features. Ask product questions in chat or Help Center.'], ['प्रोडक्ट पेज पर PIN कोड डिलीवरी चेक और प्रोडक्ट Q&A Planned Features हैं। प्रोडक्ट के सवाल चैट या Help Center में पूछें।']),
    },
    {
      id: 'cart', title: t('Add to Cart', 'कार्ट में डालें'), shot: 'c_cart',
      callouts: [
        ['css:.qty, .line__qty', t('Change quantity / remove / Save for later', 'मात्रा बदलें / हटाएँ / बाद के लिए सेव करें')],
        ['text:Order Summary', t('Order Summary: subtotal, savings, delivery, total', 'ऑर्डर सारांश: सबटोटल, बचत, डिलीवरी, कुल')],
        ['ph:e.g. WELCOME10', t('Coupon code', 'कूपन कोड')],
        ['text:Proceed to Checkout', t('Proceed to Checkout', 'चेकआउट पर जाएँ')],
      ],
      what: t('The Cart page lists what you are about to buy and calculates the total.', 'Cart पेज में वह सामान दिखता है जो आप खरीदने वाले हैं और कुल रकम गिनी जाती है।'),
      why: t('To review items, apply offers and see the final price before paying.', 'भुगतान से पहले सामान देखने, ऑफ़र लगाने और अंतिम कीमत जानने के लिए।'),
      can: t(['Change quantity or remove items', '"Save for later" (kept in this browser)', 'See "Buy More, Save More" progress (e.g. buy 2 → 10% off)', 'Apply a coupon such as WELCOME10 (first order)', 'See delivery charge and "Add ₹X more for free delivery"'],
        ['मात्रा बदलें या सामान हटाएँ', '"Save for later" (इसी ब्राउज़र में रहता है)', '"Buy More, Save More" की प्रगति देखें (जैसे 2 खरीदें → 10% छूट)', 'WELCOME10 जैसा कूपन लगाएँ (पहला ऑर्डर)', 'डिलीवरी चार्ज और "Add ₹X more for free delivery" देखें']),
      steps: t(['Tap "Cart" in the header.', 'Check items and quantities.', 'Enter a coupon and tap "Apply" (optional).', 'Tap "Proceed to Checkout →".'], ['हेडर में "Cart" दबाएँ।', 'सामान और मात्रा जाँचें।', 'कूपन डालकर "Apply" दबाएँ (वैकल्पिक)।', '"Proceed to Checkout →" दबाएँ।']),
      important: t(['Automatic offers and coupons are not added together — you automatically get whichever saves you more.'], ['ऑटोमैटिक ऑफ़र और कूपन एक साथ नहीं जुड़ते — जिससे ज़्यादा बचत हो, वही अपने-आप मिलता है।']),
      mistakes: t(['Expecting a coupon on top of "Buy More, Save More"', 'Typing the coupon code with spaces'], ['"Buy More, Save More" के ऊपर कूपन की उम्मीद करना', 'कूपन कोड खाली जगह के साथ लिखना']),
    },
    {
      id: 'checkout', title: t('Checkout', 'चेकआउट'), shot: 'c_checkout',
      callouts: [
        ['css:.co-steps, .steps, .checkout__steps', t('3 steps: Your details → Order summary → Payment', '3 चरण: आपकी जानकारी → ऑर्डर सारांश → भुगतान')],
        ['label:Full name', t('Name and mobile number', 'नाम और मोबाइल नंबर')],
        ['label:PIN code', t('PIN code — decides the delivery charge', 'PIN कोड — डिलीवरी चार्ज तय करता है')],
        ['text:Continue to Order Summary', t('Continue to Order Summary', 'ऑर्डर सारांश पर जाएँ')],
      ],
      what: t('Where you confirm who receives the order and where, then place the order.', 'जहाँ आप तय करते हैं कि ऑर्डर कौन और कहाँ लेगा, फिर ऑर्डर करते हैं।'),
      why: t('We need the correct delivery details and your confirmation of the final amount before reserving your items.', 'सामान रिज़र्व करने से पहले हमें सही डिलीवरी जानकारी और अंतिम रकम पर आपकी पुष्टि चाहिए।'),
      can: t(['Pick a saved address or type a new one', 'Choose message preferences', 'Save the address to your account', 'Review the order and place it'], ['सेव किया पता चुनें या नया लिखें', 'मैसेज की पसंद चुनें', 'पता अकाउंट में सेव करें', 'ऑर्डर देखें और ऑर्डर करें']),
      steps: t(['From the cart tap "Proceed to Checkout". Sign in if asked ("Your cart is saved").', 'Step 1: fill Full name, Mobile number, Address, PIN code, City, State (or tap a saved address).', 'Tap "Continue to Order Summary →".', 'Step 2: check "Delivering to", items and total. Tap "Place Order & Pay ₹X".', 'Step 3: pay (see Payment).'],
        ['कार्ट से "Proceed to Checkout" दबाएँ। कहे तो साइन इन करें ("Your cart is saved")।', 'चरण 1: पूरा नाम, मोबाइल, पता, PIN, शहर, राज्य भरें (या सेव किया पता दबाएँ)।', '"Continue to Order Summary →" दबाएँ।', 'चरण 2: "Delivering to", सामान और कुल जाँचें। "Place Order & Pay ₹X" दबाएँ।', 'चरण 3: भुगतान करें (Payment देखें)।']),
      after: t('Your order is reserved with an order number (e.g. DIWALI10245) and the payment panel opens.', 'आपका ऑर्डर एक ऑर्डर नंबर (जैसे DIWALI10245) के साथ रिज़र्व होता है और भुगतान पैनल खुलता है।'),
      important: t(['If prices, offers or delivery charges changed, you see the updated total before paying.', 'If our terms changed, you must accept them before the order can be placed.'], ['अगर कीमत, ऑफ़र या डिलीवरी चार्ज बदले तो भुगतान से पहले नया कुल दिखता है।', 'अगर हमारी शर्तें बदलीं तो ऑर्डर से पहले उन्हें स्वीकार करना होगा।']),
      mistakes: t(['Wrong PIN code — causes wrong charges and delays', 'Phone number that will not be reachable on the delivery day'], ['गलत PIN कोड — गलत चार्ज और देरी', 'ऐसा फ़ोन नंबर जो डिलीवरी के दिन न लगे']),
    },
    {
      id: 'addresses', title: t('Address Management', 'पता प्रबंधन'), shot: 'c_addresses',
      callouts: [
        ['text:Cancel', t('+ Add address (shows "Cancel" while the form is open)', '+ Add address (फ़ॉर्म खुला हो तो "Cancel" दिखता है)')],
        ['label:Label', t('Label (Home, Office…)', 'लेबल (Home, Office…)')],
        ['text:Save address', t('Save address', 'पता सेव करें')],
      ],
      what: t('"Addresses" tab in My account.', 'My account का "Addresses" टैब।'),
      why: t('Saved addresses make checkout faster and avoid typing mistakes.', 'सेव किए पतों से चेकआउट तेज़ होता है और गलतियाँ नहीं होतीं।'),
      can: t(['Add up to 10 addresses', 'Edit an address', 'Set any address as "Default"', 'Delete an address (🗑)'], ['10 तक पते जोड़ें', 'पता बदलें (Edit)', 'किसी भी पते को "Default" बनाएँ', 'पता हटाएँ (🗑)']),
      steps: t(['My account → Addresses → "+ Add address".', 'Fill Label, Name, Mobile, Address, Landmark (optional), City, State, PIN code. Tick "Make this my default address" if you like.', 'Tap "Save address".', 'To change one later: tap "Edit" on it, correct it, "Save changes". To make another address the default: "Set as default".'], ['My account → Addresses → "+ Add address"।', 'लेबल, नाम, मोबाइल, पता, लैंडमार्क (वैकल्पिक), शहर, राज्य, PIN भरें। चाहें तो "Make this my default address" टिक करें।', '"Save address" दबाएँ।', 'बाद में बदलने के लिए: पते पर "Edit" दबाएँ, ठीक करें, "Save changes"। दूसरे पते को डिफ़ॉल्ट बनाने के लिए: "Set as default"।']),
      important: t(['The first address becomes the default. If you delete the default address, your newest other address becomes the default.', 'Addresses here are for India (6-digit PIN).'], ['पहला पता डिफ़ॉल्ट बनता है। डिफ़ॉल्ट पता हटाने पर आपका सबसे नया दूसरा पता डिफ़ॉल्ट बन जाता है।', 'यहाँ के पते भारत के लिए हैं (6 अंकों का PIN)।']),
    },
    {
      id: 'payment', title: t('Payment', 'भुगतान'), shot: 'c_payment',
      callouts: [
        ['css:.paym', t('Choose how to pay: UPI, card, net banking, wallets, EMI', 'भुगतान का तरीका चुनें: UPI, कार्ड, नेट बैंकिंग, वॉलेट, EMI')],
        ['css:.pay__qr', t('📱 Scan QR & Pay', '📱 QR स्कैन करके भुगतान')],
        ['text:Copy UPI ID', t('Or pay to our UPI ID', 'या हमारी UPI ID पर भुगतान करें')],
        ['label:UPI transaction', t('UTR / reference number (12 digits)', 'UTR / रेफ़रेंस नंबर (12 अंक)')],
        ['text:I HAVE PAID', t('✅ I HAVE PAID', '✅ I HAVE PAID (मैंने भुगतान कर दिया)')],
      ],
      what: t('The "💳 Choose how to pay" panel after you place the order.', 'ऑर्डर के बाद खुलने वाला "💳 Choose how to pay" पैनल।'),
      why: t('To pay securely. For UPI, the UTR number lets our team match your payment with the bank statement.', 'सुरक्षित भुगतान के लिए। UPI में UTR नंबर से टीम आपका भुगतान बैंक स्टेटमेंट से मिलाती है।'),
      can: t(['Pay by UPI: scan the QR or pay to our UPI ID (on phones: "Pay using UPI app")', 'Enter the UTR and optionally upload a screenshot', 'Pay by card / net banking / wallets / EMI when the store has switched them on'],
        ['UPI से भुगतान: QR स्कैन करें या हमारी UPI ID पर भेजें (फ़ोन पर "Pay using UPI app")', 'UTR डालें और चाहें तो स्क्रीनशॉट अपलोड करें', 'स्टोर चालू करे तो कार्ड / नेट बैंकिंग / वॉलेट / EMI से भुगतान']),
      steps: t(['Choose "UPI".', 'Scan the QR with any UPI app (or copy the UPI ID) and pay the exact amount.', 'Copy the 12-digit UTR / reference number from your UPI app.', 'Paste it in "UPI transaction / reference ID (UTR)".', 'Tap "✅ I HAVE PAID".'],
        ['"UPI" चुनें।', 'किसी भी UPI ऐप से QR स्कैन करें (या UPI ID कॉपी करें) और सही रकम भेजें।', 'UPI ऐप से 12 अंकों का UTR / रेफ़रेंस नंबर कॉपी करें।', 'उसे "UPI transaction / reference ID (UTR)" में डालें।', '"✅ I HAVE PAID" दबाएँ।']),
      after: t('Payment status becomes "Payment Verification Pending". When our team confirms it, it changes to "Payment Confirmed" and you get a message. Card payments are confirmed instantly.',
        'भुगतान स्टेटस "Payment Verification Pending" हो जाता है। टीम पुष्टि करे तो "Payment Confirmed" हो जाता है और आपको मैसेज मिलता है। कार्ड भुगतान तुरंत पक्का होता है।'),
      statuses: STATUS.payment,
      important: t(['Cash on delivery is not available.', 'A UTR already used for another order is not accepted.', 'If card/net banking says "coming soon", please pay by UPI.', 'A failed card payment does not take money.'], ['कैश ऑन डिलीवरी उपलब्ध नहीं है।', 'किसी दूसरे ऑर्डर में उपयोग हुआ UTR स्वीकार नहीं होता।', 'अगर कार्ड/नेट बैंकिंग "coming soon" दिखाए तो UPI से भुगतान करें।', 'फ़ेल हुए कार्ड भुगतान में पैसा नहीं कटता।']),
      mistakes: t(['Paying a different amount than shown', 'Entering the UPI ID or phone number instead of the 12-digit UTR', 'Closing the page before tapping "I HAVE PAID"'], ['दिखाई रकम से अलग रकम भेजना', '12 अंकों के UTR की जगह UPI ID या फ़ोन नंबर डालना', '"I HAVE PAID" दबाने से पहले पेज बंद करना']),
    },
    {
      id: 'confirmation', title: t('Order Confirmation', 'ऑर्डर कन्फ़र्मेशन'), shot: 'c_order',
      callouts: [
        ['text:Order Placed Successfully', t('Order placed message and Order ID', 'ऑर्डर हुआ संदेश और ऑर्डर ID')],
        ['css:.pill', t('Payment and order status', 'भुगतान और ऑर्डर स्टेटस')],
        ['text:Order status', t('Order status timeline', 'ऑर्डर स्टेटस टाइमलाइन')],
        ['text:Get help', t('Problem with this order? Get help · Chat with us', 'ऑर्डर में समस्या? मदद लें · चैट करें')],
      ],
      what: t('The order page you see right after ordering ("Order Placed Successfully!"). You can open it again any time from My Orders.', 'ऑर्डर करने के तुरंत बाद दिखने वाला पेज ("Order Placed Successfully!")। इसे My Orders से कभी भी फिर खोल सकते हैं।'),
      why: t('It confirms your order number, what you bought, where it goes and its live status.', 'यह आपका ऑर्डर नंबर, खरीदा सामान, पता और मौजूदा स्टेटस पक्का बताता है।'),
      can: t(['Note your Order ID', 'Complete payment if still pending', 'Follow the status timeline', 'See courier/AWB details or the delivery person and your 4-digit delivery code', 'Get help for this order'],
        ['अपना ऑर्डर ID नोट करें', 'भुगतान बाकी हो तो पूरा करें', 'स्टेटस टाइमलाइन देखें', 'कूरियर/AWB या डिलीवरी व्यक्ति और आपका 4 अंकों का डिलीवरी कोड देखें', 'इस ऑर्डर के लिए मदद लें']),
      statuses: STATUS.order,
      important: t(['Share the 4-digit delivery code with the delivery person ONLY after you receive the parcel.'], ['4 अंकों का डिलीवरी कोड डिलीवरी व्यक्ति को केवल पार्सल मिलने के बाद ही बताएँ।']),
    },
    {
      id: 'orders', title: t('My Orders', 'मेरे ऑर्डर'), shot: 'c_orders',
      callouts: [
        ['css:.order-row', t('Order card: number, date, total, payment and order status', 'ऑर्डर कार्ड: नंबर, तारीख, कुल, भुगतान और ऑर्डर स्टेटस')],
        ['text:Track order', t('Track order — timeline opens here', 'Track order — टाइमलाइन यहीं खुलती है')],
        ['text:View details', t('View details (or "Complete payment")', 'View details (या "Complete payment")')],
      ],
      what: t('"My Orders" tab in My account (also "Returns & Orders" in the header).', 'My account का "My Orders" टैब (हेडर में "Returns & Orders" भी)।'),
      why: t('One list of all your orders with their current status.', 'आपके सारे ऑर्डर उनके मौजूदा स्टेटस के साथ एक लिस्ट में।'),
      can: t(['See all orders', 'Track an order', 'Open details or complete a pending payment'], ['सारे ऑर्डर देखें', 'ऑर्डर ट्रैक करें', 'विवरण खोलें या बाकी भुगतान पूरा करें']),
      steps: t(['Tap "Returns & Orders".', 'Find the order.', 'Tap "Track order" or "View details".'], ['"Returns & Orders" दबाएँ।', 'ऑर्डर ढूँढें।', '"Track order" या "View details" दबाएँ।']),
      statuses: STATUS.order,
    },
    {
      id: 'tracking', title: t('Order Tracking', 'ऑर्डर ट्रैकिंग'), shot: 'c_track',
      callouts: [
        ['label:Order ID', t('Order ID (e.g. DIWALI10245)', 'ऑर्डर ID (जैसे DIWALI10245)')],
        ['label:Mobile', t('Mobile number used for the order', 'ऑर्डर में दिया मोबाइल नंबर')],
        ['css:.track__form button', t('Track', 'Track (ट्रैक करें)')],
        ['css:section.card', t('Result: status timeline', 'नतीजा: स्टेटस टाइमलाइन')],
      ],
      what: t('"Track Your Order" page (Track Order in the top menu). Works without signing in.', '"Track Your Order" पेज (ऊपर मेन्यू में Track Order)। बिना साइन इन के भी चलता है।'),
      why: t('Anyone with the order number and the phone number can check progress — useful for gifts and family orders.', 'ऑर्डर नंबर और फ़ोन नंबर वाला कोई भी प्रगति देख सकता है — गिफ़्ट और परिवार के ऑर्डर के लिए उपयोगी।'),
      steps: t(['Open "Track Order".', 'Enter the Order ID and the mobile number.', 'Tap "Track".'], ['"Track Order" खोलें।', 'ऑर्डर ID और मोबाइल नंबर डालें।', '"Track" दबाएँ।']),
      after: t('You see the timeline, the city/PIN and courier details. For privacy only the first name is shown.', 'टाइमलाइन, शहर/PIN और कूरियर विवरण दिखते हैं। गोपनीयता के लिए केवल पहला नाम दिखता है।'),
      mistakes: t(['Using a different mobile number than on the order', 'Typing the order number without the letters'], ['ऑर्डर वाले नंबर से अलग मोबाइल नंबर डालना', 'ऑर्डर नंबर के अक्षर छोड़कर लिखना']),
    },
    {
      id: 'cancel', title: t('Cancellation', 'कैंसलेशन'), shot: 'c_cancel',
      callouts: [
        ['text:Cancel, return', t('"Cancel, return & refund" box on the order page', 'ऑर्डर पेज पर "Cancel, return & refund" बॉक्स')],
        ['label:Why are you cancelling', t('Choose why you are cancelling', 'कैंसल करने का कारण चुनें')],
        ['text:Yes, cancel order', t('Yes, cancel order', 'Yes, cancel order (हाँ, कैंसल करें)')],
        ['text:Keep my order', t('Keep my order', 'Keep my order (ऑर्डर रखें)')],
      ],
      what: t('The "Cancel order" button on your order page (My Orders → the order). It shows only while the order can still be cancelled.', 'आपके ऑर्डर पेज पर "Cancel order" बटन (My Orders → ऑर्डर)। यह तभी दिखता है जब ऑर्डर अभी कैंसल हो सकता है।'),
      why: t('So you can stop an order yourself, free of charge, before it is packed — and get a full refund automatically if you already paid.', 'ताकि आप पैक होने से पहले खुद, बिना शुल्क, ऑर्डर रोक सकें — और भुगतान हो चुका हो तो पूरा रिफ़ंड अपने-आप शुरू हो।'),
      can: t(['Cancel before packing starts', 'See if a refund was opened and its status'], ['पैकिंग शुरू होने से पहले कैंसल करें', 'देखें कि रिफ़ंड खुला या नहीं और उसका स्टेटस']),
      steps: t(['Open My account → My Orders → the order (or the order link in your email).', 'In "Cancel, return & refund" tap "Cancel order".', 'Choose a reason (or "Other" and type it).', 'Tap "Yes, cancel order".'], ['My account → My Orders → ऑर्डर खोलें (या ईमेल वाला ऑर्डर लिंक)।', '"Cancel, return & refund" में "Cancel order" दबाएँ।', 'कारण चुनें (या "Other" चुनकर लिखें)।', '"Yes, cancel order" दबाएँ।']),
      after: t('The order shows "Cancelled" and the items go back to stock. If you had paid, a full refund opens at once ("Refund pending") and reaches your original payment method in 5–7 working days; then it shows "Refunded" with the reference.', 'ऑर्डर "Cancelled" दिखता है और सामान स्टॉक में लौटता है। भुगतान हो चुका था तो पूरा रिफ़ंड तुरंत खुलता है ("Refund pending") और 5–7 कार्य दिवस में उसी भुगतान तरीके में पहुँचता है; फिर रेफ़रेंस के साथ "Refunded" दिखता है।'),
      statuses: STATUS.refund,
      important: t(['Cancel free of charge until the order is packed. After that the button disappears — you can refuse the delivery or request a return.', 'Partial cancellation (only some items) is not available; cancel the order and order again, or request a return after delivery.'], ['पैक होने तक बिना शुल्क कैंसल करें। उसके बाद बटन नहीं दिखता — आप डिलीवरी लेने से मना कर सकते हैं या रिटर्न माँग सकते हैं।', 'कुछ ही आइटम कैंसल करना (आंशिक) उपलब्ध नहीं है; पूरा ऑर्डर कैंसल करके दोबारा ऑर्डर करें, या डिलीवरी के बाद रिटर्न माँगें।']),
      mistakes: t(['Waiting until the parcel is packed — then only a return is possible', 'Paying for an order you already cancelled'], ['पार्सल पैक होने तक इंतज़ार — फिर सिर्फ़ रिटर्न हो सकता है', 'कैंसल किए ऑर्डर का भुगतान करना']),
    },
    {
      id: 'return', title: t('Return', 'रिटर्न'), shot: 'c_return',
      callouts: [
        ['css:.ret-pick', t('Choose which items and how many', 'कौन से आइटम और कितने, चुनें')],
        ['label:Reason', t('Reason (damaged, wrong, missing, not as shown, quality, no longer needed)', 'कारण (टूटा, गलत, कम, जैसा दिखाया वैसा नहीं, क्वालिटी, अब ज़रूरत नहीं)')],
        ['label:Photo', t('Photo of the item and the box (needed for damaged / wrong items)', 'आइटम और डिब्बे की फ़ोटो (टूटे / गलत आइटम के लिए ज़रूरी)')],
        ['text:Send return request', t('Send return request', 'रिटर्न रिक्वेस्ट भेजें')],
      ],
      what: t('"Request a return" on a delivered order (My Orders → the order → "Cancel, return & refund").', 'डिलीवर हुए ऑर्डर पर "Request a return" (My Orders → ऑर्डर → "Cancel, return & refund")।'),
      why: t('So you can return items yourself within the return window and track the pickup and refund in one place, as per the Cancellation, Return & Refund Policy.', 'ताकि आप रिटर्न विंडो में खुद आइटम लौटा सकें और पिकअप व रिफ़ंड एक जगह देख सकें, Cancellation, Return & Refund Policy के अनुसार।'),
      can: t(['Return some or all pieces', 'Add a photo', 'See the refund amount before you send', 'Follow the status'], ['कुछ या सभी पीस लौटाएँ', 'फ़ोटो जोड़ें', 'भेजने से पहले रिफ़ंड राशि देखें', 'स्टेटस देखें']),
      steps: t(['Open the delivered order.', 'Tap "Request a return".', 'Choose how many of each item to return.', 'Choose the reason; write what happened (optional).', 'Add a photo (needed for damaged or wrong items).', 'Tap "Send return request".'], ['डिलीवर हुआ ऑर्डर खोलें।', '"Request a return" दबाएँ।', 'हर आइटम में से कितने लौटाने हैं, चुनें।', 'कारण चुनें; क्या हुआ लिखें (वैकल्पिक)।', 'फ़ोटो जोड़ें (टूटे या गलत आइटम के लिए ज़रूरी)।', '"Send return request" दबाएँ।']),
      after: t('You get a return number (RET-…). Our team approves it (or explains why not) within 1 working day and arranges the pickup. When the item reaches us, your refund opens; you see "Refunded" with the reference once it is sent.', 'आपको रिटर्न नंबर (RET-…) मिलता है। टीम 1 कार्य दिवस में मंज़ूर करती है (या कारण बताती है) और पिकअप करवाती है। सामान हमारे पास पहुँचने पर रिफ़ंड खुलता है; भेजने पर रेफ़रेंस के साथ "Refunded" दिखता है।'),
      statuses: STATUS.returns,
      important: t(['Return window: 7 days from delivery. Damaged, wrong or missing items: within 48 hours, with photos.', 'Refund = what you paid for those pieces (after discounts). The delivery charge is also refunded once when an item was damaged, wrong or missing.', 'Items must be unused and in original packing, unless damaged or wrong. Diyas with oil, used candles, puja consumables, food and personalised items cannot be returned unless damaged or wrong.', 'One open return request per order at a time.'], ['रिटर्न विंडो: डिलीवरी से 7 दिन। टूटा, गलत या कम सामान: 48 घंटे के अंदर, फ़ोटो के साथ।', 'रिफ़ंड = उन पीस के लिए आपने जो दिया (छूट के बाद)। टूटा, गलत या कम सामान होने पर डिलीवरी शुल्क भी एक बार लौटता है।', 'सामान बिना इस्तेमाल और असली पैकिंग में हो, जब तक टूटा या गलत न हो। तेल वाले दीये, जली मोमबत्ती, पूजा सामग्री, खाने का सामान और पर्सनलाइज़्ड आइटम टूटे या गलत न हों तो वापस नहीं होते।', 'एक ऑर्डर पर एक समय में एक खुली रिटर्न रिक्वेस्ट।']),
      planned: t(['Booking a pickup time slot yourself is a Planned Feature — today our team calls you to arrange it.'], ['पिकअप का समय खुद चुनना Planned Feature है — अभी टीम कॉल करके तय करती है।']),
      mistakes: t(['No photo for a damaged item', 'Throwing away the box before the pickup', 'Asking after the window ended — contact Help Center'], ['टूटे आइटम की फ़ोटो न देना', 'पिकअप से पहले डिब्बा फेंक देना', 'विंडो खत्म होने के बाद माँगना — Help Center से संपर्क करें']),
    },
    {
      id: 'refund', title: t('Refund', 'रिफ़ंड'), shot: 'c_refund',
      callouts: [
        ['text:Your returns', t('Your returns with their status and refund amount', 'आपके रिटर्न — स्टेटस और रिफ़ंड राशि के साथ')],
        ['text:Refunds', t('Refunds: amount, status and bank reference', 'रिफ़ंड: राशि, स्टेटस और बैंक रेफ़रेंस')],
      ],
      shot2: 'c_payhistory',
      callouts2: [
        ['text:Payment History', t('Payment History tab', 'Payment History टैब')],
        ['css:table', t('Each payment with method, UTR and status ("Refunded" when fully returned)', 'हर भुगतान: तरीका, UTR और स्टेटस (पूरा लौटने पर "Refunded")')],
      ],
      what: t('Refunds show on the order page (under "Cancel, return & refund") and in My account → Payment History.', 'रिफ़ंड ऑर्डर पेज पर ("Cancel, return & refund" के नीचे) और My account → Payment History में दिखते हैं।'),
      why: t('To see that your money has been returned after a cancellation or a return, with the reference to show your bank.', 'कैंसलेशन या रिटर्न के बाद पैसा वापस हुआ, यह रेफ़रेंस के साथ देखने के लिए — जो आप बैंक को दिखा सकें।'),
      steps: t(['Open the order (My account → My Orders).', 'Look at "Refunds": amount and status.', 'When it says "Refunded", note the reference.', 'Not received 7 working days after "Refunded"? Raise a "Refund status" request with that reference.'], ['ऑर्डर खोलें (My account → My Orders)।', '"Refunds" में राशि और स्टेटस देखें।', '"Refunded" दिखने पर रेफ़रेंस नोट करें।', '"Refunded" के 7 कार्य दिवस बाद भी नहीं मिला? उस रेफ़रेंस के साथ "Refund status" रिक्वेस्ट बनाएँ।']),
      statuses: STATUS.refund,
      important: t(['Refunds go back to the original payment method. UPI usually 1–3 days; cards 5–7 working days after "Refunded".', 'A refund is never more than what you paid, and each refund is paid only once.'], ['रिफ़ंड उसी भुगतान तरीके में जाता है। "Refunded" के बाद UPI में आम तौर पर 1–3 दिन; कार्ड में 5–7 कार्य दिवस।', 'रिफ़ंड कभी भी आपके भुगतान से ज़्यादा नहीं होता, और हर रिफ़ंड एक ही बार दिया जाता है।']),
    },
    {
      id: 'support', title: t('Customer Support', 'ग्राहक सहायता'), shot: 'c_help',
      callouts: [
        ['ph:Search: refund', t('Search help articles', 'मदद लेख खोजें')],
        ['text:Track order', t('Quick buttons: Track order, Chat with us, WhatsApp, Call us, Raise a request', 'तुरंत बटन: Track order, Chat with us, WhatsApp, Call us, Raise a request')],
        ['text:Common problems', t('Common problems — instant answers', 'आम समस्याएँ — तुरंत जवाब')],
      ],
      what: t('Help Center ("How can we help you? 🙏"), the 💬 chat assistant "Utsav Sahayak" and your request pages.', 'Help Center ("How can we help you? 🙏"), 💬 चैट सहायक "Utsav Sahayak" और आपकी रिक्वेस्ट के पेज।'),
      why: t('To solve problems fast — many answers are instant, and the rest go to our team with all details.', 'समस्याएँ जल्दी हल करने के लिए — कई जवाब तुरंत मिलते हैं, बाकी पूरी जानकारी के साथ टीम तक पहुँचते हैं।'),
      can: t(['Read instant answers', 'Chat in English, Hinglish or Hindi', 'Raise a request (with photo) and reply in the thread', 'WhatsApp or call us', 'Rate our help with 1–5 stars'], ['तुरंत जवाब पढ़ें', 'अंग्रेज़ी, हिंग्लिश या हिंदी में चैट करें', 'रिक्वेस्ट बनाएँ (फ़ोटो के साथ) और उसी में जवाब दें', 'WhatsApp या कॉल करें', '1–5 स्टार से हमारी मदद को रेटिंग दें']),
      steps: t(['Open "Customer Service".', 'Search or tap a common problem.', 'Still stuck? Tap "Raise a request", choose a topic, fill details, "Send request".', 'Follow replies at Help requests in My account.'], ['"Customer Service" खोलें।', 'खोजें या कोई आम समस्या दबाएँ।', 'फिर भी हल नहीं? "Raise a request" दबाएँ, विषय चुनें, जानकारी भरें, "Send request"।', 'My account के Help requests में जवाब देखें।']),
      statuses: STATUS.ticket,
      important: t(['We reply within a few hours (10 am – 8 pm, Mon–Sat).', 'One open request per order and topic — reply in the existing one.'], ['हम कुछ घंटों में जवाब देते हैं (सुबह 10 – रात 8, सोम–शनि)।', 'एक ऑर्डर और विषय पर एक खुली रिक्वेस्ट — उसी में जवाब दें।']),
    },
    {
      id: 'reviews', title: t('Reviews & Ratings', 'रिव्यू और रेटिंग'), shot: 'c_review',
      callouts: [
        ['text:Write a review', t('Write a review', 'रिव्यू लिखें')],
        ['css:.rate-pick', t('Choose 1–5 stars', '1–5 स्टार चुनें')],
        ['text:Submit review', t('Submit review', 'रिव्यू भेजें')],
      ],
      what: t('The reviews part of each product page.', 'हर प्रोडक्ट पेज का रिव्यू वाला हिस्सा।'),
      why: t('Honest reviews from real buyers help other customers choose well.', 'असली खरीदारों के ईमानदार रिव्यू दूसरे ग्राहकों को सही चुनने में मदद करते हैं।'),
      can: t(['Give 1–5 stars', 'Write your review (at least 10 characters)', 'Add a photo (optional, up to 5 MB)'], ['1–5 स्टार दें', 'रिव्यू लिखें (कम से कम 10 अक्षर)', 'फ़ोटो जोड़ें (वैकल्पिक, 5 MB तक)']),
      steps: t(['Sign in and open a product you bought.', 'Go to "Write a review".', 'Choose stars, write, add a photo if you like.', 'Tap "Submit review".'], ['साइन इन करें और खरीदा हुआ प्रोडक्ट खोलें।', '"Write a review" पर जाएँ।', 'स्टार चुनें, लिखें, चाहें तो फ़ोटो जोड़ें।', '"Submit review" दबाएँ।']),
      after: t('"Your review will appear after moderation." Approved reviews show "✓ Verified purchase".', '"Your review will appear after moderation." मंज़ूर रिव्यू पर "✓ Verified purchase" दिखता है।'),
      statuses: [[t('Pending', 'बाकी'), t('Waiting for moderation', 'मॉडरेशन का इंतज़ार')], [t('Approved', 'मंज़ूर'), t('Visible on the product', 'प्रोडक्ट पर दिखता है')], [t('Rejected', 'अस्वीकार'), t('Broke the Review Policy', 'Review Policy के खिलाफ़')]],
      important: t(['You can review only products from your confirmed (paid) orders, once per product.'], ['आप केवल अपने पक्के (भुगतान हुए) ऑर्डर के प्रोडक्ट का रिव्यू दे सकते हैं, हर प्रोडक्ट पर एक बार।']),
    },
    {
      id: 'notifications', title: t('Notifications', 'सूचनाएँ'), shot: 'c_alerts',
      callouts: [
        ['text:Send me deals on', t('Channel: WhatsApp / Email', 'माध्यम: WhatsApp / ईमेल')],
        ['text:How often', t('How often: daily, weekly or only festival alerts', 'कितनी बार: रोज़, हफ़्ते में या केवल त्योहार अलर्ट')],
        ['text:Get my deals', t('🔔 Get my deals', '🔔 मेरे ऑफ़र पाएँ')],
      ],
      what: t('Messages we send: order updates (email/WhatsApp) and optional deals & festival alerts.', 'हम जो मैसेज भेजते हैं: ऑर्डर अपडेट (ईमेल/WhatsApp) और वैकल्पिक ऑफ़र व त्योहार अलर्ट।'),
      why: t('Order messages keep you informed at each step; deal alerts are only sent if you ask for them.', 'ऑर्डर मैसेज हर चरण पर जानकारी देते हैं; ऑफ़र अलर्ट केवल आपके कहने पर भेजे जाते हैं।'),
      can: t(['Receive order received / payment confirmed / shipped / out for delivery (with code) / delivered / cancelled messages', 'Subscribe to deals ("🔔 Deals & festival alerts")', 'Change or stop messages using the link in any message ("Your message settings" → "Unsubscribe from everything")'],
        ['ऑर्डर मिला / भुगतान पक्का / शिप / डिलीवरी पर (कोड के साथ) / डिलीवर / कैंसल के मैसेज पाएँ', 'ऑफ़र के लिए सब्सक्राइब करें ("🔔 Deals & festival alerts")', 'किसी भी मैसेज के लिंक से मैसेज बदलें या बंद करें ("Your message settings" → "Unsubscribe from everything")']),
      steps: t(['Footer → "🔔 Get deals on WhatsApp / email" (or My account → Deals & festival alerts).', 'Choose channel, how often and interests.', 'Tick the consent box and tap "🔔 Get my deals".'], ['फ़ुटर → "🔔 Get deals on WhatsApp / email" (या My account → Deals & festival alerts)।', 'माध्यम, कितनी बार और रुचियाँ चुनें।', 'सहमति बॉक्स टिक करके "🔔 Get my deals" दबाएँ।']),
      important: t(['We never ask for OTPs, PINs or passwords in any message.'], ['हम किसी भी मैसेज में OTP, PIN या पासवर्ड कभी नहीं माँगते।']),
    },
    {
      id: 'legal', title: t('Legal & Agreements', 'कानूनी दस्तावेज़ और एग्रीमेंट'), shot: 'c_legal',
      callouts: [
        ['text:View online', t('👁️ View online', '👁️ ऑनलाइन देखें')],
        ['text:Download PDF', t('⬇️ Download PDF', '⬇️ PDF डाउनलोड')],
        ['text:Print', t('🖨️ Print', '🖨️ प्रिंट')],
        ['text:Agreements you accepted', t('Agreements you accepted — version, date, agreement number', 'आपके स्वीकार किए एग्रीमेंट — वर्ज़न, तारीख, एग्रीमेंट नंबर')],
      ],
      what: t('My account → Legal & Agreements, plus the public pages Terms, Privacy, Returns and "All Policies" (/policies).', 'My account → Legal & Agreements, और सार्वजनिक पेज Terms, Privacy, Returns और "All Policies" (/policies)।'),
      why: t('This page allows customers to understand the rules of using the marketplace and gives access to the important legal documents — the current ones and the exact versions you accepted.', 'यह पेज ग्राहकों को मार्केटप्लेस के नियम समझाता है और ज़रूरी कानूनी दस्तावेज़ देता है — मौजूदा भी और आपके स्वीकार किए सही वर्ज़न भी।'),
      can: t(['Read Customer Terms, Privacy Policy and the Cancellation, Return & Refund Policy (Payment, Shipping and other policies on /policies once published)', 'Switch "Simple explanation" / "Full legal terms"', 'View, Download PDF, Print', 'See every version you accepted with its agreement number'],
        ['Customer Terms, Privacy Policy और Cancellation, Return & Refund Policy पढ़ें (Payment, Shipping और बाकी पॉलिसी प्रकाशित होने पर /policies पर)', '"Simple explanation" / "Full legal terms" बदलें', 'देखें, PDF डाउनलोड करें, प्रिंट करें', 'आपका स्वीकार किया हर वर्ज़न एग्रीमेंट नंबर के साथ देखें']),
      steps: t(['My account → Legal & Agreements.', 'Tap "View online", "Download PDF" or "Print" on a document.', 'In "Agreements you accepted" tap "PDF" for your signed copy.'], ['My account → Legal & Agreements।', 'किसी दस्तावेज़ पर "View online", "Download PDF" या "Print" दबाएँ।', '"Agreements you accepted" में अपनी कॉपी के लिए "PDF" दबाएँ।']),
      important: t(['Why acceptance is required: it records which version of the rules applies to your orders. When we make an important change, you are asked to accept the new version before your next order.', 'The simple explanation helps you understand; the Full legal terms are the binding text.'],
        ['स्वीकृति क्यों ज़रूरी है: इससे दर्ज होता है कि आपके ऑर्डर पर नियमों का कौन सा वर्ज़न लागू है। ज़रूरी बदलाव होने पर अगले ऑर्डर से पहले नया वर्ज़न स्वीकार करना होता है।', 'आसान भाषा समझने के लिए है; "Full legal terms" ही बाध्यकारी (लागू) पाठ है।']),
    },
    {
      id: 'privacy', title: t('Privacy', 'गोपनीयता'), shot: 'c_privacy',
      callouts: [
        ['css:.lg-meta', t('Version and effective date', 'वर्ज़न और लागू होने की तारीख')],
        ['css:.lg-mode', t('Simple explanation / Full legal terms', 'आसान भाषा / पूरी कानूनी शर्तें')],
      ],
      what: t('The Privacy Policy page (footer → Privacy Policy).', 'Privacy Policy पेज (फ़ुटर → Privacy Policy)।'),
      why: t('It explains what personal data we collect, why, who we share it with and your rights under the Digital Personal Data Protection Act, 2023.', 'यह बताता है कि हम कौन सा व्यक्तिगत डेटा लेते हैं, क्यों, किसके साथ साझा करते हैं और डिजिटल व्यक्तिगत डेटा संरक्षण अधिनियम, 2023 के तहत आपके अधिकार क्या हैं।'),
      can: t(['Read and download the policy', 'Download all your data (My account → Login & Security → "Download my data")', 'Delete your account'], ['पॉलिसी पढ़ें और डाउनलोड करें', 'अपना सारा डेटा डाउनलोड करें (My account → Login & Security → "Download my data")', 'अपना अकाउंट डिलीट करें']),
      important: t(['Dealers see your name, phone and address only after they accept your order, only to deliver it.'], ['डीलर आपका नाम, फ़ोन और पता केवल ऑर्डर स्वीकार करने के बाद, केवल डिलीवरी के लिए देखते हैं।']),
    },
    {
      id: 'security', title: t('Account Security', 'अकाउंट सुरक्षा'), shot: 'c_security',
      callouts: [
        ['text:Change password', t('🔑 Change password', '🔑 पासवर्ड बदलें')],
        ['text:Sign out on all devices', t('💻 Sign out on all devices + recent activity', '💻 सभी डिवाइस से साइन आउट + हाल की गतिविधि')],
        ['text:Download my data', t('📦 Download my data', '📦 मेरा डेटा डाउनलोड करें')],
        ['text:Delete my account', t('🗑️ Delete my account', '🗑️ मेरा अकाउंट डिलीट करें')],
      ],
      what: t('My account → Login & Security.', 'My account → Login & Security।'),
      why: t('To keep your account safe and in your control.', 'आपके अकाउंट को सुरक्षित और आपके नियंत्रण में रखने के लिए।'),
      can: t(['Change password (signs out other devices; you get an email)', 'Sign out on all devices', 'See recent sign-ins and changes', 'Download your data (JSON file)', 'Delete your account (type DELETE to confirm)'], ['पासवर्ड बदलें (बाकी डिवाइस साइन आउट होते हैं; ईमेल आता है)', 'सभी डिवाइस से साइन आउट', 'हाल के साइन-इन और बदलाव देखें', 'अपना डेटा डाउनलोड करें (JSON फ़ाइल)', 'अकाउंट डिलीट करें (पुष्टि के लिए DELETE लिखें)']),
      steps: t(['Change password: enter Current password and New password → save.', 'Lost phone or shared computer? Tap "Sign out on all devices".'], ['पासवर्ड बदलें: Current password और New password डालें → सेव।', 'फ़ोन खो गया या कंप्यूटर साझा था? "Sign out on all devices" दबाएँ।']),
      important: t(['Deleting the account cannot be undone. Orders are kept for legal records but are no longer linked to you.', 'Never share your password or OTPs.'], ['अकाउंट डिलीट वापस नहीं होता। ऑर्डर कानूनी रिकॉर्ड के लिए रखे जाते हैं पर आपसे जुड़े नहीं रहते।', 'पासवर्ड या OTP किसी से साझा न करें।']),
      planned: t(['Two-step login for customers is a Planned Feature.'], ['ग्राहकों के लिए दो-चरण लॉगिन Planned Feature है।']),
    },
    {
      id: 'logout', title: t('Logout', 'लॉगआउट'), shot: 'c_logout',
      callouts: [['text:Sign out', t('Sign out', 'साइन आउट')]],
      what: t('The "Sign out" button at the top of My account.', 'My account के ऊपर "Sign out" बटन।'),
      why: t('Always sign out on shared or public devices so nobody else can see your orders or addresses.', 'साझा या सार्वजनिक डिवाइस पर हमेशा साइन आउट करें ताकि कोई और आपके ऑर्डर या पते न देख सके।'),
      steps: t(['Open My account.', 'Tap "Sign out".'], ['My account खोलें।', '"Sign out" दबाएँ।']),
      after: t('You are signed out on this device. Your cart stays saved in this browser.', 'इस डिवाइस से साइन आउट हो जाते हैं। आपका कार्ट इसी ब्राउज़र में सेव रहता है।'),
    },
    {
      id: 'problems', title: t('Common Problems', 'आम समस्याएँ'),
      table: [
        [t('"Accept & Create Account" is grey', '"Accept & Create Account" धुंधला है'), t('Read "Still needed:" under the button — fill that field or tick that box.', 'बटन के नीचे "Still needed:" पढ़ें — वह फ़ील्ड भरें या बॉक्स टिक करें।')],
        [t('Sign-in paused / account locked', 'साइन-इन रुका / अकाउंट लॉक'), t('Wait 15 minutes and try again, or contact us.', '15 मिनट रुककर फिर कोशिश करें, या संपर्क करें।')],
        [t('Forgot password', 'पासवर्ड भूल गए'), t('Sign in page → "Forgot password?" → code to your email and mobile → new password.', 'साइन इन पेज → "Forgot password?" → ईमेल और मोबाइल पर कोड → नया पासवर्ड।')],
        [t('Sign-up code not received', 'साइन-अप कोड नहीं आया'), t('Check the mobile number and email, and your spam folder. Tap "Resend code" after 30 seconds.', 'मोबाइल नंबर, ईमेल और स्पैम फ़ोल्डर जाँचें। 30 सेकंड बाद "Resend code" दबाएँ।')],
        [t('"Cancel order" button is not shown', '"Cancel order" बटन नहीं दिख रहा'), t('The order is already packed or on its way. Refuse the delivery or request a return after delivery.', 'ऑर्डर पैक हो चुका है या रास्ते में है। डिलीवरी लेने से मना करें या डिलीवरी के बाद रिटर्न माँगें।')],
        [t('Paid by UPI but status is still "Verification Pending"', 'UPI से भुगतान किया पर स्टेटस अभी "Verification Pending"'), t('Our team confirms during working hours. If more than a day, raise "Payment deducted / not confirmed" with the UTR.', 'टीम कार्य समय में पुष्टि करती है। एक दिन से ज़्यादा हो तो UTR के साथ "Payment deducted / not confirmed" रिक्वेस्ट बनाएँ।')],
        [t('Money deducted but order not placed', 'पैसा कटा पर ऑर्डर नहीं हुआ'), t('Banks usually reverse it automatically within 7 working days. Otherwise raise a request with the transaction reference.', 'बैंक आम तौर पर 7 कार्य दिवस में अपने-आप वापस करते हैं। नहीं तो ट्रांज़ैक्शन रेफ़रेंस के साथ रिक्वेस्ट बनाएँ।')],
        [t('"Order not found" on the order page', 'ऑर्डर पेज पर "Order not found"'), t('Sign in, or use Track Order with order number + phone.', 'साइन इन करें, या ऑर्डर नंबर + फ़ोन से Track Order उपयोग करें।')],
        [t('Coupon not applied', 'कूपन नहीं लगा'), t('Check minimum items/end date; a better automatic offer may already apply.', 'न्यूनतम आइटम/अंतिम तारीख जाँचें; हो सकता है बेहतर ऑटोमैटिक ऑफ़र पहले से लगा हो।')],
        [t('Can\'t place order — "accept updated terms"', 'ऑर्डर नहीं हो रहा — "updated terms स्वीकार करें"'), t('Tick the boxes in "We have updated our terms" and continue.', '"We have updated our terms" के बॉक्स टिक करके आगे बढ़ें।')],
        [t('Item damaged / wrong', 'सामान टूटा / गलत'), t('Open the order → "Request a return" within 48 hours, with photos.', 'ऑर्डर खोलें → 48 घंटे के अंदर फ़ोटो के साथ "Request a return"।')],
      ],
    },
    {
      id: 'faq', title: t('Frequently Asked Questions', 'अक्सर पूछे जाने वाले प्रश्न'),
      faq: [
        [t('Is cash on delivery available?', 'क्या कैश ऑन डिलीवरी है?'), t('Not right now. Pay by UPI (and cards/net banking when shown).', 'अभी नहीं। UPI से भुगतान करें (और दिखे तो कार्ड/नेट बैंकिंग)।')],
        [t('Can I order without an account?', 'क्या बिना अकाउंट ऑर्डर कर सकते हैं?'), t('Usually no — the store requires an account. Your cart is saved while you sign up.', 'आम तौर पर नहीं — स्टोर में अकाउंट ज़रूरी है। साइन अप करते समय कार्ट सेव रहता है।')],
        [t('How do I know my order is confirmed?', 'कैसे पता चले कि ऑर्डर पक्का हुआ?'), t('Payment status "Payment Confirmed" and a message by email/WhatsApp.', 'भुगतान स्टेटस "Payment Confirmed" और ईमेल/WhatsApp पर मैसेज।')],
        [t('What is the 4-digit delivery code?', '4 अंकों का डिलीवरी कोड क्या है?'), t('Proof that you received the parcel. Give it only after you have the parcel in hand.', 'यह प्रमाण है कि आपको पार्सल मिला। पार्सल हाथ में आने के बाद ही बताएँ।')],
        [t('Do you deliver outside India?', 'क्या भारत के बाहर डिलीवरी है?'), t('Only when the store switches on international shipping; then "Deliver to" lets you pick a country.', 'केवल तब, जब स्टोर अंतरराष्ट्रीय शिपिंग चालू करे; तब "Deliver to" से देश चुनें।')],
        [t('How long do refunds take?', 'रिफ़ंड में कितना समय लगता है?'), t('UPI usually 1–3 days, cards 5–7 working days after we process it.', 'प्रोसेस होने के बाद UPI में आम तौर पर 1–3 दिन, कार्ड में 5–7 कार्य दिवस।')],
        [t('Why must I accept the terms again?', 'शर्तें दोबारा क्यों स्वीकार करनी हैं?'), t('We published an important change. Acceptance records which version applies to you.', 'हमने ज़रूरी बदलाव प्रकाशित किया है। स्वीकृति से दर्ज होता है कि आप पर कौन सा वर्ज़न लागू है।')],
        [t('Can I change my email?', 'क्या ईमेल बदल सकते हैं?'), t('Yes: My account → My Profile → "Change email". Enter your password and the code we send to the new email.', 'हाँ: My account → My Profile → "Change email"। अपना पासवर्ड और नए ईमेल पर भेजा गया कोड डालें।')],
        [t('Can I cancel only one item?', 'क्या एक ही आइटम कैंसल कर सकते हैं?'), t('Not before delivery — cancel the whole order (free until packed). After delivery you can return single pieces.', 'डिलीवरी से पहले नहीं — पूरा ऑर्डर कैंसल करें (पैक होने तक मुफ़्त)। डिलीवरी के बाद एक-एक पीस लौटा सकते हैं।')],
      ],
    },
  ],
};
