/** Dealer User Manual — content (English + Hindi). See common.js for the format. */
import { t, STATUS } from './common.js';

export default {
  key: 'dealer',
  file: 'Dealer_User_Manual',
  title: t('Dealer User Manual', 'डीलर उपयोगकर्ता मैनुअल'),
  subtitle: t('Complete Guide to Dealer Registration, KYC, Products, Orders & Payments', 'डीलर रजिस्ट्रेशन, KYC, प्रोडक्ट, ऑर्डर और भुगतान की पूरी गाइड'),
  audience: t('For Dealers', 'डीलरों के लिए'),
  help: 'dealer',
  phone: true,
  sections: [
    {
      id: 'intro', title: t('Introduction', 'परिचय'), shot: 'd_dashboard',
      callouts: [
        ['css:.dl-nav', t('Bottom menu: Dashboard, Orders, Products, Profile', 'नीचे का मेन्यू: Dashboard, Orders, Products, Profile')],
        ['css:.dl-bell', t('🔔 Notifications', '🔔 सूचनाएँ')],
        ['css:.dl-store', t('🏪 Store — open the Utsav Ghar website', '🏪 Store — Utsav Ghar वेबसाइट खोलें')],
      ],
      what: t('The Utsav Ghar dealer app ("UG Dealer" on phones, or /dealer in a browser). Dealers supply products and deliver orders to customers in their area.',
        'Utsav Ghar डीलर ऐप (फ़ोन पर "UG Dealer", या ब्राउज़र में /dealer)। डीलर प्रोडक्ट सप्लाई करते हैं और अपने इलाके के ग्राहकों तक ऑर्डर पहुँचाते हैं।'),
      why: t('One app to register, finish KYC and the agreement, list products, manage stock and handle orders.', 'एक ही ऐप से रजिस्टर करें, KYC और एग्रीमेंट पूरा करें, प्रोडक्ट डालें, स्टॉक संभालें और ऑर्डर पूरे करें।'),
      can: t(['Register and complete onboarding (7 steps)', 'See your earnings and stock on the Dashboard', 'Accept, pack and deliver orders', 'Add products and update stock', 'Read and download your agreements'], ['रजिस्टर करें और ऑनबोर्डिंग पूरी करें (7 चरण)', 'Dashboard पर कमाई और स्टॉक देखें', 'ऑर्डर स्वीकार, पैक और डिलीवर करें', 'प्रोडक्ट जोड़ें और स्टॉक अपडेट करें', 'अपने एग्रीमेंट पढ़ें और डाउनलोड करें']),
      flow: 'dealer_approval',
      important: t(['Every order is prepaid — never collect cash from the customer.', 'You only see your own dealer price. Customer selling prices and Utsav Ghar\'s profit are not shown in the dealer app.'], ['हर ऑर्डर प्रीपेड है — ग्राहक से कभी नकद न लें।', 'आपको केवल अपना डीलर प्राइस दिखता है। ग्राहक की कीमत और Utsav Ghar का मुनाफ़ा डीलर ऐप में नहीं दिखता।']),
    },
    {
      id: 'register', title: t('Dealer Registration', 'डीलर रजिस्ट्रेशन'), shot: 'd_register',
      callouts: [
        ['label:Business / shop name', t('Business / shop name', 'बिज़नेस / दुकान का नाम')],
        ['label:Mobile number', t('Mobile number — you sign in with it; signing OTP comes here', 'मोबाइल नंबर — इसी से साइन इन; साइनिंग OTP यहीं आता है')],
        ['label:Password', t('Password and Confirm password', 'पासवर्ड और पासवर्ड की पुष्टि')],
        ['text:Create dealer account', t('Create dealer account', 'डीलर अकाउंट बनाएँ')],
      ],
      what: t('"Register your business" — the first step to become a dealer. Open it from the dealer sign-in page: "🏪 New dealer? Register your business".', '"Register your business" — डीलर बनने का पहला कदम। डीलर साइन-इन पेज से खोलें: "🏪 New dealer? Register your business"।'),
      why: t('This page collects the dealer\'s basic identity so the company can identify the dealer and start the onboarding process. Full business details, PAN, GSTIN and bank come in the next steps.', 'यह पेज डीलर की बुनियादी पहचान लेता है ताकि कंपनी डीलर को पहचान सके और ऑनबोर्डिंग शुरू कर सके। पूरा बिज़नेस विवरण, PAN, GSTIN और बैंक अगले चरणों में आते हैं।'),
      can: t(['Create your dealer account in about 2 minutes'], ['लगभग 2 मिनट में डीलर अकाउंट बनाएँ']),
      steps: t(['Enter Business / shop name and Your name.', 'Enter your 10-digit Mobile number and Email.', 'Choose a Password (8+ characters) and confirm it.', 'Tap "Create dealer account".'], ['बिज़नेस / दुकान का नाम और अपना नाम भरें।', '10 अंकों का मोबाइल नंबर और ईमेल भरें।', 'पासवर्ड चुनें (8+ अक्षर) और पुष्टि करें।', '"Create dealer account" दबाएँ।']),
      after: t('You are signed in and taken to "Dealer onboarding". Status is Draft. You cannot receive orders until Utsav Ghar approves you.', 'आप साइन इन होकर "Dealer onboarding" पर पहुँचते हैं। स्टेटस Draft है। Utsav Ghar की मंज़ूरी तक ऑर्डर नहीं मिलेंगे।'),
      important: t(['One account per mobile number. If the number is already registered, sign in instead.'], ['एक मोबाइल नंबर पर एक अकाउंट। नंबर पहले से रजिस्टर हो तो साइन इन करें।']),
      mistakes: t(['Using a number you may change soon — it is your login and OTP number', 'Weak password like your shop name'], ['ऐसा नंबर जो जल्दी बदल सकता है — यही लॉगिन और OTP नंबर है', 'दुकान के नाम जैसा कमज़ोर पासवर्ड']),
    },
    {
      id: 'login', title: t('Dealer Login', 'डीलर लॉगिन'), shot: 'd_login',
      callouts: [
        ['label:Mobile number', t('Mobile number', 'मोबाइल नंबर')],
        ['label:Password', t('Password', 'पासवर्ड')],
        ['css:form .dl-btn--primary', t('Sign in', 'साइन इन')],
        ['text:New dealer?', t('New dealer? Register your business', 'नए डीलर? बिज़नेस रजिस्टर करें')],
        ['text:Forgot password?', t('Forgot password? Reset it with a code', 'Forgot password? कोड से रीसेट करें')],
        ['text:Back to Utsav Ghar store', t('← Back to Utsav Ghar store', '← Utsav Ghar स्टोर पर वापस')],
      ],
      what: t('The dealer "Sign in" page.', 'डीलर "Sign in" पेज।'),
      why: t('Only you can see your orders, customers\' delivery details and earnings.', 'केवल आप ही अपने ऑर्डर, ग्राहकों के डिलीवरी विवरण और कमाई देख सकते हैं।'),
      steps: t(['Open the UG Dealer app or /dealer.', 'Enter the registered Mobile number and Password.', 'Tap "Sign in".', 'If an admin created your account, set your own password on the next screen ("Set your password").'], ['UG Dealer ऐप या /dealer खोलें।', 'रजिस्टर्ड मोबाइल नंबर और पासवर्ड डालें।', '"Sign in" दबाएँ।', 'अगर एडमिन ने अकाउंट बनाया है तो अगली स्क्रीन ("Set your password") पर अपना पासवर्ड बनाएँ।']),
      after: t('Approved dealers see the Dashboard. Dealers still onboarding see the onboarding screens (Onboarding, Agreements, Profile). You stay signed in for 30 days.', 'मंज़ूर डीलर Dashboard देखते हैं। ऑनबोर्डिंग वाले डीलर ऑनबोर्डिंग स्क्रीन (Onboarding, Agreements, Profile) देखते हैं। आप 30 दिन तक साइन इन रहते हैं।'),
      shot2: 'd_forgot',
      callouts2: [
        ['label:Mobile number', t('Your registered mobile number', 'आपका रजिस्टर्ड मोबाइल नंबर')],
        ['text:Resend code', t('Send code (WhatsApp/SMS, and email if saved) — after sending it waits 30 s before "Resend code"', 'Send code (WhatsApp/SMS, और ईमेल हो तो उस पर भी) — भेजने के बाद "Resend code" के लिए 30 सेकंड रुकें')],
        ['label:6-digit code', t('Code you received', 'आपको मिला कोड')],
        ['text:Set new password', t('Set new password', 'नया पासवर्ड सेट करें')],
      ],
      important: t(['Several wrong passwords lock sign-in for a while.', 'Forgot your password? Tap "Forgot password?", enter your mobile number, tap "Send code", type the code, choose a new password. All other devices are signed out.', 'The code is valid for 10 minutes; "Send code" again after 30 seconds.'], ['कई बार गलत पासवर्ड पर कुछ समय के लिए साइन-इन लॉक होता है।', 'पासवर्ड भूल गए? "Forgot password?" दबाएँ, मोबाइल नंबर लिखें, "Send code" दबाएँ, कोड डालें, नया पासवर्ड चुनें। बाकी सभी डिवाइस साइन आउट हो जाते हैं।', 'कोड 10 मिनट चलता है; 30 सेकंड बाद दोबारा "Send code"।']),
    },
    {
      id: 'dashboard', title: t('Dealer Dashboard', 'डीलर डैशबोर्ड'), shot: 'd_dashboard2',
      callouts: [
        ['css:.dd-range', t('Period: 7 days, 30 days, 3 months, 1 year', 'अवधि: 7 दिन, 30 दिन, 3 महीने, 1 साल')],
        ['css:.dd-alerts', t('Alerts: new orders waiting, out of stock', 'अलर्ट: नए ऑर्डर, स्टॉक खत्म')],
        ['css:.dd-hero', t('Your earnings (delivered) at your dealer price', 'आपकी कमाई (डिलीवर) आपके डीलर प्राइस पर')],
        ['css:.dd-tiles', t('Tiles: stock, products live, open orders, low stock, stock in/out, service', 'टाइल: स्टॉक, लाइव प्रोडक्ट, खुले ऑर्डर, कम स्टॉक, स्टॉक आया/गया, सर्विस')],
      ],
      what: t('"Your business at a glance" — the first screen of the approved dealer app.', '"Your business at a glance" — मंज़ूर डीलर ऐप की पहली स्क्रीन।'),
      why: t('To see quickly what needs action (new orders, stock) and how your business is doing.', 'जल्दी देखने के लिए कि किस पर काम करना है (नए ऑर्डर, स्टॉक) और बिज़नेस कैसा चल रहा है।'),
      can: t(['Switch the period', 'See earnings: units sold, orders delivered, money "on the way"', 'Sales trend chart (₹ or units; "Show as table")', 'Sales by product, Top sellers, Stock in vs out', 'Stock alerts with "Update stock →"', 'Recent orders'], ['अवधि बदलें', 'कमाई देखें: बिकी यूनिट, डिलीवर ऑर्डर, "रास्ते में" पैसा', 'बिक्री ट्रेंड चार्ट (₹ या यूनिट; "Show as table")', 'प्रोडक्ट अनुसार बिक्री, टॉप सेलर, स्टॉक आया बनाम गया', '"Update stock →" के साथ स्टॉक अलर्ट', 'हाल के ऑर्डर']),
      important: t(['Earnings count only delivered orders, at your dealer price × quantity. You are paid as per your agreement.', 'Low stock means 5 pieces or fewer.'], ['कमाई में केवल डिलीवर ऑर्डर गिने जाते हैं, आपके डीलर प्राइस × मात्रा पर। भुगतान आपके एग्रीमेंट के अनुसार होता है।', 'कम स्टॉक का मतलब 5 या उससे कम पीस।']),
    },
    {
      id: 'business', title: t('Business Information', 'बिज़नेस जानकारी'), shot: 'd_business',
      callouts: [
        ['label:Legal entity name', t('Legal entity name (as on PAN / GST)', 'कानूनी नाम (PAN / GST के अनुसार)')],
        ['label:Business type', t('Business type', 'बिज़नेस का प्रकार')],
        ['label:Registered address', t('Registered address', 'पंजीकृत पता')],
        ['label:PIN code', t('PIN code (fills State)', 'PIN कोड (राज्य भरता है)')],
        ['text:Save & continue', t('Save & continue', 'सेव करें और आगे बढ़ें')],
      ],
      what: t('Onboarding step 1 — "Business information".', 'ऑनबोर्डिंग चरण 1 — "Business information"।'),
      why: t('This page collects the dealer\'s business information so that the company can identify the dealer, match orders to your area and complete the onboarding process.', 'यह पेज डीलर की बिज़नेस जानकारी लेता है ताकि कंपनी डीलर को पहचान सके, आपके इलाके के ऑर्डर आप तक भेज सके और ऑनबोर्डिंग पूरी कर सके।'),
      can: t(['Dealer (business/shop) name', 'Legal business name', 'Business type: Proprietorship, Partnership firm, LLP, Private Ltd, Public Ltd, Other', 'Contact person, email (mobile is fixed)', 'Registered address and business/pickup address', 'PIN, City, State, Country, Website (optional)'], ['डीलर (बिज़नेस/दुकान) नाम', 'कानूनी बिज़नेस नाम', 'बिज़नेस का प्रकार: Proprietorship, Partnership firm, LLP, Private Ltd, Public Ltd, Other', 'संपर्क व्यक्ति, ईमेल (मोबाइल तय है)', 'पंजीकृत पता और बिज़नेस/पिकअप पता', 'PIN, शहर, राज्य, देश, वेबसाइट (वैकल्पिक)']),
      steps: t(['In Dealer onboarding open step 1.', 'Fill all fields. Tick "Business / pickup address is the same" if it is.', 'Tap "Save & continue".'], ['Dealer onboarding में चरण 1 खोलें।', 'सारे फ़ील्ड भरें। अगर पता एक ही है तो "Business / pickup address is the same" टिक करें।', '"Save & continue" दबाएँ।']),
      important: t(['PAN and GSTIN are entered in the next step (KYC).', 'After approval, address, PIN and delivery area can only be changed by the Utsav Ghar team.'], ['PAN और GSTIN अगले चरण (KYC) में भरे जाते हैं।', 'मंज़ूरी के बाद पता, PIN और डिलीवरी एरिया केवल Utsav Ghar टीम बदल सकती है।']),
      mistakes: t(['Legal name different from PAN/GST', 'Website without https://'], ['PAN/GST से अलग कानूनी नाम', 'https:// के बिना वेबसाइट']),
    },
    {
      id: 'kyc', title: t('KYC Information', 'KYC जानकारी'), shot: 'd_kyc',
      callouts: [
        ['label:PAN', t('PAN (required)', 'PAN (ज़रूरी)')],
        ['label:GSTIN', t('GSTIN (if registered) — must contain the same PAN', 'GSTIN (अगर रजिस्टर्ड) — उसमें वही PAN होना चाहिए')],
        ['text:Bank account for payments', t('Bank account for payments', 'भुगतान के लिए बैंक खाता')],
        ['label:Re-enter account number', t('Re-enter account number (paste is blocked)', 'खाता नंबर दोबारा लिखें (पेस्ट बंद है)')],
        ['label:IFSC', t('IFSC', 'IFSC')],
      ],
      what: t('Onboarding step 2 — "Tax, registration & bank".', 'ऑनबोर्डिंग चरण 2 — "Tax, registration & bank"।'),
      why: t('KYC helps us verify that the dealer is a genuine business/person, pay you into the right account and keep the compliance records the law requires.', 'KYC से हम जाँचते हैं कि डीलर असली बिज़नेस/व्यक्ति है, सही खाते में भुगतान करते हैं और कानून के ज़रूरी रिकॉर्ड रखते हैं।'),
      can: t(['PAN (required), GSTIN (if registered)', 'CIN / LLPIN (required for companies and LLPs)', 'TAN, registration no., Udyam, trade licence (optional)', 'Bank name, account holder, account number (twice), IFSC, branch'], ['PAN (ज़रूरी), GSTIN (अगर रजिस्टर्ड)', 'CIN / LLPIN (कंपनी और LLP के लिए ज़रूरी)', 'TAN, रजिस्ट्रेशन नं., Udyam, ट्रेड लाइसेंस (वैकल्पिक)', 'बैंक नाम, खाताधारक, खाता नंबर (दो बार), IFSC, ब्रांच']),
      steps: t(['Open step 2.', 'Enter PAN (e.g. ABCDE1234F) and GSTIN if you have one.', 'Enter bank details exactly as on the cheque.', 'Tap "Save & continue".'], ['चरण 2 खोलें।', 'PAN (जैसे ABCDE1234F) और GSTIN हो तो भरें।', 'बैंक विवरण चेक के अनुसार बिल्कुल सही भरें।', '"Save & continue" दबाएँ।']),
      after: t('The account shows as "Saved account: XXXX XXXX 1234". To change it later, fill the account fields again.', 'खाता "Saved account: XXXX XXXX 1234" दिखता है। बाद में बदलना हो तो खाता फ़ील्ड दोबारा भरें।'),
      important: t(['🔒 Bank details are encrypted and seen only by our verification team.', 'Account holder name must match the business or proprietor.'], ['🔒 बैंक विवरण एन्क्रिप्टेड हैं और केवल हमारी सत्यापन टीम देखती है।', 'खाताधारक का नाम बिज़नेस या प्रोपराइटर से मेल खाना चाहिए।']),
      mistakes: t(['GSTIN that does not contain your PAN', 'Wrong IFSC (11 characters, 5th is zero)'], ['ऐसा GSTIN जिसमें आपका PAN न हो', 'गलत IFSC (11 अक्षर, 5वाँ शून्य)']),
    },
    {
      id: 'documents', title: t('Document Upload', 'दस्तावेज़ अपलोड'), shot: 'd_docs',
      callouts: [
        ['css:.dl-doctable', t('Checklist: document · Required / If applicable · status', 'चेकलिस्ट: दस्तावेज़ · ज़रूरी / लागू हो तो · स्टेटस')],
        ['text:Upload Document', t('Upload Document (PDF, JPG or PNG, up to 5 MB)', 'Upload Document (PDF, JPG या PNG, 5 MB तक)')],
      ],
      what: t('Onboarding step 3 — "Dealer Documents".', 'ऑनबोर्डिंग चरण 3 — "Dealer Documents"।'),
      why: t('Documents prove the details you entered, so we can verify you and keep compliance records.', 'दस्तावेज़ आपकी दी गई जानकारी का प्रमाण हैं, ताकि हम सत्यापन कर सकें और अनुपालन रिकॉर्ड रख सकें।'),
      can: t(['Every dealer (Required): PAN card, business address proof, ID of owner/authorised signatory, cancelled cheque or bank statement', 'GST certificate — required if you entered a GSTIN', 'Partnership: partnership deed + authorisation letter', 'LLP / company: registration certificate + authorisation letter / board resolution', 'If applicable: Udyam, trade/shop licence (with expiry date), other'], ['हर डीलर (ज़रूरी): PAN कार्ड, बिज़नेस पते का प्रमाण, मालिक/अधिकृत हस्ताक्षरकर्ता की ID, कैंसल चेक या बैंक स्टेटमेंट', 'GST प्रमाणपत्र — GSTIN डाला हो तो ज़रूरी', 'पार्टनरशिप: पार्टनरशिप डीड + अधिकार पत्र', 'LLP / कंपनी: रजिस्ट्रेशन प्रमाणपत्र + अधिकार पत्र / बोर्ड प्रस्ताव', 'लागू हो तो: Udyam, ट्रेड/दुकान लाइसेंस (समाप्ति तारीख के साथ), अन्य']),
      steps: t(['Open step 3.', 'For each row tap "Upload Document" and choose a clear PDF/photo.', 'Enter the document number if asked (and expiry date for a licence).', 'When all required ones are uploaded, tap "Continue: read the Dealer Agreement →".'], ['चरण 3 खोलें।', 'हर पंक्ति में "Upload Document" दबाकर साफ़ PDF/फ़ोटो चुनें।', 'माँगा जाए तो दस्तावेज़ नंबर डालें (लाइसेंस के लिए समाप्ति तारीख)।', 'सारे ज़रूरी दस्तावेज़ अपलोड होने पर "Continue: read the Dealer Agreement →" दबाएँ।']),
      statuses: STATUS.document,
      important: t(['Expired documents are not accepted.', 'After you sign, uploaded documents are kept on record — upload a newer file instead of removing.'], ['समाप्त दस्तावेज़ स्वीकार नहीं होते।', 'साइन करने के बाद अपलोड दस्तावेज़ रिकॉर्ड में रहते हैं — हटाने की जगह नई फ़ाइल अपलोड करें।']),
      mistakes: t(['Blurred or cut photos', 'Name on the document does not match the business', 'Uploading the wrong document in a row'], ['धुंधली या कटी फ़ोटो', 'दस्तावेज़ का नाम बिज़नेस से मेल न खाना', 'किसी पंक्ति में गलत दस्तावेज़ अपलोड करना']),
    },
    {
      id: 'verification', title: t('Document Verification', 'दस्तावेज़ सत्यापन'), shot: 'd_docs2',
      callouts: [
        ['css:.dl-doctable', t('Status of each document: Pending → Uploaded ✓ · Under review → Approved / Rejected (with reason and "Upload again")', 'हर दस्तावेज़ का स्टेटस: Pending → Uploaded ✓ · Under review → Approved / Rejected (कारण और "Upload again" के साथ)')],
        ['text:Continue: read the Dealer Agreement', t('Continue when all required documents are uploaded', 'सारे ज़रूरी दस्तावेज़ अपलोड होने पर आगे बढ़ें')],
      ],
      what: t('How our team checks your documents, and how you see the result in the documents checklist.', 'हमारी टीम आपके दस्तावेज़ कैसे जाँचती है, और आप दस्तावेज़ चेकलिस्ट में नतीजा कैसे देखते हैं।'),
      why: t('Verification protects customers and the marketplace from fake sellers and makes sure payments reach the right business.', 'सत्यापन ग्राहकों और मार्केटप्लेस को नकली विक्रेताओं से बचाता है और भुगतान सही बिज़नेस तक पहुँचाता है।'),
      steps: t(['After signing, wait for the review (usually within 2 working days).', 'If a document is Rejected, read the reason.', 'Tap "Upload again" and send a correct file.'], ['साइन करने के बाद समीक्षा का इंतज़ार करें (आम तौर पर 2 कार्य दिवस)।', 'दस्तावेज़ अस्वीकार हो तो कारण पढ़ें।', '"Upload again" दबाकर सही फ़ाइल भेजें।']),
      statuses: STATUS.document,
      after: t('When every required document is Approved and your agreement is signed, the team can approve your account.', 'जब हर ज़रूरी दस्तावेज़ Approved हो और एग्रीमेंट साइन हो, तब टीम आपका अकाउंट मंज़ूर कर सकती है।'),
    },
    {
      id: 'agreement', title: t('Dealer Agreement', 'डीलर एग्रीमेंट'), shot: 'd_agreement',
      callouts: [
        ['text:Download PDF', t('⬇️ Download PDF', '⬇️ PDF डाउनलोड')],
        ['text:Print', t('🖨️ Print', '🖨️ प्रिंट')],
        ['css:.lg-mode', t('Simple explanation / Full legal terms', 'आसान भाषा / पूरी कानूनी शर्तें')],
        ['text:I have read it', t('I have read it — continue to sign →', 'मैंने पढ़ लिया — साइन करने के लिए आगे →')],
      ],
      what: t('Onboarding step 4 — read the Dealer Agreement (and the Dealer Terms & Conditions, signed together).', 'ऑनबोर्डिंग चरण 4 — Dealer Agreement पढ़ें (और Dealer Terms & Conditions, जो साथ में साइन होते हैं)।'),
      why: t('This page explains the business relationship between you and Utsav Ghar: your responsibilities, product rules, payments, returns, customer data and other marketplace requirements, including your commercial schedule.', 'यह पेज आपके और Utsav Ghar के बिज़नेस संबंध को समझाता है: आपकी ज़िम्मेदारियाँ, प्रोडक्ट नियम, भुगतान, रिटर्न, ग्राहक डेटा और बाकी मार्केटप्लेस नियम, आपके कमर्शियल शेड्यूल सहित।'),
      can: t(['"Simple explanation" — short "What this means" lines', '"Full legal terms" — the complete binding text', '"Download PDF" — a copy with your details filled in', '"Print"', '"I have read it — continue to sign"'], ['"Simple explanation" — छोटी "What this means" लाइनें', '"Full legal terms" — पूरा बाध्यकारी पाठ', '"Download PDF" — आपकी जानकारी भरी कॉपी', '"Print"', '"I have read it — continue to sign"']),
      steps: t(['Finish steps 1–3 first.', 'Read the simple explanation, then the full terms.', 'Download or print a copy if you want.', 'Tap "I have read it — continue to sign →".'], ['पहले चरण 1–3 पूरे करें।', 'पहले आसान भाषा, फिर पूरी शर्तें पढ़ें।', 'चाहें तो कॉपी डाउनलोड या प्रिंट करें।', '"I have read it — continue to sign →" दबाएँ।']),
      important: t(['The simple explanation helps understanding; the Full legal terms are what you sign.'], ['आसान भाषा समझने के लिए है; आप "Full legal terms" पर ही साइन करते हैं।']),
    },
    {
      id: 'signature', title: t('Digital Signature', 'डिजिटल सिग्नेचर'), shot: 'd_sign',
      callouts: [
        ['css:.dl-signinfo', t('Dealer name, business name, agreement version and date', 'डीलर नाम, बिज़नेस नाम, एग्रीमेंट वर्ज़न और तारीख')],
        ['text:Please confirm', t('4 required confirmations', '4 ज़रूरी पुष्टियाँ')],
        ['label:Type your full name', t('Full name and capacity (Proprietor, Director…)', 'पूरा नाम और पद (Proprietor, Director…)')],
        ['css:canvas', t('Draw your signature', 'अपना सिग्नेचर बनाएँ')],
        ['label:6-digit code', t('Verify with mobile OTP → enter the 6-digit code', 'मोबाइल OTP से पुष्टि → 6 अंकों का कोड डालें')],
        ['text:Sign & Submit Agreement', t('✍️ Sign & Submit Agreement', '✍️ साइन करें और एग्रीमेंट जमा करें')],
      ],
      what: t('Onboarding step 5 — "Sign Dealer Agreement".', 'ऑनबोर्डिंग चरण 5 — "Sign Dealer Agreement"।'),
      why: t('Digital acceptance records your agreement to the terms and creates a traceable record of which agreement version was accepted, by whom, when, from which device and with which OTP.', 'डिजिटल स्वीकृति शर्तों पर आपकी सहमति दर्ज करती है और ट्रेस किया जा सकने वाला रिकॉर्ड बनाती है — कौन सा वर्ज़न, किसने, कब, किस डिवाइस से और किस OTP से।'),
      steps: t(['Check Dealer name, Business name, Agreement version and date.', 'Tick the 4 boxes under "Please confirm".', 'Type your full name and capacity; tick "I am authorised to sign".', 'Draw your signature with finger or mouse ("Clear" to redo).', 'Tap "Verify with mobile OTP" and enter the 6-digit code sent to your mobile/email.', 'Tap "✍️ Sign & Submit Agreement".'],
        ['डीलर नाम, बिज़नेस नाम, एग्रीमेंट वर्ज़न और तारीख जाँचें।', '"Please confirm" के 4 बॉक्स टिक करें।', 'पूरा नाम और पद लिखें; "I am authorised to sign" टिक करें।', 'उंगली या माउस से सिग्नेचर बनाएँ (दोबारा के लिए "Clear")।', '"Verify with mobile OTP" दबाएँ और मोबाइल/ईमेल पर आया 6 अंकों का कोड डालें।', '"✍️ Sign & Submit Agreement" दबाएँ।']),
      after: t('"✅ Agreement signed". Download the signed "DEALER AGREEMENT" PDF any time from Legal & Agreements. Status becomes Under review.', '"✅ Agreement signed"। साइन किया "DEALER AGREEMENT" PDF कभी भी Legal & Agreements से डाउनलोड करें। स्टेटस Under review हो जाता है।'),
      important: t(['The OTP is valid for 10 minutes, 5 tries; you can ask for a new one after 30 seconds.', 'Signed electronically under the IT Act, 2000. Date, time, IP address, device and OTP reference are recorded.', 'If a new agreement version or new commercial terms are published, you will be asked to sign again.'], ['OTP 10 मिनट तक मान्य, 5 कोशिशें; 30 सेकंड बाद नया माँग सकते हैं।', 'IT Act, 2000 के तहत इलेक्ट्रॉनिक हस्ताक्षर। तारीख, समय, IP पता, डिवाइस और OTP रेफ़रेंस दर्ज होते हैं।', 'नया एग्रीमेंट वर्ज़न या नई कमर्शियल शर्तें आने पर दोबारा साइन करना होगा।']),
      mistakes: t(['Typing a short name or a nickname', 'Waiting more than 10 minutes before entering the OTP'], ['छोटा नाम या उपनाम लिखना', 'OTP डालने में 10 मिनट से ज़्यादा लगाना']),
    },
    {
      id: 'approval', title: t('Dealer Approval', 'डीलर अप्रूवल'), shot: 'd_review',
      callouts: [
        ['css:.lg-steps', t('The 7 onboarding steps with progress', '7 ऑनबोर्डिंग चरण और प्रगति')],
        ['text:Status', t('Your current status', 'आपका मौजूदा स्टेटस')],
      ],
      what: t('The "Dealer onboarding" page shows where you are: Admin verification and Dealer approval are the last two steps.', '"Dealer onboarding" पेज बताता है आप कहाँ हैं: Admin verification और Dealer approval आखिरी दो चरण हैं।'),
      why: t('Approval is the final check before you can receive orders and add products.', 'ऑर्डर लेने और प्रोडक्ट जोड़ने से पहले मंज़ूरी अंतिम जाँच है।'),
      flow: 'dealer_approval',
      statuses: STATUS.onboarding,
      after: t('When approved you get a message ("Your dealer account is approved…"), and the full app opens: Dashboard, Orders, Products, Profile.', 'मंज़ूरी पर संदेश आता है ("Your dealer account is approved…") और पूरा ऐप खुलता है: Dashboard, Orders, Products, Profile।'),
      important: t(['Dealers added by the Utsav Ghar team get 14 days (grace period) to finish onboarding while still receiving orders. A banner shows the days left.', 'Self-registered dealers receive orders only after approval.'], ['Utsav Ghar टीम द्वारा जोड़े गए डीलरों को ऑनबोर्डिंग पूरी करने के लिए 14 दिन (ग्रेस पीरियड) मिलते हैं, तब तक ऑर्डर आते रहते हैं। बैनर में बचे दिन दिखते हैं।', 'खुद रजिस्टर किए डीलरों को मंज़ूरी के बाद ही ऑर्डर मिलते हैं।']),
    },
    {
      id: 'products', title: t('Product Management', 'प्रोडक्ट प्रबंधन'), shot: 'd_products',
      callouts: [
        ['text:Add a product', t('＋ Add a product', '＋ प्रोडक्ट जोड़ें')],
        ['css:.dl-pcard .dl-pill, .dl-prod .pill, .dl-pill', t('Product status', 'प्रोडक्ट स्टेटस')],
        ['css:.dl-stock', t('Stock box — "Available" + Save', 'स्टॉक बॉक्स — "Available" + Save')],
      ],
      what: t('"My products" — every product you supply.', '"My products" — आपके द्वारा सप्लाई किए सारे प्रोडक्ट।'),
      why: t('Customers can buy only products that are approved and live; this page shows their review status and stock.', 'ग्राहक केवल मंज़ूर और लाइव प्रोडक्ट खरीद सकते हैं; यह पेज उनका रिव्यू स्टेटस और स्टॉक दिखाता है।'),
      can: t(['Add products', 'Edit a product (re-reviewed)', 'Update available stock (instant)', 'Read team notes'], ['प्रोडक्ट जोड़ें', 'प्रोडक्ट बदलें (दोबारा रिव्यू)', 'उपलब्ध स्टॉक अपडेट करें (तुरंत)', 'टीम के नोट पढ़ें']),
      statuses: STATUS.product,
      planned: t(['Deleting a product, bulk upload (CSV) and showing the team-agreed price are Planned Features.'], ['प्रोडक्ट डिलीट, बल्क अपलोड (CSV) और टीम द्वारा तय कीमत दिखाना Planned Features हैं।']),
    },
    {
      id: 'addproduct', title: t('Add Product', 'प्रोडक्ट जोड़ें'), shot: 'd_addproduct',
      callouts: [
        ['text:Photos', t('📷 Photos — 1 to 6 (JPG/PNG/WebP, 5 MB each)', '📷 फ़ोटो — 1 से 6 (JPG/PNG/WebP, हर 5 MB)')],
        ['label:Product name', t('Product name, category, summary, description', 'प्रोडक्ट नाम, कैटेगरी, सारांश, विवरण')],
        ['text:Your price & stock', t('💰 Your price & stock', '💰 आपकी कीमत और स्टॉक')],
        ['text:Send for review', t('Send for review', 'रिव्यू के लिए भेजें')],
      ],
      what: t('"Add a product" form.', '"Add a product" फ़ॉर्म।'),
      why: t('You enter the product information because customers buy from what they see. Clear photos and true details reduce returns and complaints.', 'आप प्रोडक्ट की जानकारी इसलिए भरते हैं क्योंकि ग्राहक वही देखकर खरीदते हैं। साफ़ फ़ोटो और सही विवरण से रिटर्न और शिकायतें कम होती हैं।'),
      steps: t(['Tap "＋ Add a product".', 'Add 1–6 clear photos (plain background, front + side + in use).', 'Fill Product name, Category, One-line summary and Full description (20+ characters).', 'Add details: material, dimensions, weight, what\'s included, colour, care, country of origin.', 'Enter Your price per piece and Quantity available.', 'Tap "Send for review".'], ['"＋ Add a product" दबाएँ।', '1–6 साफ़ फ़ोटो जोड़ें (सादा बैकग्राउंड, आगे + साइड + उपयोग में)।', 'प्रोडक्ट नाम, कैटेगरी, एक लाइन सारांश और पूरा विवरण (20+ अक्षर) भरें।', 'विवरण जोड़ें: मटेरियल, माप, वज़न, क्या शामिल है, रंग, देखभाल, मूल देश।', 'प्रति पीस अपनी कीमत और उपलब्ध मात्रा भरें।', '"Send for review" दबाएँ।']),
      after: t('"📨 Sent for review". The team checks it and tells you on WhatsApp/email. Status: Under review → Approved / Changes needed / Not accepted.', '"📨 Sent for review"। टीम जाँचकर WhatsApp/ईमेल पर बताती है। स्टेटस: Under review → Approved / Changes needed / Not accepted।'),
      statuses: STATUS.product,
      important: t(['Up to 50 products can wait for review at once.', 'Editing an approved product sends it for review again; stock changes are instant.'], ['एक साथ 50 तक प्रोडक्ट रिव्यू में रह सकते हैं।', 'मंज़ूर प्रोडक्ट बदलने पर फिर रिव्यू होता है; स्टॉक बदलाव तुरंत होता है।']),
      mistakes: t(['Photos with watermarks, phone numbers or other sellers\' logos', 'Wrong category', 'Missing size or material'], ['वॉटरमार्क, फ़ोन नंबर या दूसरे विक्रेताओं के लोगो वाली फ़ोटो', 'गलत कैटेगरी', 'माप या मटेरियल न लिखना']),
    },
    {
      id: 'pricing', title: t('Product Pricing', 'प्रोडक्ट प्राइसिंग'), shot: 'd_pricing',
      callouts: [
        ['label:Your price per piece', t('Your price per piece (₹)', 'प्रति पीस आपकी कीमत (₹)')],
        ['text:This is the price Utsav Ghar pays you', t('"This is the price Utsav Ghar pays you… The store sets the price customers pay."', '"This is the price Utsav Ghar pays you… The store sets the price customers pay."')],
      ],
      what: t('The price section of the product form.', 'प्रोडक्ट फ़ॉर्म का कीमत वाला हिस्सा।'),
      why: t('There are two separate prices: your Dealer Price and the Platform Selling Price.', 'दो अलग कीमतें होती हैं: आपका Dealer Price और Platform Selling Price।'),
      flow: 'price_split',
      important: t(['The dealer only sees pricing information the business has decided to show to the dealer. Internal profit calculations and confidential platform pricing remain restricted.'], ['डीलर को केवल वही कीमत की जानकारी दिखती है जो बिज़नेस ने दिखाना तय किया है। आंतरिक मुनाफ़े की गणना और गोपनीय प्लेटफ़ॉर्म प्राइसिंग प्रतिबंधित रहती है।']),
    },
    {
      id: 'dealerprice', title: t('Dealer Price', 'डीलर प्राइस'),
      what: t('Your Dealer Price is the amount Utsav Ghar pays you for each piece you supply and deliver.', 'Dealer Price वह रकम है जो Utsav Ghar आपको हर सप्लाई और डिलीवर किए पीस के लिए देता है।'),
      why: t('It is the basis of your earnings: Dashboard earnings = dealer price × quantity of delivered orders.', 'यही आपकी कमाई का आधार है: Dashboard कमाई = डिलीवर ऑर्डर की मात्रा × डीलर प्राइस।'),
      can: t(['Set it when you add a product', 'Change it by editing the product (reviewed again)', 'See it on each product card ("Your price ₹…") and in the stock table'], ['प्रोडक्ट जोड़ते समय तय करें', 'प्रोडक्ट बदलकर बदलें (फिर रिव्यू होगा)', 'हर प्रोडक्ट कार्ड ("Your price ₹…") और स्टॉक टेबल में देखें']),
      important: t(['Quote an all-inclusive price per piece (packing included, unless your commercial schedule says otherwise).', 'In the Supply model you are paid the dealer price × quantity delivered with no commission. In the Commission model, the commission and fees in your schedule apply.'], ['प्रति पीस सब-शामिल कीमत बताएँ (पैकिंग शामिल, जब तक कमर्शियल शेड्यूल कुछ और न कहे)।', 'Supply मॉडल में आपको डिलीवर मात्रा × डीलर प्राइस मिलता है, कोई कमीशन नहीं। Commission मॉडल में आपके शेड्यूल का कमीशन और फ़ीस लगती है।']),
    },
    {
      id: 'platformprice', title: t('Platform Selling Price', 'प्लेटफ़ॉर्म सेलिंग प्राइस'),
      what: t('The price customers pay on the Utsav Ghar store.', 'Utsav Ghar स्टोर पर ग्राहक जो कीमत देते हैं।'),
      why: t('Utsav Ghar sets it after adding delivery, packaging, payment fees, taxes and its own costs. It is separate from your dealer price.', 'Utsav Ghar डिलीवरी, पैकिंग, पेमेंट फ़ीस, टैक्स और अपनी लागत जोड़कर इसे तय करता है। यह आपके डीलर प्राइस से अलग है।'),
      flow: 'price_split',
      important: t(['The customer selling price, MRP and margin are not shown in the dealer app by design.', 'You cannot change the selling price; contact the team if you think it is wrong for your product.'], ['ग्राहक कीमत, MRP और मार्जिन जानबूझकर डीलर ऐप में नहीं दिखाए जाते।', 'आप सेलिंग प्राइस नहीं बदल सकते; आपके प्रोडक्ट के लिए गलत लगे तो टीम से संपर्क करें।']),
    },
    {
      id: 'inventory', title: t('Inventory', 'इन्वेंटरी'), shot: 'd_stock',
      callouts: [
        ['css:.dl-stock input', t('Available — type the pieces you have', 'Available — आपके पास के पीस लिखें')],
        ['css:.dl-stock button', t('Save — updates the store immediately', 'Save — स्टोर तुरंत अपडेट होता है')],
      ],
      what: t('The stock box on each product card.', 'हर प्रोडक्ट कार्ड पर स्टॉक बॉक्स।'),
      why: t('Correct stock means customers order only what you can supply; wrong stock causes cancellations.', 'सही स्टॉक से ग्राहक वही ऑर्डर करते हैं जो आप दे सकते हैं; गलत स्टॉक से कैंसलेशन होते हैं।'),
      can: t(['Available stock — pieces you can supply now (shown as "On the store now")', 'Reserved stock — pieces in orders placed but not yet sent out', 'Sold stock — pieces delivered', 'Out of stock — set 0 to stop orders for that product', 'Stock update — type the new number and Save'], ['उपलब्ध स्टॉक — अभी दे सकने वाले पीस ("On the store now")', 'रिज़र्व स्टॉक — ऐसे ऑर्डर के पीस जो हुए पर अभी भेजे नहीं गए', 'बिका स्टॉक — डिलीवर हुए पीस', 'स्टॉक खत्म — उस प्रोडक्ट के ऑर्डर रोकने के लिए 0 करें', 'स्टॉक अपडेट — नई संख्या लिखकर Save करें']),
      steps: t(['Open Products.', 'In the product card change "Available".', 'Tap "Save".'], ['Products खोलें।', 'प्रोडक्ट कार्ड में "Available" बदलें।', '"Save" दबाएँ।']),
      important: t(['Stock is taken off as soon as a customer places an order, so "On the store now" never sells what is already reserved.', 'Stock cannot be negative. When a customer cancels or a resaleable item is returned, the pieces come back automatically.'], ['ग्राहक के ऑर्डर करते ही स्टॉक घट जाता है, इसलिए "On the store now" पहले से रिज़र्व पीस दोबारा नहीं बेचता।', 'स्टॉक माइनस नहीं हो सकता। ग्राहक के कैंसल करने या बिकने लायक आइटम लौटने पर पीस अपने-आप वापस आते हैं।']),
    },
    {
      id: 'stock', title: t('Stock Management', 'स्टॉक प्रबंधन'), shot: 'd_stockalerts',
      callouts: [
        ['text:Stock alerts', t('Stock alerts: 🚫 out of stock, ⚠️ only N left', 'स्टॉक अलर्ट: 🚫 खत्म, ⚠️ केवल N बचे')],
        ['text:Update stock', t('Update stock →', 'स्टॉक अपडेट करें →')],
        ['text:Stock in vs stock out', t('Stock in vs stock out', 'स्टॉक आया बनाम गया')],
      ],
      what: t('Dashboard cards that watch your stock.', 'Dashboard के कार्ड जो आपका स्टॉक देखते हैं।'),
      why: t('To refill before you run out and to see how fast stock moves.', 'खत्म होने से पहले भरने और यह देखने के लिए कि स्टॉक कितनी तेज़ी से जाता है।'),
      steps: t(['Check "Stock alerts" on the Dashboard every day.', 'Tap "Update stock →" and save the new quantity.', 'Expand "All products stock" to see In stock, Sold and Your price per product.'], ['रोज़ Dashboard पर "Stock alerts" देखें।', '"Update stock →" दबाकर नई मात्रा सेव करें।', 'हर प्रोडक्ट का In stock, Sold और Your price देखने के लिए "All products stock" खोलें।']),
      important: t(['You also get notifications for out-of-stock and low-stock products.'], ['स्टॉक खत्म और कम स्टॉक की सूचनाएँ भी मिलती हैं।']),
    },
    {
      id: 'orders', title: t('Orders', 'ऑर्डर'), shot: 'd_orders',
      callouts: [
        ['css:.dl-stats', t('Counters: New, In progress, Delivered today', 'गिनती: New, In progress, आज डिलीवर')],
        ['css:.dl-tabs', t('Tabs: New · In progress · Done', 'टैब: New · In progress · Done')],
        ['css:.dl-list > *', t('Order card: number, status, items, city & PIN, time', 'ऑर्डर कार्ड: नंबर, स्टेटस, आइटम, शहर और PIN, समय')],
      ],
      what: t('The Orders list.', 'Orders लिस्ट।'),
      why: t('One place for every order sent to you, so none is missed.', 'आपको भेजे हर ऑर्डर की एक जगह, ताकि कोई न छूटे।'),
      can: t(['See new orders waiting for you ("⏰ Waiting for you")', 'See orders in progress and done (delivered or cancelled)', 'Refresh the list'], ['आपका इंतज़ार कर रहे नए ऑर्डर देखें ("⏰ Waiting for you")', 'चल रहे और पूरे (डिलीवर या कैंसल) ऑर्डर देखें', 'लिस्ट रिफ़्रेश करें']),
      statuses: STATUS.dealerOrder,
      important: t(['The app checks for new orders every 30 seconds and beeps/vibrates while open. Turn on alerts when asked.', 'You must accept within the time set by Utsav Ghar (usually 2 hours); otherwise the order may move to another dealer.'], ['ऐप हर 30 सेकंड में नए ऑर्डर देखता है और खुले रहने पर बीप/वाइब्रेट करता है। माँगे जाने पर अलर्ट चालू करें।', 'Utsav Ghar के तय समय (आम तौर पर 2 घंटे) में स्वीकार करें; नहीं तो ऑर्डर दूसरे डीलर को जा सकता है।']),
      planned: t(['Search and date filters in the order list are Planned Features.'], ['ऑर्डर लिस्ट में सर्च और तारीख फ़िल्टर Planned Features हैं।']),
    },
    {
      id: 'processing', title: t('Order Processing', 'ऑर्डर प्रोसेसिंग'), shot: 'd_order_new',
      callouts: [
        ['text:Accept order', t('👍 Accept order', '👍 ऑर्डर स्वीकार करें')],
        ['text:Can\'t fulfil', t('Can\'t fulfil — choose a reason', 'नहीं कर सकते — कारण चुनें')],
        ['has:Full address and phone appear', t('Customer details appear after you accept', 'स्वीकार के बाद ग्राहक का विवरण दिखता है')],
      ],
      shot2: 'd_order_pack',
      callouts2: [
        ['css:label.dl-check', t('Tick each item as you put it in the box', 'डिब्बे में रखते समय हर आइटम टिक करें')],
        ['text:Tick all items', t('"Tick all items (x/y)" becomes "📦 Mark as packed"', '"Tick all items (x/y)" फिर "📦 Mark as packed" बनता है')],
      ],
      what: t('The order page: accept, pack and get ready.', 'ऑर्डर पेज: स्वीकार करें, पैक करें और तैयार करें।'),
      why: t('Each step updates the customer\'s timeline automatically, so they always know where their order is.', 'हर चरण ग्राहक की टाइमलाइन अपने-आप अपडेट करता है, ताकि उन्हें हमेशा पता रहे ऑर्डर कहाँ है।'),
      flow: 'dealer_order',
      steps: t(['Open the new order.', 'Check items. Tap "👍 Accept order" (or "Can\'t fulfil" → reason → "Reject order").', 'Tick every item while packing; tap "📦 Mark as packed".', 'Tap "🏷️ Ready for delivery" and "🖨️ Print packing slip".'], ['नया ऑर्डर खोलें।', 'आइटम जाँचें। "👍 Accept order" दबाएँ (या "Can\'t fulfil" → कारण → "Reject order")।', 'पैक करते समय हर आइटम टिक करें; "📦 Mark as packed" दबाएँ।', '"🏷️ Ready for delivery" और "🖨️ Print packing slip" दबाएँ।']),
      statuses: STATUS.dealerOrder,
      important: t(['Reject reasons: item out of stock, cannot deliver to this PIN, shop closed, too many orders, other. Rejected orders go to another dealer.', 'You can reject only before packing.'], ['अस्वीकार के कारण: स्टॉक खत्म, इस PIN पर डिलीवरी नहीं, दुकान बंद, बहुत ऑर्डर, अन्य। अस्वीकार ऑर्डर दूसरे डीलर को जाते हैं।', 'पैक करने से पहले ही अस्वीकार कर सकते हैं।']),
    },
    {
      id: 'shipping', title: t('Shipping', 'शिपिंग'), shot: 'd_handover',
      callouts: [
        ['text:Our delivery person', t('🛵 Our delivery person — name and mobile', '🛵 हमारा डिलीवरी व्यक्ति — नाम और मोबाइल')],
        ['text:Courier', t('📮 Courier — company, AWB / tracking number, link', '📮 कूरियर — कंपनी, AWB / ट्रैकिंग नंबर, लिंक')],
        ['text:Send out for delivery', t('Send out for delivery', 'डिलीवरी के लिए भेजें')],
      ],
      what: t('"Hand over for delivery" on a Ready order.', 'Ready ऑर्डर पर "Hand over for delivery"।'),
      why: t('So the customer gets the right tracking information and the delivery can be proved.', 'ताकि ग्राहक को सही ट्रैकिंग जानकारी मिले और डिलीवरी का प्रमाण हो।'),
      steps: t(['Own delivery: choose "🛵 Our delivery person", enter name and 10-digit mobile → "Send out for delivery". At the door, ask the customer\'s 4-digit code, enter it → "✅ Delivered".', 'Courier: choose "📮 Courier", pick the company, enter the AWB / tracking number (and link) → "Handed to courier". Later add updates (In transit, Out for delivery, Attempt failed, Delivered) from the courier\'s tracking page.'],
        ['खुद डिलीवरी: "🛵 Our delivery person" चुनें, नाम और 10 अंकों का मोबाइल डालें → "Send out for delivery"। दरवाज़े पर ग्राहक से 4 अंकों का कोड पूछें, डालें → "✅ Delivered"।', 'कूरियर: "📮 Courier" चुनें, कंपनी चुनें, AWB / ट्रैकिंग नंबर (और लिंक) डालें → "Handed to courier"। बाद में कूरियर की ट्रैकिंग पेज से अपडेट डालें (In transit, Out for delivery, Attempt failed, Delivered)।']),
      important: t(['Every order is prepaid — "do not collect cash".', 'After 5 wrong delivery codes, ask the store to confirm delivery.'], ['हर ऑर्डर प्रीपेड है — "नकद न लें"।', '5 गलत डिलीवरी कोड के बाद स्टोर से डिलीवरी पक्की करवाएँ।']),
      planned: t(['Automatic courier tracking (updates without typing) is a Planned Feature.'], ['अपने-आप कूरियर ट्रैकिंग (बिना लिखे अपडेट) Planned Feature है।']),
    },
    {
      id: 'returns', title: t('Returns', 'रिटर्न'),
      what: t('Customer returns of orders you delivered. They appear on that order in your Orders list ("↩️ Return RET-…").', 'आपके डिलीवर किए ऑर्डर के ग्राहक रिटर्न। ये Orders लिस्ट में उसी ऑर्डर पर दिखते हैं ("↩️ Return RET-…")।'),
      why: t('Returns follow the Dealer Return & Refund Policy and the return window in your commercial terms.', 'रिटर्न Dealer Return & Refund Policy और आपकी कमर्शियल शर्तों की रिटर्न अवधि के अनुसार होते हैं।'),
      steps: t(['The customer requests a return on the order page (with photos for damaged/wrong items).', 'Utsav Ghar approves or rejects it. When approved, you get a message and the order shows "Return … approved — our team will arrange the pickup".', 'When the item comes back, resaleable pieces go back to stock.', 'The returned value is deducted in your next settlement (see Payments & settlement).'], ['ग्राहक ऑर्डर पेज पर रिटर्न माँगता है (टूटे/गलत आइटम के लिए फ़ोटो के साथ)।', 'Utsav Ghar मंज़ूर या अस्वीकार करता है। मंज़ूर होने पर आपको संदेश मिलता है और ऑर्डर पर "Return … approved — our team will arrange the pickup" दिखता है।', 'सामान लौटने पर बिकने लायक पीस स्टॉक में वापस जाते हैं।', 'लौटाई गई राशि आपके अगले सेटलमेंट में घटती है (Payments & settlement देखें)।']),
      statuses: STATUS.returns,
      important: t(['Wrong, defective or poorly packed items are the dealer\'s responsibility.', 'If the store cancels an order you already packed, keep it aside — the team will contact you.', 'You never see the customer\'s payment or refund amount — only the items and the status.'], ['गलत, खराब या खराब पैक आइटम डीलर की ज़िम्मेदारी है।', 'अगर स्टोर आपके पैक किए ऑर्डर को कैंसल करे, उसे अलग रखें — टीम संपर्क करेगी।', 'आपको ग्राहक का भुगतान या रिफ़ंड राशि नहीं दिखती — केवल आइटम और स्टेटस।']),
    },
    {
      id: 'refunds', title: t('Refunds', 'रिफ़ंड'),
      what: t('Refunds to customers are paid by Utsav Ghar.', 'ग्राहकों को रिफ़ंड Utsav Ghar देता है।'),
      why: t('Customers pay Utsav Ghar, so Utsav Ghar returns the money. For your orders, the returned pieces are deducted in your settlement at your dealer price (Supply model) or at the sale value (Commission model).', 'ग्राहक Utsav Ghar को भुगतान करते हैं, इसलिए Utsav Ghar ही पैसा लौटाता है। आपके ऑर्डर में लौटाए गए पीस आपके सेटलमेंट में डीलर प्राइस (Supply मॉडल) या बिक्री मूल्य (Commission मॉडल) पर घटते हैं।'),
      steps: t(['Open Payments & settlement.', 'Returns appear as "↩️ RET-…" lines with a minus amount.'], ['Payments & settlement खोलें।', 'रिटर्न "↩️ RET-…" लाइन में माइनस राशि के साथ दिखते हैं।']),
      important: t(['"Refund issues" count in your account health.', 'If returns are more than new sales, nothing is taken from your bank — the difference is carried to the next settlement.'], ['"Refund issues" आपकी अकाउंट हेल्थ में गिने जाते हैं।', 'अगर रिटर्न नई बिक्री से ज़्यादा हों तो बैंक से कुछ नहीं कटता — अंतर अगले सेटलमेंट में जाता है।']),
    },
    {
      id: 'payments', title: t('Dealer Payments', 'डीलर भुगतान'), shot: 'd_payments',
      callouts: [
        ['css:.dl-pay-net', t('Due to you now — estimate of your next settlement', 'अभी आपका बकाया — अगले सेटलमेंट का अनुमान')],
        ['css:.dl-kpis', t('Total paid, processing, total sales, returns, fees, adjustments', 'कुल भुगतान, प्रोसेसिंग, कुल बिक्री, रिटर्न, फ़ीस, समायोजन')],
        ['css:.dl-setl', t('Settlements with status, net amount and date — tap one for details and UTR', 'सेटलमेंट — स्टेटस, शुद्ध राशि और तारीख; विवरण और UTR के लिए दबाएँ')],
      ],
      what: t('"💰 Payments & settlement" (Profile → Payments, or "See payments →" on the Dashboard).', '"💰 Payments & settlement" (Profile → Payments, या Dashboard पर "See payments →")।'),
      why: t('This page lets you understand your completed sales, applicable deductions and settlement/payment status.', 'यह पेज आपकी पूरी बिक्री, लागू कटौतियाँ और सेटलमेंट/भुगतान स्टेटस समझने देता है।'),
      can: t(['Total Sales', 'Applicable Fees (Commission model only)', 'Returns', 'Adjustments (e.g. penalty or bonus)', 'Net Settlement', 'Payment Status', 'Settlement Date and bank UTR'], ['कुल बिक्री', 'लागू फ़ीस (केवल Commission मॉडल)', 'रिटर्न', 'समायोजन (जैसे पेनल्टी या बोनस)', 'शुद्ध सेटलमेंट', 'भुगतान स्टेटस', 'सेटलमेंट तारीख और बैंक UTR']),
      steps: t(['Open Profile → "💰 Payments & settlement".', 'Check "Due to you now" and "See orders" for what is not yet settled.', 'Tap a settlement to see each order, deductions and the UTR.'], ['Profile → "💰 Payments & settlement" खोलें।', 'जो अभी सेटल नहीं हुआ, उसके लिए "Due to you now" और "See orders" देखें।', 'हर ऑर्डर, कटौती और UTR देखने के लिए सेटलमेंट दबाएँ।']),
      statuses: STATUS.settlement,
      important: t(['Supply model: you are paid dealer price × quantity delivered; no commission.', 'An order is never paid twice, and a settlement is never made for zero or a negative amount.', 'The customer selling price and Utsav Ghar\'s margin are never shown.'], ['Supply मॉडल: आपको डीलर प्राइस × डिलीवर मात्रा मिलती है; कोई कमीशन नहीं।', 'कोई ऑर्डर दो बार नहीं चुकाया जाता, और शून्य या माइनस राशि का सेटलमेंट नहीं बनता।', 'ग्राहक कीमत और Utsav Ghar का मार्जिन कभी नहीं दिखता।']),
    },
    {
      id: 'settlement', title: t('Settlement', 'सेटलमेंट'), shot: 'd_commercial',
      callouts: [
        ['text:Commercial Terms', t('Commercial Terms — your model, settlement days, return window, penalties', 'Commercial Terms — आपका मॉडल, सेटलमेंट दिन, रिटर्न अवधि, पेनल्टी')],
      ],
      what: t('How settlements are made, and your Commercial Terms (Legal & Agreements → Documents → Commercial Terms).', 'सेटलमेंट कैसे बनते हैं, और आपकी Commercial Terms (Legal & Agreements → Documents → Commercial Terms)।'),
      why: t('They state how and when you are paid and what may be deducted.', 'इनमें लिखा है कि आपको कैसे और कब भुगतान होगा और क्या कट सकता है।'),
      can: t(['Model: Supply (dealer price × delivered quantity, no commission) or Commission (commission %, platform fee, payment fee)', 'Settlement: within N days after delivery, less refunds, returns or penalties due', 'Return window (days)', 'Late dispatch penalty', 'Logistics and taxes (TCS/TDS where required)'], ['मॉडल: Supply (डीलर प्राइस × डिलीवर मात्रा, कोई कमीशन नहीं) या Commission (कमीशन %, प्लेटफ़ॉर्म फ़ीस, पेमेंट फ़ीस)', 'सेटलमेंट: डिलीवरी के N दिन के अंदर, देय रिफ़ंड, रिटर्न या पेनल्टी घटाकर', 'रिटर्न अवधि (दिन)', 'देर से भेजने की पेनल्टी', 'लॉजिस्टिक्स और टैक्स (जहाँ ज़रूरी TCS/TDS)']),
      steps: t(['Utsav Ghar finance creates a settlement from your delivered orders (status "Processing").', 'They transfer the money to your verified bank account.', 'The settlement turns "Paid" with the UTR; you get a message.'], ['Utsav Ghar फ़ाइनेंस आपके डिलीवर ऑर्डर से सेटलमेंट बनाता है (स्टेटस "Processing")।', 'वे आपके सत्यापित बैंक खाते में पैसा भेजते हैं।', 'सेटलमेंट UTR के साथ "Paid" हो जाता है; आपको संदेश मिलता है।']),
      flow: 'settlement_flow',
      statuses: STATUS.settlement,
      important: t(['If Utsav Ghar changes your commercial terms, you must sign the agreement again before receiving new orders.', 'Keep your bank details correct in KYC — payments go only to the verified account.'], ['अगर Utsav Ghar आपकी कमर्शियल शर्तें बदले तो नए ऑर्डर से पहले एग्रीमेंट दोबारा साइन करना होगा।', 'KYC में बैंक विवरण सही रखें — भुगतान केवल सत्यापित खाते में जाता है।']),
    },
    {
      id: 'performance', title: t('Dealer Performance', 'डीलर प्रदर्शन'), shot: 'd_health',
      callouts: [
        ['text:Account health', t('Account health level', 'अकाउंट हेल्थ स्तर')],
        ['css:.dl-hlist', t('Measures: cancellation, late shipment, complaints, returns, refunds, quality, violations, document expiry, fraud', 'माप: कैंसलेशन, देर से शिपमेंट, शिकायतें, रिटर्न, रिफ़ंड, गुणवत्ता, उल्लंघन, दस्तावेज़ समाप्ति, धोखाधड़ी')],
      ],
      what: t('"Account health" in Profile → Legal & Agreements, plus the "Service" tile on the Dashboard.', 'Profile → Legal & Agreements में "Account health", और Dashboard पर "Service" टाइल।'),
      why: t('Customers need reliable delivery. These measures show where you are doing well and what to improve, as explained in the Dealer Performance & Account Health Policy.', 'ग्राहकों को भरोसेमंद डिलीवरी चाहिए। ये माप दिखाते हैं कि आप कहाँ अच्छा कर रहे हैं और क्या सुधारना है, जैसा Dealer Performance & Account Health Policy में बताया है।'),
      statuses: STATUS.health,
      important: t(['Rates are judged only after enough orders in the period (usually 90 days).', 'Restricted accounts may have new orders or listings paused.'], ['दर केवल अवधि में पर्याप्त ऑर्डर होने पर आँकी जाती है (आम तौर पर 90 दिन)।', 'Restricted अकाउंट के नए ऑर्डर या लिस्टिंग रोकी जा सकती हैं।']),
      mistakes: t(['Accepting orders you cannot fulfil', 'Late dispatch', 'Letting a licence expire'], ['ऐसे ऑर्डर स्वीकार करना जो पूरे न कर सकें', 'देर से भेजना', 'लाइसेंस की अवधि खत्म होने देना']),
    },
    {
      id: 'notifications', title: t('Notifications', 'सूचनाएँ'), shot: 'd_alerts',
      callouts: [['css:.dl-notes, .dl-alerts, ul', t('Notifications: new orders, product reviews, stock, policy updates, document expiry', 'सूचनाएँ: नए ऑर्डर, प्रोडक्ट रिव्यू, स्टॉक, पॉलिसी अपडेट, दस्तावेज़ समाप्ति')]],
      what: t('The 🔔 bell page.', '🔔 घंटी वाला पेज।'),
      why: t('So you never miss an order or an important update.', 'ताकि कोई ऑर्डर या ज़रूरी अपडेट न छूटे।'),
      can: t(['New order / waiting too long / cancelled', 'Product approved / changes requested / not accepted', 'Out of stock / low stock', 'Policy updates, policy issues, document expiry, listing paused'], ['नया ऑर्डर / बहुत देर से इंतज़ार / कैंसल', 'प्रोडक्ट मंज़ूर / बदलाव माँगे / स्वीकार नहीं', 'स्टॉक खत्म / कम स्टॉक', 'पॉलिसी अपडेट, पॉलिसी मामले, दस्तावेज़ समाप्ति, लिस्टिंग रोकी']),
      important: t(['You also get WhatsApp/SMS/email messages for orders and important issues.'], ['ऑर्डर और ज़रूरी मामलों के WhatsApp/SMS/ईमेल मैसेज भी आते हैं।']),
      planned: t(['Push notifications when the app is closed are a Planned Feature.'], ['ऐप बंद होने पर पुश नोटिफ़िकेशन Planned Feature है।']),
    },
    {
      id: 'communication', title: t('Customer Communication', 'ग्राहक से संवाद'), shot: 'd_customer',
      callouts: [
        ['text:Call', t('📞 Call the customer', '📞 ग्राहक को कॉल करें')],
        ['text:Map', t('🗺️ Map', '🗺️ नक्शा')],
      ],
      what: t('After you accept an order, the order page shows the customer\'s full name, address, "📞 Call" and "🗺️ Map".', 'ऑर्डर स्वीकार करने के बाद ऑर्डर पेज पर ग्राहक का पूरा नाम, पता, "📞 Call" और "🗺️ Map" दिखते हैं।'),
      why: t('Only to deliver that order — confirm the address or delivery time.', 'केवल उस ऑर्डर की डिलीवरी के लिए — पता या डिलीवरी समय पक्का करना।'),
      important: t(['Do not send promotions, ask for payment outside the platform or share customer details (Customer Communication Policy and Customer Data Policy).', 'The customer\'s phone is hidden again 7 days after delivery.'], ['प्रचार न भेजें, प्लेटफ़ॉर्म के बाहर भुगतान न माँगें और ग्राहक विवरण साझा न करें (Customer Communication Policy और Customer Data Policy)।', 'डिलीवरी के 7 दिन बाद ग्राहक का फ़ोन फिर छिप जाता है।']),
      planned: t(['In-app chat with customers is a Planned Feature.'], ['ग्राहकों के साथ इन-ऐप चैट Planned Feature है।']),
    },
    {
      id: 'legal', title: t('Legal & Agreements', 'कानूनी दस्तावेज़ और एग्रीमेंट'), shot: 'd_legal',
      callouts: [
        ['text:Signed agreement', t('Signed agreement — ⬇️ PDF', 'साइन किया एग्रीमेंट — ⬇️ PDF')],
        ['text:Documents', t('Documents: Dealer Agreement, T&C, Commercial Terms, dealer policies, privacy, refund policy', 'दस्तावेज़: Dealer Agreement, T&C, Commercial Terms, डीलर पॉलिसी, प्राइवेसी, रिफ़ंड पॉलिसी')],
        ['text:View online', t('View online · Download PDF · Print', 'ऑनलाइन देखें · PDF डाउनलोड · प्रिंट')],
      ],
      what: t('Profile → "📜 Legal & Agreements".', 'Profile → "📜 Legal & Agreements"।'),
      why: t('Your signed agreements and all rules that apply to dealers, in simple words and in full.', 'आपके साइन किए एग्रीमेंट और डीलरों पर लागू सारे नियम, आसान भाषा में और पूरे।'),
      can: t(['Download your signed DEALER AGREEMENT PDF', 'Read every dealer policy (listing, pricing & fees, settlement, fulfilment, returns, customer data, IP, product safety, performance, violations)', 'See account health and policy issues', 'See previous agreements'], ['अपना साइन किया DEALER AGREEMENT PDF डाउनलोड करें', 'हर डीलर पॉलिसी पढ़ें (लिस्टिंग, प्राइसिंग और फ़ीस, सेटलमेंट, फ़ुलफ़िलमेंट, रिटर्न, ग्राहक डेटा, IP, प्रोडक्ट सुरक्षा, प्रदर्शन, उल्लंघन)', 'अकाउंट हेल्थ और पॉलिसी मामले देखें', 'पुराने एग्रीमेंट देखें']),
      statuses: STATUS.violation,
      important: t(['If a new version needs your signature, a banner "✍️ A new version needs your signature" appears.', 'To respond to or appeal a policy issue, reply to our email or contact the team (in-app reply is a Planned Feature).'], ['नए वर्ज़न पर साइन चाहिए तो "✍️ A new version needs your signature" बैनर दिखता है।', 'पॉलिसी मामले का जवाब या अपील के लिए हमारे ईमेल का जवाब दें या टीम से संपर्क करें (ऐप में जवाब Planned Feature है)।']),
    },
    {
      id: 'profile', title: t('Profile', 'प्रोफ़ाइल'), shot: 'd_profile',
      callouts: [
        ['text:Business details', t('Business details (address, GSTIN, delivery area, categories)', 'बिज़नेस विवरण (पता, GSTIN, डिलीवरी एरिया, कैटेगरी)')],
        ['text:Email for updates', t('Email for updates — editable', 'अपडेट के लिए ईमेल — बदल सकते हैं')],
        ['text:Legal & Agreements', t('📜 Legal & Agreements', '📜 कानूनी दस्तावेज़')],
        ['text:KYC, documents', t('📝 KYC, documents & onboarding status', '📝 KYC, दस्तावेज़ और ऑनबोर्डिंग स्टेटस')],
        ['text:Sign out', t('Sign out', 'साइन आउट')],
      ],
      what: t('The Profile tab.', 'Profile टैब।'),
      why: t('Your business details decide which orders come to you.', 'आपका बिज़नेस विवरण तय करता है कि कौन से ऑर्डर आपको मिलें।'),
      can: t(['See business details and delivery area', 'Change the email for updates', 'Open Legal & Agreements and onboarding', 'Go to the store, sign out'], ['बिज़नेस विवरण और डिलीवरी एरिया देखें', 'अपडेट वाला ईमेल बदलें', 'Legal & Agreements और ऑनबोर्डिंग खोलें', 'स्टोर पर जाएँ, साइन आउट करें']),
      important: t(['To change address, GSTIN, delivery area or categories, message the team.'], ['पता, GSTIN, डिलीवरी एरिया या कैटेगरी बदलने के लिए टीम को संदेश भेजें।']),
    },
    {
      id: 'security', title: t('Account Security', 'अकाउंट सुरक्षा'),
      what: t('How your dealer account is protected.', 'आपका डीलर अकाउंट कैसे सुरक्षित है।'),
      why: t('Your account shows customer addresses and your bank details, so it must stay private.', 'आपके अकाउंट में ग्राहकों के पते और बैंक विवरण हैं, इसलिए इसे निजी रखना ज़रूरी है।'),
      can: t(['Strong password (8+ characters)', 'Sign-in locks after repeated wrong passwords', 'Bank account stored encrypted and shown masked', 'Signing OTP sent only to your registered mobile/email'], ['मज़बूत पासवर्ड (8+ अक्षर)', 'बार-बार गलत पासवर्ड पर साइन-इन लॉक', 'बैंक खाता एन्क्रिप्टेड और छिपा हुआ', 'साइनिंग OTP केवल रजिस्टर्ड मोबाइल/ईमेल पर']),
      important: t(['Never share your password or OTP with anyone, including people claiming to be from Utsav Ghar.', 'Do not let staff use your login; one login per dealer.'], ['पासवर्ड या OTP किसी से साझा न करें, Utsav Ghar के नाम पर बात करने वालों से भी नहीं।', 'स्टाफ़ को अपना लॉगिन न दें; एक डीलर का एक लॉगिन।']),
      steps: t(['Forgot your password? On the sign-in page tap "Forgot password?" and reset it with the code sent to your mobile.'], ['पासवर्ड भूल गए? साइन-इन पेज पर "Forgot password?" दबाएँ और मोबाइल पर आए कोड से रीसेट करें।']),
      planned: t(['Changing the password from Profile (while signed in), two-step login and a list of signed-in devices are Planned Features. Use "Forgot password?" to set a new password.'], ['साइन इन रहते Profile से पासवर्ड बदलना, दो-चरण लॉगिन और साइन-इन डिवाइस की सूची Planned Features हैं। नया पासवर्ड बनाने के लिए "Forgot password?" उपयोग करें।']),
    },
    {
      id: 'suspension', title: t('Suspension / Restriction', 'निलंबन / प्रतिबंध'),
      what: t('What happens when an account or a listing is paused.', 'अकाउंट या लिस्टिंग रुकने पर क्या होता है।'),
      why: t('To protect customers when there are serious or repeated policy problems, expired mandatory documents or legal requirements (Dealer Violation, Suspension & Termination Policy).', 'गंभीर या बार-बार पॉलिसी समस्याओं, समाप्त ज़रूरी दस्तावेज़ों या कानूनी आवश्यकताओं पर ग्राहकों की सुरक्षा के लिए (Dealer Violation, Suspension & Termination Policy)।'),
      table: [
        [t('Listing paused', 'लिस्टिंग रुकी'), t('One product is hidden from the store. You get "Listing paused".', 'एक प्रोडक्ट स्टोर से छिपा। "Listing paused" सूचना आती है।')],
        [t('Suspended', 'निलंबित'), t('New orders stop; app shows onboarding screens; no new products, uploads or signing. Message explains the reason.', 'नए ऑर्डर रुकते हैं; ऐप ऑनबोर्डिंग स्क्रीन दिखाता है; नए प्रोडक्ट, अपलोड या साइन नहीं। मैसेज में कारण होता है।')],
        [t('Reinstated', 'फिर से चालू'), t('After the issue is fixed, the team reinstates the account.', 'मामला ठीक होने पर टीम अकाउंट फिर चालू करती है।')],
        [t('Terminated', 'समाप्त'), t('Account switched off; signed agreements and records are kept as required by law.', 'अकाउंट बंद; साइन एग्रीमेंट और रिकॉर्ड कानून के अनुसार रखे जाते हैं।')],
      ],
      important: t(['You can appeal within 15 days by replying to our email with reasons and evidence.'], ['15 दिन के अंदर कारण और प्रमाण के साथ हमारे ईमेल का जवाब देकर अपील कर सकते हैं।']),
    },
    {
      id: 'support', title: t('Support', 'सहायता'),
      what: t('How to get help as a dealer.', 'डीलर के रूप में मदद कैसे लें।'),
      why: t('Quick help keeps your orders moving.', 'जल्दी मदद से आपके ऑर्डर चलते रहते हैं।'),
      can: t(['Call or WhatsApp the dealer team', 'Reply to any email from us', 'Ask for a delivery-area change or category change'], ['डीलर टीम को कॉल या WhatsApp करें', 'हमारे किसी भी ईमेल का जवाब दें', 'पासवर्ड रीसेट, डिलीवरी एरिया या कैटेगरी बदलवाएँ']),
      planned: t(['A dealer support-ticket screen in the app is a Planned Feature.'], ['ऐप में डीलर सपोर्ट-टिकट स्क्रीन Planned Feature है।']),
    },
    {
      id: 'problems', title: t('Common Problems', 'आम समस्याएँ'),
      table: [
        [t('"Continue" stays disabled in Documents', 'Documents में "Continue" बंद है'), t('Some required document is missing or rejected — check the status column.', 'कोई ज़रूरी दस्तावेज़ बाकी या अस्वीकार है — स्टेटस कॉलम देखें।')],
        [t('OTP not received', 'OTP नहीं आया'), t('Wait 30 seconds and tap "Resend code"; check email too.', '30 सेकंड रुककर "Resend code" दबाएँ; ईमेल भी देखें।')],
        [t('"Verify with mobile OTP" is grey', '"Verify with mobile OTP" धुंधला है'), t('Tick all 4 boxes and draw your signature first.', 'पहले चारों बॉक्स टिक करें और सिग्नेचर बनाएँ।')],
        [t('No orders coming', 'ऑर्डर नहीं आ रहे'), t('Check status is Approved, products are live with stock, and your delivery PIN areas are set (ask the team).', 'जाँचें स्टेटस Approved है, प्रोडक्ट स्टॉक के साथ लाइव हैं, और डिलीवरी PIN एरिया सेट हैं (टीम से पूछें)।')],
        [t('Order disappeared from New', 'ऑर्डर New से गायब'), t('It was not accepted in time and moved to another dealer, or it was cancelled.', 'समय पर स्वीकार नहीं हुआ और दूसरे डीलर को गया, या कैंसल हुआ।')],
        [t('Wrong delivery code', 'गलत डिलीवरी कोड'), t('Ask the customer to read the code from their order page/message. After 5 tries call the store.', 'ग्राहक से उनके ऑर्डर पेज/मैसेज से कोड पढ़वाएँ। 5 कोशिशों के बाद स्टोर को कॉल करें।')],
        [t('Product stuck "Under review"', 'प्रोडक्ट "Under review" में अटका'), t('Reviews usually take 1–2 working days. Contact the team if longer.', 'रिव्यू में आम तौर पर 1–2 कार्य दिवस लगते हैं। ज़्यादा हो तो टीम से संपर्क करें।')],
        [t('Forgot password', 'पासवर्ड भूल गए'), t('Sign-in page → "Forgot password?" → code to your mobile → new password.', 'साइन-इन पेज → "Forgot password?" → मोबाइल पर कोड → नया पासवर्ड।')],
      ],
    },
    {
      id: 'faq', title: t('Frequently Asked Questions', 'अक्सर पूछे जाने वाले प्रश्न'),
      faq: [
        [t('Do I see the price customers pay?', 'क्या मुझे ग्राहक की कीमत दिखती है?'), t('No. You see your dealer price only.', 'नहीं। आपको केवल अपना डीलर प्राइस दिखता है।')],
        [t('When do I get paid?', 'भुगतान कब मिलता है?'), t('As per the settlement days in your Commercial Terms, after delivery, less any refunds, returns or penalties.', 'आपकी Commercial Terms के सेटलमेंट दिनों के अनुसार, डिलीवरी के बाद, रिफ़ंड, रिटर्न या पेनल्टी घटाकर।')],
        [t('Can I collect cash on delivery?', 'क्या डिलीवरी पर नकद ले सकते हैं?'), t('No. Every order is prepaid.', 'नहीं। हर ऑर्डर प्रीपेड है।')],
        [t('Why must I sign again?', 'दोबारा साइन क्यों करना है?'), t('A new agreement version or new commercial terms were published.', 'नया एग्रीमेंट वर्ज़न या नई कमर्शियल शर्तें प्रकाशित हुईं।')],
        [t('Can I reject an order after packing?', 'क्या पैक करने के बाद ऑर्डर अस्वीकार कर सकते हैं?'), t('No — contact the store.', 'नहीं — स्टोर से संपर्क करें।')],
        [t('What is the grace period?', 'ग्रेस पीरियड क्या है?'), t('Dealers added by our team get 14 days to finish KYC and sign while still receiving orders.', 'टीम द्वारा जोड़े डीलरों को KYC और साइन पूरा करने के लिए 14 दिन मिलते हैं, तब तक ऑर्डर आते रहते हैं।')],
        [t('Is the UG Dealer app different from the website?', 'क्या UG Dealer ऐप वेबसाइट से अलग है?'), t('No, it shows the same dealer app, with camera, vibration and call/map shortcuts on phones.', 'नहीं, यह वही डीलर ऐप दिखाता है, फ़ोन पर कैमरा, वाइब्रेशन और कॉल/मैप शॉर्टकट के साथ।')],
      ],
    },
  ],
};
